undertow-io/undertow

core/src/main/java/io/undertow/server/handlers/resource/FileResourceManager.java
isSymlinkSafe() fixed so that it iterates through all entries in safePaths. Previous behavior was that it would return true/false on the first iteration.
I ran into the issue when trying to configure symbolic link following in FileResourceManager. In my project there are two symlinked folders inside the main deployment folder, and it turned out that it was able to process symlinks only if there was a single string in safePaths parameter.
=> FileResourceManager not handling multiple safe paths properly

servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
HttpServletRequest is used as an event payload for @Initialzied(RequestScoped) CDI events. Having a nice toString() makes inspecting events easier plus the object looks better in a debugger
=> HttpServletRequestImpl.toString()

core/src/main/java/io/undertow/util/Headers.java, core/src/test/java/io/undertow/util/HeadersUtilsTestCase.java
Merging this fix to 1.1 branch
=> UNDERTOW-387 Fixed parsing of boundary from Content-Type header to ignore semicolon

core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java
The resource can specify its mime type, but only if the exchange does not have one already. Therefore move the inquiry inside the conditional block.
=> avoid querying resource for content type if not needed

core/src/main/java/io/undertow/security/api/SecurityContext.java, core/src/main/java/io/undertow/security/impl/BasicAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/CachedAuthenticatedSessionMechanism.java, core/src/main/java/io/undertow/security/impl/ClientCertAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/DigestAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/ExternalAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/GSSAPIAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/SingleSignOnAuthenticationMechanism.java, servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java, servlet/src/main/java/io/undertow/servlet/handlers/security/CachedAuthenticatedSessionHandler.java, servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Whilst all current mechanisms make use of this it should not be seen as an exclusive way to access identities and accounts.
The next step for Elytron is going to be to adjust the mechanisms to make use of the Elytron domains and realms directly.
=> [UNDERTOW-421] Deprecate the getIdentityManager method on the SecurityContext

core/src/main/java/io/undertow/security/api/SecurityContextFactory.java, core/src/main/java/io/undertow/security/handlers/AbstractSecurityContextAssociationHandler.java, core/src/main/java/io/undertow/security/handlers/SecurityInitialHandler.java
Instead a new AbstractSecurityContextAssociationHandler can be extended to provide custom implementations.
=> [UNDERTOW-463] Deprecate the SecurityContextFactory.

core/src/main/java/io/undertow/security/api/AuthenticationMechanismContext.java, core/src/main/java/io/undertow/security/api/SecurityContext.java, core/src/main/java/io/undertow/security/handlers/AuthenticationMechanismsHandler.java, core/src/main/java/io/undertow/security/impl/SecurityContextImpl.java
Instead add a specific interface for if Undertow AuthenticationMechanisms are supported.
=> [UNDERTOW-462] Deprecate the AuthenticationMechanism handling on the SecurityContext interface.

core/src/main/java/io/undertow/security/impl/AbstractSecurityContext.java, core/src/main/java/io/undertow/security/impl/SecurityContextImpl.java
Split out the generic notification handling side of the SecurityContext implementation into an abstract base class so future SecurityContext implementations can focus just on the actual authentication.
Note: I have chosen not to add the deprecated methods to the abstract class as I believe once Java 8 is available it will be better to handle them on the interface to make implementing those methods entirely optional.
=> [UNDERTOW-466] Split the SecurityContextImpl in two.

core/src/main/java/io/undertow/server/handlers/resource/PathResource.java, core/src/test/java/io/undertow/server/handlers/file/FileHandlerSymlinksTestCase.java
Two minor fixes, related to my previous pull request.
The first simplifies the file channel opening in the PathResource class. In my previous pull request I changed the Xnio channel opener to the standard 1.7+ method FileChannel.open() everywhere, except here. This will make it consistent across the project.
The second fix changes the symlink unit test @After method to not fail on Windows systems.
=> Two minor fixes.

core/src/main/java/io/undertow/server/session/InMemorySessionManager.java, core/src/main/java/io/undertow/server/session/SessionManager.java, core/src/main/java/io/undertow/server/session/SessionManagerStatistics.java
The basic motivation behind this change is that the distributed session manager is not going to want to implement statistics via inheritance.
Once WF is upgraded to the next release of Undertow, we can change the logic for obtaining the SessionManagerStatistics object from the current "instanceof" with a simple call to the getStatistics() method - although the old logic will continue to work.
=> Provide statistics via a SessionManager method instead of forcing inheritance on implementations.

websockets-jsr/src/main/java/io/undertow/websockets/jsr/annotated/AnnotatedEndpointFactory.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedGenericClientEndpoint.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/GenericWebSocketClientEndpoint.java
Shadow synthetic bridge methods are generated with annotations as of JDK8. This causes the bridged method with the @OnMessage annotation to be scanned by the AnnotatedEndpointFactory. The bridged method has an Object parameter which causes the exception:
javax.websocket.DeploymentException: UT003029: Could not find message parameter on method ....... onMessage(java.lang.Object)
The fix is to not scan bridged methods. This works fine in JDK7 and JDK8. Similar problem in myBatis: https://github.com/mybatis/mybatis-3/issues/237
=> Prevent "Could not find message parameter on method" for methods with generic parameters

core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Notify listeners of an invalidated session from outside the synchronized
block.
=> Proposed correction to UNDERTOW-479

core/src/main/java/io/undertow/util/CopyOnWriteMap.java
I have found a possible bug while browsing through the code.
=> Making replace(K,V) call thread safe.

core/src/main/java/io/undertow/security/impl/SingleSignOnAuthenticationMechanism.java, core/src/main/java/io/undertow/server/Connectors.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/main/java/io/undertow/server/JvmRouteHandler.java, core/src/main/java/io/undertow/server/handlers/RequestDumpingHandler.java, core/src/test/java/io/undertow/server/handlers/CookieHandlingTestCase.java
This patch should resolve UNDERTOW-488 by ensuring that response cookies can be set multiple times with the same name=value mapping.
=> UNDERTOW-488 Allow setting the same cookie more than once

core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
According to the [RFC7540](https://tools.ietf.org/html/rfc7540) there should be check for stream ID number of frames of types DATA, HEADERS, GOAWAY and SETTINGS and raise PROTOCOL_ERROR if invalid stream ID has been passed.
I've added that check into Http2FrameHeaderParser.java as there is already similar check for PING frame type.
Although as I browsed through the codebase I saw that similar check is made also in [Http2Channel.java](https://github.com/undertow-io/undertow/blob/90789748d3b493d7a233a4ef5ba8ae33032c1543/core/src/main/java/io/undertow/protocols/http2/Http2Channel.java#L259) and also e.g. in [ping parser itself](https://github.com/undertow-io/undertow/blob/90789748d3b493d7a233a4ef5ba8ae33032c1543/core/src/main/java/io/undertow/protocols/http2/Http2PingParser.java#L43). As I …
=> HTTP2 added missing checks on stream IDs for frame types when parsing

core/src/main/java/io/undertow/security/impl/InMemorySingleSignOnManager.java, core/src/main/java/io/undertow/security/impl/SingleSignOnAuthenticationMechanism.java, core/src/main/java/io/undertow/security/impl/SingleSignOnManager.java
... instead of just its identifier.
This is required for the distributable implementation to propagate the transaction context of the SSO to be removed - since the removal is performed while the SSO is locked.  This is needed to fix:
https://issues.jboss.org/browse/WFLY-5473
https://issues.jboss.org/browse/WFLY-5422
=> Modify SingleSignOnManager.removeSingleSignOn(...) to accept SSO itself

servlet/src/main/java/io/undertow/servlet/handlers/security/CachedAuthenticatedSessionHandler.java
Removes the need for duplication in org.wildfly.clustering.web.undertow.session.DistributableSession#AUTHENTICATED_SESSION_ATTRIBUTE_NAME.
=> Make visibility CachedAuthenticatedSessionHandler#ATTRIBUTE_NAME public

servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java
- fixes "memory leak" when testing with arquillian servlet protocol.
see https://github.com/wildfly/wildfly/issues/8263
=> Make sure .destroy() is called for all servlets on undeploy

servlet/src/main/java/io/undertow/servlet/core/InMemorySessionManagerFactory.java
Wrong call to create a session.
JIRA: https://issues.jboss.org/browse/UNDERTOW-586
=> [UNDERTOW-586]: max-active-sessions doesn't work with enabled statistics

pom.xml, zanata.xml
I created a project on the JBoss Zanata server as well, https://translate.jboss.org/project/view/undertow. I'm currently the only maintainer, but can add others that need to be. I've only created the 2.0 version, but it will be easy to back port if we need to.
=> Add zanata configuration and plugin for internationalization support.

core/src/main/java/io/undertow/security/impl/BasicAuthenticationMechanism.java
This only needs to be applied to the 1.4.x branch, the master branch is on Java 8 so does not require this.
=> [UNDERTOW-641] Create the empty map in advance so it is of the correct type when it is used.

core/src/main/java/io/undertow/attribute/SecureExchangeAttribute.java
Uses HttpString#equalsToString() to test the protocol of the given exchange instead of HttpString#equals().
=> Fixes small bug in SecureExchangeAttribute#readAttribute()

core/src/main/java/io/undertow/Undertow.java, core/src/test/java/io/undertow/server/StopTestCase.java
Undertow should not throw a NullPointerException if stopping a server
that is not correctly started.
This could also be merged to the most recent 1.X branch as well.
=> Add null-checks when stopping server

core/src/main/java/io/undertow/util/HeaderValues.java
Hey,
just saw that the size parameter is not used anymore due to previous fixes/refactorings.
Cheers,
Christoph
=> Removed unused parameter in HeaderValues.clearInternal()

core/src/main/java/io/undertow/websockets/core/function/ChannelFunctionFileChannel.java
FileChannel.position(long) and FileChannle.truncate(int) are supposed to return itself. Fixing the code to not create new instance but rather return itself as it is supposed to.
=> ChannelFunctionFileChannel preventing creation of new instances when not needed 

core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
Hey,
I just stumpled upon this unused parameter and removed it. Keep up the good work.
Cheers,
Christoph
=> Removed unused parameter in HttpTransferEncoding.handleResponseConduit()

core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
The commit here adds a new constructor to LearningPushHandler to allow it to be used as a configured filter in WildFly server. Please see this forum discussion https://developer.jboss.org/message/956914#956914 for more details.
=> Add a convenience constructor to LearningPushHandler

core/src/main/java/io/undertow/util/PathTemplate.java, core/src/test/java/io/undertow/server/handlers/RoutingHandlerTestCase.java, core/src/test/java/io/undertow/util/PathTemplateTestCase.java
hallo *,
i extend PathTemplate to support wildcard matching in path string
for example path url like /docs/{docId}/* match /docs/test/my.
i hope that is ok for the first pull request.
Thanks,
Arek
=> Extend PathTemplate (match method) to support wildcard matching in path string

core/src/main/java/io/undertow/util/MimeMappings.java
Because they were giving me problems in Chrome when serving static font files
=> Add fonts mime types

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
At load with WebSockets on SSL, we have been seeing IllegalStateException
exceptions which we suspect are due to dirty connection closes. The
observed stack in 1.3.23.Final is:
```
[org.xnio.nio] (default I/O-15) XNIO000011: Task io.undertow.protocols.ssl.SslConduit$1@959ab9 failed with an exception: java.lang.IllegalStateException: UT000091: Buffer has already been freed
at io.undertow.server.DefaultByteBufferPool$DefaultPooledBuffer.getBuffer(DefaultByteBufferPool.java:196)
at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:744)
at io.undertow.protocols.ssl.SslConduit.doHandshake(SslConduit.java:603)
at io.undertow.protocols.ssl.SslConduit.access$500(SslConduit.java:63)
at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1029)
at …
```
=> IllegalStateException "Buffer has already been freed" in SslConduit.doUnwrap finally block

core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
- HTTP2 request MUST NOT contain 'connection' header
- HTTP2 request MAY contain 'te' header but if so, then just with value 'trailers'
- fix: check for 'connect' method (used contains instead of wrong equals method now)
=> [UNDERTOW-822] HTTP2 headers - another HTTP2 spec compliance checks

core/src/main/java/io/undertow/client/spdy/SpdyClientConnection.java
In the SPDY protocol the order of streams is important.
Multi-thread apps that use undertow to interact with SPDY servers
must use a synchronized request in order to guarantee that streams
don't arrive in a messed order in the endpoint.
=> SPDY Connection: Make synchronized requests

core/src/main/java/io/undertow/util/LocaleUtils.java, core/src/test/java/io/undertow/util/LocaleUtilsTestCase.java
According to the newer standard RFC7231 (HTTP/1.1), the Accept-Language can
be used to indicate the desired languages by using language tags as defined
in RFC5646 (BCP 47).
This obsoletes the older standards RFC2616 and RFC2068, which had a different
definition for the content of Accept-Language.
Nevertheless, the newer definition is a superset of the old one, and therefore
the language tag parser should be changed to accept the newer BCP47 compatible
tags (which should not make any difference for almost all real world language
tags).
As we should parse language tags (i.e. user generated content) as lenient as possible, we simply can use Locale.forLanguageTag, which itself does all the magic to parse given inputs as lenient as possible.
=> Parse languages according to RFC7231 / RFC5646 / BCP47

websockets-jsr/src/main/java/io/undertow/websockets/jsr/EncodingFactory.java, websockets-jsr/src/main/java/io/undertow/websockets/jsr/annotated/AnnotatedEndpointFactory.java, websockets-jsr/src/main/java/io/undertow/websockets/jsr/annotated/BoundMethod.java
Hey,
As of Java 8 there is the possibilty to call Method.getParameterCount(), which is a much more efficient variant in case just the parameter count is needed. Method.getParameterTypes() clones the underlying parameters and therefore creates unnecessary pressure on the heap in such cases.
I revised all places to use the new method.
Cheers,
Christoph
=> Reduce memory consumption caused by Method.getParameterTypes()

core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java
https://issues.jboss.org/browse/UNDERTOW-852
https://issues.jboss.org/browse/JBEAP-6258
https://issues.jboss.org/browse/UNDERTOW-851
https://issues.jboss.org/browse/JBEAP-6257
=> [UNDERTOW-852] Web server should return 501 for unknown METHOD requests

core/src/main/java/io/undertow/server/HttpServerExchange.java
To be par with the Javadoc on `getRequestCharset()` and `getResponseCharset()`, also return `ISO_8859_1` instead of `null` in the case of an absent Content-Type header.
=> Return default charset if Content-Type header is absent.

core/src/main/java/io/undertow/security/impl/DigestAuthenticationMechanism.java, core/src/test/java/io/undertow/server/security/ParseDigestAuthorizationTokenTestCase.java
Hey,
I just noticed that we could switch to an enhanced EnumSet instead of a HashSet for mandatory tokens inside DigestAuthenticationMechanism. As it's backed by a simple array, access to the tokens will be much faster. 
While doing so, I adjusted a test inside the same context of digests to use an EnumMap instead of a HashMap.
Cheerio,
Christoph
=> Switch to enhanced EnumSet in DigestAuthenticationMechanism

core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java, core/src/test/java/io/undertow/server/security/SpnegoAuthenticationTestCase.java, core/src/test/resources/krb5.conf
* Updated enctypes in krb5.conf to enctypes properly working also on IBM JDK
* Setup environment for krb5.conf location moved before actually starting the server.
* Solved issue when token decoded from the header contains improperly 0 bytes at the end, making the token byte[] corrupted by using Base64.decode.
=> UNDERTOW-545 - SPNEGO test fixed.

core/src/main/java/io/undertow/server/handlers/encoding/EncodingHandler.java
Ran into this while attempting to load jsp, the forward request causes a `UT000004: getResponseChannel() has already been called`
=> EncodingHandler doesn't wrap exchanges without available channel

core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java
Call holders.remove(holder) instead of it.remove() that is not supported
for a CopyOnWriteArrayList's iterator.
JIRA: https://issues.jboss.org/browse/UNDERTOW-931
=> (1.4.x) [UNDERTOW-931] Fix removal of ChannelUpgradeHandler's protocol.

core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java
Call holders.remove(holder) instead of it.remove() that is not supported
for a CopyOnWriteArrayList's iterator.
JIRA: https://issues.jboss.org/browse/UNDERTOW-931
=> [UNDERTOW-931] Fix removal of ChannelUpgradeHandler's protocol.

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Context.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPHandler.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterProxyTarget.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Node.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/VirtualHost.java
https://issues.jboss.org/browse/UNDERTOW-932
mod_cluster hot standby workers are always in error mode resulting in 503
https://issues.jboss.org/browse/UNDERTOW-898
Failover targets should be chosen deterministically 
Also includes work for (not yet done in native module)
https://issues.jboss.org/browse/MODCLUSTER-557
Hot standby workers should be excluded from the deterministic failover candidate list
=> [1.4] UNDERTOW-932 hot standby broken + UNDERTOW-898 deterministic failover

core/src/main/java/io/undertow/server/handlers/ProxyPeerAddressHandler.java
Jira: https://issues.jboss.org/browse/UNDERTOW-847
JBEAP Jira: https://issues.jboss.org/browse/JBEAP-8087
1.4.x branch commit is: https://github.com/undertow-io/undertow/commit/a5ae059b824bd67e22e16a5e12c77293c0753a23
This is needed by EAP 7.0 CP release.
=> UNDERTOW-847 fixed appending port 80 if "X-Forwarded-Port" is empty

core/src/main/java/io/undertow/security/impl/SingleSignOnAuthenticationMechanism.java
https://issues.jboss.org/browse/UNDERTOW-976
=> UNDERTOW-976 SingleSignOnAuthenticationMechanism fails to destroy SSO following session invalidation if session was registered with SSO on remote node

core/src/main/java/io/undertow/websockets/core/WebSockets.java
Adds PooledByteBuffer overloads to all the send methods of the WebSockets class.
Also fixes some documentation inconsistencies.
=> Websockets PooledByteBuffer API

core/src/main/java/io/undertow/protocols/ssl/UndertowAcceptingSslChannel.java
There are several options to fix the issue, either catch only `IOException`, but as this was introduced due https://github.com/undertow-io/undertow/commit/cb0a53e57a2ccbc69789c05c06b381939837845c, where it should also be done for any other issues such as RuntimeException, catching both.
The other option would be to catch directly `Throwable`
=> Fixing findbugs issue REC_CATCH_EXCEPTION

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/main/java/io/undertow/util/BadRequestException.java, core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java, core/src/test/java/io/undertow/server/protocol/http/ParserResumeTestCase.java, core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
This PR contains the following changes:
- UNDERTOW-1021 AJP listener should log at DEBUG level when handling 400 Bad Request like wrong magic number and invalid Content-Length
- UNDERTOW-1020 AjpRequestParser should output DEBUG log when exceeding max-parameters/max-headers
- Consolidate Http/AjpRequestParser's BadRequestException into the io.undertow.util package
=> UNDERTOW-1020 / UNDERTOW-1021 for 1.4.x branch

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/main/java/io/undertow/util/BadRequestException.java, core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java, core/src/test/java/io/undertow/server/protocol/http/ParserResumeTestCase.java, core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
This PR contains the following changes:
- UNDERTOW-1021 AJP listener should log at DEBUG level when handling 400 Bad Request like wrong magic number and invalid Content-Length
- UNDERTOW-1020 AjpRequestParser should output DEBUG log when exceeding max-parameters/max-headers
- Consolidate Http/AjpRequestParser's BadRequestException into the io.undertow.util package
=> UNDERTOW-1020 / UNDERTOW-1021 for 1.3.x branch

core/src/main/java/io/undertow/protocols/alpn/JettyAlpnProvider.java
NOTE: If approved, this has to be picked also to 1.4.x branch too.
=> [UNDERTOW-1050] minor: just a fix of a typo in name of JettyAlpnProvider

servlet/src/main/java/io/undertow/servlet/handlers/ServletDebugPageHandler.java
This change improves the HTTP 500 page that normally displays exception stacktraces. Key changes:
* bit more spacious HTML element alignment
* display complete stacktraces (not just the main stacktrace)
=> Improve HTTP 500 page

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
Occasionally I/O threads would get stuck in an infinite loop, throwing the following exception over and over:
`ERROR [default I/O-8] [org.xnio.listener] XNIO001007: A channel event listener threw an exception: java.lang.IllegalStateException: XNIO000017: Buffer was already freed
at org.xnio.ByteBufferSlicePool$PooledByteBuffer.getResource(ByteBufferSlicePool.java:206)
at org.xnio.ByteBufferSlicePool$PooledByteBuffer.getResource(ByteBufferSlicePool.java:176)
at io.undertow.server.protocol.framed.AbstractFramedChannel.flushSenders(AbstractFramedChannel.java:481)
at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameWriteListener.handleEvent(AbstractFramedChannel.java:774)
at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameWriteListener.handleEvent(AbstractFramedChann …
=> Fix potential infinite loop in AbstractFramedChannel#flushSenders

pom.xml
Lets have defined explicit surefire plugin version to prevent usage of different versions on different environments.
=> Explicit surefire plugin version

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
This is a workaround for JBEAP-11176 (which ends up not having anythign to do with the external SASL mechanism, just a programmatic MCC that never calls MCC.close(). [https://issues.jboss.org/browse/JBEAP-11176]
@stuartwdouglas What do you think should be happening here? In this state, when notifyReadClosed() gets called and throws (SslConduit:614) the underlying connection never seems to get closed, so either closing it explicitly, or calling notifyWriteClosed() seems to be required in this state.
FWIW, the other state here is:
runListener: false, FLAG_WRITE_CLOSED: not set, FLAG_WRITE_REQUIRES_READ: not set.
Also at the time, the client has completed execution and exited.
=> test fix / workaround for wildfly shutdown with MCC that hasn't called close.

core/src/main/java/io/undertow/conduits/GzipStreamSourceConduit.java, core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java
GzipStreamSourceConduit and InflatingStreamSourceConduit take
an inflater pool to allow reuse of expensive objects.
=> Support pooling Inflater instances for reduced jni overhead

core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/server/Connectors.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/main/java/io/undertow/util/DateUtils.java, core/src/main/java/io/undertow/util/LegacyCookieSupport.java, core/src/main/java/io/undertow/util/Rfc6265CookieSupport.java, core/src/test/java/io/undertow/util/CookiesTestCase.java, servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingTestCase.java
Please backport the master's commit 04ced07 to 1.3.x branch. 
In addition to the commit, I would like to add a new system property `io.undertow.cookie.DEFAULT_ENABLE_RFC6265_COOKIE_VALIDATION` for enabling RFC6265 cookie validation. 
I understand that Undertow does not go in for config via system properties but I think the feature is not albe to be enabled in EAP 7.0.z without this. (A new configurable parameter inside subsystem requires the management model change which does not happen during EAP 7.0.z release.)
=> UNDERTOW-1095 UNDERTOW-1096 for 1.3.x branch

core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
The path being checked is coming from the request, which doesn't
depend on the platform file separator.
=> Apply fix for UNDERTOW-432 to Windows systems

core/src/main/java/io/undertow/websockets/core/protocol/Handshake.java
If a websocket ExtensionHandshake is available but fails negotiation against the client-supplied extensions, the websocket connection will die with a null pointer exception.
The problem is that the Handshake class does not check the result of `ExtensionHandshake.accept(WebSocketExtension ext)` for null (which means the extension should not be used) before adding this extension to the list of selected and configured extensions on the connection. The null blows up later.
This commit checks whether the available extension was accepted by checking for a null return value from the extension's `accept` method. It stops checking for `ext != null` because this is unnecessary.
=> UNDERTOW-1139 Not-accepted websocket extension will NPE connection

core/src/main/java/io/undertow/UndertowMessages.java
https://issues.jboss.org/browse/UNDERTOW-1142
=> [UNDERTOW-1142] fix of two minor typos in log messages

servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
IE (at least IE8, IE9 and IE10) sends the negotiation token in every request for kerberos authentication. This is only reproducible in undertow-1.3, because in undertow-1.4 CachedAuthenticatedSessionMechanism is being called before than NegotiationMechanism. This patch fixes the order of those mechanisms in undertow-1.3 as they are in undertow-1.4. 
Issue: https://issues.jboss.org/browse/UNDERTOW-1149
EAP 7.0.x Issue: https://issues.jboss.org/browse/JBEAP-12407
Upstream Issue: Upstream not required
=> [UNDERTOW-1149] Move CachedAuthenticatedSessionMechanism before than NegotiationMechanism to avoid kerberos negotiation on each request in IE

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPConfig.java
The commit here fixes the issue reported in https://issues.jboss.org/browse/UNDERTOW-1016.
The commit just reorders the if blocks which check whether an address is unresolved and whether it is a "any" local address, such that it first checks whether the address is unresolved. This prevents the NPE while checking `isAnyLocalAddress()` since the `managementSocketAddress.getAddress()`, as per its API contract can return null for unresolved address.
=> [master branch] UNDERTOW-1016 Fix potential NPE while dealing with unresolved InetSocketAddress

core/src/main/java/io/undertow/Undertow.java, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java, core/src/test/java/io/undertow/server/protocol/proxy/ProxyProtocolTestCase.java
This fixes a typo in the PROXY protocol code (ProxyProtocolReadListener.java:38) that eliminated the "UNKNOWN" handling. In addition to that, the state machine for that case was too narrow, requiring at least a space character after the "UNKNOWN".
Apart from fixing these issues, this PR adds test coverage for the "UNKNOWN" handling code and gives some general love to the PROXY protocol code.
=> UNDERTOW-1166: make PROXY protocol implementation compliant with spec

core/src/main/java/io/undertow/client/http/HttpClientConnection.java, core/src/main/java/io/undertow/util/ConnectionUtils.java
In some (likely failure) cases I've noticed the undertow client
fails to execute any ClientCallback methods.
I've noticed NPEs in the the logs from SslConduit.doUnwrap, so
it's possible this is caused by UNDERTOW-1156.
=> HttpClientConnection catches failures more broadly

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/client/ALPNClientSelector.java, core/src/main/java/io/undertow/client/ajp/AjpClientConnection.java, core/src/main/java/io/undertow/client/http/HttpClientProvider.java, core/src/main/java/io/undertow/client/http/HttpRequestConduit.java, core/src/main/java/io/undertow/client/http2/Http2ClientConnection.java, core/src/main/java/io/undertow/client/http2/Http2PriorKnowledgeClientProvider.java, core/src/main/java/io/undertow/conduits/AbstractFixedLengthStreamSinkConduit.java, core/src/main/java/io/undertow/conduits/AbstractFramedStreamSinkConduit.java, core/src/main/java/io/undertow/conduits/ChunkedStreamSourceConduit.java, core/src/main/java/io/undertow/conduits/DeflatingStreamSinkConduit.java, core/src/main/java/io/undertow/conduits/FixedLengthStreamSourceConduit.java, core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/protocols/ssl/SslConduit.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/main/java/io/undertow/server/handlers/RequestBufferingHandler.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java, core/src/main/java/io/undertow/server/protocol/http/AlpnOpenListener.java, core/src/main/java/io/undertow/server/protocol/http/HttpOpenListener.java, core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java, core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java, core/src/main/java/io/undertow/server/protocol/http/PipeliningBufferingStreamSinkConduit.java, core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java, servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
There are several places where errors (OutOfMemoryError, for
instance) cause us not to return pooled buffers, and continue
a memory death spiral.
=> Attempt to recover from Errors and RuntimeExceptions

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPInfoUtil.java
The DUMP and INFO output of the undertow mod_cluster implementation contains formatting errors. This fix updates dump and info functions so that the output matches that of apache httpd mod_cluster.
=> UNDERTOW-1196 match DUMP and INFO output of apache httpd mod_cluster

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPConstants.java
The value of FLUSH_PACKET_STRING in the mod_cluster MCMP implementation
should be set to "flushpackets", not "flushpacket".
The error can be reproduced by configuring the mod_cluster subsystem with property flush-packets set to true.
Apache httpd mod_cluster-1.3.7 accepts the node. Undertow mod_cluster implementation produces an error:
ERROR: UT005043: Error in processing MCMP commands: Type:SYNTAX, Mess: SYNTAX: Invalid field flushpackets in message
This fix should be applied to all active branches.
=> UNDERTOW-1195 correct value of FLUSH_PACKET_STRING in the mod_cluster MCMP implementation

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPHandler.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPInfoUtil.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPWebManager.java
ModCluster handles ttl in milliseconds. Client sends ttl in seconds, but MCMPHandler does not convert the incoming value to milliseconds. Setting the ttl to 600 - client-side - results in a ttl of 0.6 seconds in undertow. This is not as intended.
To keep DUMP and INFO output similar to that of apache httpd mod_cluster, MCMPInfoUtil should convert ttl from milliseconds to seconds. MCMPWebManager should match that behaviour.
=> UNDERTOW-1206 MCMPHandler must convert ttl from seconds to milliseconds

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/NodeConfig.java
The NodeConfig defaults for queueNewRequests and ttl are always overridden in the
constructor. It is better to have the defaults specified in ModCluster.
This also solves the issue where the ttl is set to 0 instead of 60000.
=> UNDERTOW-1205 move NodeConfig queueNewRequests and ttl defaults to ModCluster

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
The default value of cacheConnections (smax) is currently set to 8. This is the number of idle connections that will be kept alive per IO thread. ioThreads is set to the number of available processors with a minimum of 2 (Undertow.java).
These idle connections unnecessarily consume cpu, memory and network resources. This becomes a big issue in large scale environments with over 4100 backend servers (4100 (backend servers) * 8 (conns) * 2 (iothreads) = 65600 idle connections, TCP stack only supports up to 65535 ports).
By setting the default value of cacheConnections (smax) to 1, idle connections timeout when they reach their ttl, not before. There is no performance impact. The default value can still be overriden client-side by setting smax in the mod_cluster configuration.
=> UNDERTOW-1204 mod_cluster proxy: set default value of cacheConnections (smax) to 1

core/src/main/java/io/undertow/server/handlers/proxy/ProxyConnectionPool.java
The number of idle connections should not drop below coreCachedConnections.
=> UNDERTOW 1219 ProxyConnectionPool closes too many idle connections when they reach their ttl

core/src/main/java/io/undertow/UndertowLogger.java
Hey, I was experimenting with [using Undertow as a module on Java 9](https://github.com/moditect/moditect#example) (explicit module, not automatic) and creating a modular runtime image with it.
In that course I noticed that there currently is a mandatory dependence to the _java.sql_ module due to a specific log handler and exposure of `SQLException` in a few signatures of `UndertowLogger`. This proposed change allows to make that dependence optional (`requires static java.sql` in terms of the module descriptor), which reduces size of a runtime image with an Undertow Hello World from 29 MB to 25 MB. The price is a slightly less explicit signature of these methods. An alternative would be to create a separate logger interface just for the methods with a `SQLException` parameter.
I thought …
=> Avoid mandatory dependency to java.sql module

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Node.java
In an Undertow setup with IoThreads = 1, cacheConnections (smax) = 2, maxConnections = 16 and ttl = 10s, Apache HTTP server benchmarking tool load tests reveal:
- 1 connection: all good, no connections closed
- 2 concurrent connections: all good, no connections closed
- 3-16 or more concurrent connections: connections closed **before** they reach their ttl
I expect the 3rd to 16th connection to be maintained until they reach their ttl. But this does not happen.
mod_cluster java documentation:
> smax: Soft maximum idle connection count (that is the smax in worker mod_proxy documentation). The maximum value depends on the httpd thread configuration (ThreadsPerChild or 1).
> ttl:  Time to live (in seconds) for **idle connections above smax**
URL: …
=> UNDERTOW-1222 modcluster Node getMaxCachedConnections should return maxConnections

core/src/main/java/io/undertow/client/ajp/AjpClientConnection.java, core/src/main/java/io/undertow/protocols/ajp/AjpClientChannel.java
Added a few debug log calls similar to those defined in HttpClientConnection.
Set currentRequest to null after it is set to failed, similar to HttpClientConnection.
Emptied AjpClientChannel#handleBrokenSourceChannel, because:
- IoUtils.safeClose(source, sink) is already called in AjpClientChannel#closeSubChannels
- Debug log entry already sent in AbstractFramedChannel#markReadsBroken
- IoUtils.safeClose(this) is already called in AjpClientChannel#lastDataRead
Emptied AjpClientChannel#handleBrokenSinkChannel, because:
- IoUtils.safeClose(source, sink) is already called via AjpClientChannel#closeSubChannels
- Debug log entry already sent in AbstractFramedChannel#markWritesBroken
- IoUtils.safeClose(this) is already called in AjpClientChannel#lastDataRead
=> UNDERTOW-1200 AjpClientConnection should handle a closed connection like HttpClientConnection

core/src/main/java/io/undertow/client/http/HttpClientConnection.java
Function equalToString(String) is more efficient than equals(HttpString) as it does not require an additional object allocation.
Prefix header constants to make clear we are dealing with a header, not with some other constant such as CLOSE_REQ, CLOSED.
=> UNDERTOW-1229 HttpClientConnection should use equalToString and prefix header constants

core/src/main/java/io/undertow/util/MultipartParser.java, core/src/test/java/io/undertow/util/MimeDecodingTestCase.java, core/src/test/java/io/undertow/util/mime-multiline.txt
Modified multipart header parsing to allow for headers that span multiple lines per section 2.2.3 of RFC2822.
=> UNDERTOW-1237 Added multiline header parsing (master)

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPAdvertiseTask.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPConfig.java
Added variable including getter setter methods to allow the modcluster
advertise ttl to be set.  The default multicast ttl is now set to 10,
this matches the apache httpd mod_cluster behaviour.
Reordered several methods and variables so that their order matches.
Renamed variable group to address because it contains the advertise address,
not the advertise group.  Used the createUdpServer method as it requires
one less argument.
=> UNDERTOW-1267 add option to allow the modcluster advertise ttl to be set

core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Proper test for https://issues.jboss.org/browse/UNDERTOW-1193
When approved and merged, please cherry-pick to all related branches.
=> [UNDERTOW-1193] Test for parsing + vs %20 when both used in path

core/src/test/java/io/undertow/util/PathTemplateTestCase.java, findbugs-exclude.xml
This fix is needed only for 1.4.x branches, which are still java 1.7 compatible.
=> Compilation issue fix - Map types required for java 1.7

karaf/pom.xml
- This contains an update of Karaf module from 4.0.7 to 4.2.0.M2
so we are able to build Undertow with JDK9.
=> [UNDERTOW-1287] Karaf update to 4.2.0.M2 version which supports Java 9.

pom.xml
A version bump from 2.0.0.Final to 2.0.1.Final-SNAPSHOT accidentally
updated the version of jboss-logmanager dependency.
=> Revert jboss-logmanager version

core/src/main/java/io/undertow/attribute/SecureExchangeAttribute.java
This PR contains two commits for SecureExchangeAttribute:
- [UNDERTOW-1290 Fix a typo for the token name of SecureExchangeAttribute](https://issues.jboss.org/browse/UNDERTOW-1290)
- [UNDERTOW-1291 Improve SecureExchangeAttribute to use HttpServerExchange#isSecure() instead of HttpServerExchange#getRequestScheme()](https://issues.jboss.org/browse/UNDERTOW-1291)
=> [UNDERTOW-1290][UNDERTOW-1291] for SecureExchangeAttribute

servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
Native JSSE implementations may be more expensive to interact
with than SunJSSE.
=> Reduce invocations of SSLSession.getCipherSuite per request

core/src/main/java/io/undertow/util/URLUtils.java, core/src/test/java/io/undertow/util/URLUtilsTestCase.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
- previous recognition based on literal "://" was incomplete
- especially it should be possible to redirect to native oauth2 clients
using 7.1.  Private-Use URI Scheme Redirection
e.g. com.example.app:/oauth2redirect/example-provider
=> UNDERTOW-1308 Fix incomplete recognition of absolute URL for redirects

pom.xml, spotbugs-exclude.xml
As Findbugs project has been discontinued, we should now use Spotbugs which is a successor.
=> Migrated from deprecated findbugs plugin to spotbugs.

core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Balancer.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPHandler.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPInfoUtil.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterProxyTarget.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterStatus.java
Jira
https://issues.jboss.org/browse/UNDERTOW-1315
This is very easy to overlook because the attribute is extremely poorly named and missing from MCMP definition [1] completely. This is because mod_cluster aligned nomenclature with httpd mod_proxy's [2] which defines maxattempts as:
Maximum number of failover attempts before giving up.
[1] https://developer.jboss.org/docs/DOC-11425
[2] https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass
The first commit fixes the issue.
Second commit cleans up the API with proper deprecation. I don't think we need to keep the mod_proxy nomenclature and use proper one in our APIs.
=>  UNDERTOW-1315 Undertow mod_cluster balancer retries one less time

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
The `SslConduit` logs some exceptions at debug level. Some of these use the wrong exception instance to log the message. The commit here fixes such instances.
=> Use the correct exception instances while logging

core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Previously the tracked size was decremented when a buffer was
received from the ThreadLocal cache rather than the shared
queue, allowing the queue to grow unbonuded.
=> UNDERTOW-1316: Fix DefaultByteBufferPool queue memory leak

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java, core/src/main/java/io/undertow/server/protocol/framed/ShutdownFallbackExecutor.java
Rather than executing remaining tasks on the current non-io thread,
they are invoked from a fallback single threaded executor.
=> UNDERTOW-1321: Prevent AbstractFramedChannel deadlock on shutdown

core/src/main/java/io/undertow/server/ConnectorStatisticsImpl.java
setting complete listener is unreachable when a current value less than max
=> fix active requests metric collecting

core/src/main/java/io/undertow/conduits/DeflatingStreamSinkConduit.java, core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java, core/src/main/java/io/undertow/util/SimpleObjectPool.java, core/src/test/java/io/undertow/server/handlers/encoding/GzipContentEncodingSimpleObjectPoolTestCase.java
Adds "recycling" functionality to SimpleObjectPool, which allows consumers of the pool to provide a lambda to be run on every object which is returned to the pool to be reused. This commit also includes now-possible bugfixes to DeflatingStreamSinkConduit and InflatingStreamSourceConduit, which properly reset Inflaters/Deflaters for reuse.
=> [UNDERTOW-1364] Add "recycle" functionality to SimpleObjectPool

core/src/main/java/io/undertow/server/JvmRouteHandler.java, core/src/main/java/io/undertow/server/SecureCookieCommitListener.java, core/src/main/java/io/undertow/server/handlers/SecureCookieHandler.java
First commit is straightforward, the second attempts a bit more aggressively to avoid creating the mutable cookie map when we only need to read existing cookies.
=> UNDERTOW-1368: SecureCookieHandler improvements

examples/src/main/java/io/undertow/examples/websockets_extension/WebSocketServer.java, examples/src/main/java/io/undertow/examples/websockets_extension/index.html
I had some hard times finding an example on how to enable websocket per-message deflate.
I've added an extra example highliting usage of WebSocketProtocolHandshakeHandler and PerMessageDeflateHandshake in this PR.
=> Added an example on WebSocketProtocolHandshakeHandler usage

servlet/src/test/java/io/undertow/servlet/test/streams/AbstractServletInputStreamTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java
It's much more likely that we will hit this issue when the client
is rate limited.
Added tests for servlet 3.1 async io with a RequestBufferingHandler
which seems to cause the issue reproducibly.
=> UNDERTOW-1382: Tests to reproduce this issue

core/src/main/java/io/undertow/server/protocol/http/ALPNLimitingSSLEngine.java, core/src/main/java/io/undertow/server/protocol/http/ALPNOfferedClientHelloExplorer.java
Unnecessary to throw and catch an exception when we can validate
content length first.
=> UNDERTOW-1395: ALPNLimitingSSLEngine validates buffer size.

core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java, core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1404
https://issues.jboss.org/browse/JBEAP-15134
=> UNDERTOW-1404 Treat invalid query string via AJP as bad request

spotbugs-exclude.xml
Commit df65c01 caused spotbugs failing with CN_IDIOM_NO_SUPER_CALL.
Although introduced change is intentional, this commit adds an exclude rule to spotbugs to ignore this.
=> Add new rule to spotbugs-exclude.xml

core/src/main/java/io/undertow/server/ConnectorStatisticsImpl.java
It's unnecessary to create multiple instances because they
wrap state in the parent ConnectorStatisticsImpl.
=> ConnectorStatisticsImpl reuses ByteActivityCallback instances

core/src/main/java/io/undertow/server/Connectors.java
with UndertowOptions.DECODE_URL = false, it will always try to decode path if contains "%", and will result in NullPointerException (by io.undertow.util.URLUtils.decode)
due to io.undertow.server.protocol.http2.Http2ReceiveListener.encoding will be null 
if UndertowOptions.DECODE_URL = false
=> Fix HTTP/2.0 receiver doesn't respect UndertowOptions.DECODE_URL

parser-generator/src/main/java/io/undertow/annotationprocessor/AbstractParserGenerator.java
The parser generator uses non deterministic data structures (HashMap, HashSet) that make the output non reproducible (see https://reproducible-builds.org for why it matters). I suggest using LinkedHashMap and LinkedHashSet instead since the iterator order is guaranteed to be the insertion order.
=> Reproducible output for the parser generator

core/src/main/java/io/undertow/Undertow.java, core/src/main/java/io/undertow/UndertowOptions.java
Cherry picked fix as this bug affects all spring relases from 1.5.12 and 2.0.2 onwards.
=> UNDERTOW-1387: Implement configurable executor shutdown timeout

core/src/main/java/io/undertow/util/PathTemplateMatcher.java, core/src/test/java/io/undertow/server/handlers/PathTemplateHandlerTestCase.java, core/src/test/java/io/undertow/server/handlers/RoutingHandlerTestCase.java
Previusly RoutingHandler and PathTemplateHandler would not match
root paths after a portion of the path had been resolved (by a
PathHandler, for example), which results in relative path `` (empty string)
rather than `/`.
=> UNDERTOW-1460: PathTemplateMatcher matches empty string to "/"

websockets-jsr/src/main/java/io/undertow/websockets/jsr/ServerWebSocketContainer.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedAddedProgrammaticallyEndpoint.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java
The Javadoc for `ServerEndpointConfig` states that both Annotated + programmatic endpoints should be supported, though it doesn't seem to work with Undertow's implementation. The fix was fairly straightforward - if the endpoint does not extend from `Endpoint` then add the `AnnotatedEndpointFactory` to the final configuration, similar to when provided as the class-specifying method.
=> Add a test + fix for adding an annotated Websocket endpoint programmatically

core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
All accessors already synchronize on the list instance.
The additional `Collections.synchronizedList(` wrapper might be a bit safer against potential future bugs, please feel free to close out this PR if you prefer to keep that safety over avoiding the additional re-synchronization.
=> Remove unnecessary synchronized list in DefaultByteBufferPool

core/src/main/java/io/undertow/server/handlers/form/FormData.java
The commit here fixes a file descriptor leak in FormData while writing out the data to target file as noted in https://issues.jboss.org/browse/UNDERTOW-1474.
This either is the sole reason why the users are running into such leaks as noted in the linked forum thread https://developer.jboss.org/thread/278816 or at least one of the reasons.
=> UNDERTOW-1474 Fix file descriptor leaks while writing FormData

servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java, servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
https://issues.jboss.org/browse/UNDERTOW-1482
This is an enhancement to log a warning message before throwing FileNotFoundException for missing static file in JSP include action tag.
e.g. <jsp:include page="missingstaticpage.html"/>
=> UNDERTOW-1482 log a warning for jsp missing included file.

core/src/main/java/io/undertow/server/handlers/URLDecodingHandler.java
If DECODE_URL is set to the default value, the URLDecodingHandler
will not cause problems, it jut won't do additional decoding.
=> Update URLDecodingHandler javadoc

core/src/main/java/io/undertow/attribute/ExchangeAttributes.java, core/src/main/java/io/undertow/attribute/RemoteObfuscatedIPAttribute.java, core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java, core/src/main/java/io/undertow/util/NetworkUtils.java, core/src/main/resources/META-INF/services/io.undertow.attribute.ExchangeAttributeBuilder, core/src/test/java/io/undertow/util/NetworkUtilsAddressObfuscationTestCase.java
add %o: obfuscated remote IP address, removing the
last IPv4 byte or anything after the second colon (IPv6),
ie. "1.2.3." or "fe08:2:"
Also added the log patterns commonobf and combinedobf where instead of the remote host the obfuscated remote IP gets logged.
Purpose: better support for data privacy laws in the EU.
Tested against WildFly 15.0.1.
=> add %o: obfuscated remote IP address

core/src/main/java/io/undertow/server/HttpServerExchange.java
This reverts commit 51144633f22ba0e73ee1f435db72025720395797.
=> [UNDERTOW-1515] HttpServerExchange.toString does not include headers

core/src/main/java/io/undertow/server/ExchangeCompletionListener.java
Document that NextListener.proceed is not optional.
=> Improve ExchangeCompletionListener javadoc

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java, core/src/test/java/io/undertow/server/ssl/TLS13HalfCloseHangTestCase.java, core/src/test/java/io/undertow/testutils/DefaultServer.java
Fix infinite looping in `SslConduit` with Java 11 and TLS 1.3 half-close semantics.
=> UNDERTOW-1493: Fix TLS 1.3 half-close hang

core/src/main/java/io/undertow/server/HttpServerExchange.java
Previously it was unclear what the returned value represented.
=> Improve HttpServerExchange.getRequestStartTime javadoc

core/src/main/java/io/undertow/server/handlers/form/FormParserFactory.java
A non-breaking change that makes the FormParserFactory.Builder methods chainable.
=> Make FormParserFactory builder more fluent

core/src/main/java/io/undertow/server/DirectByteBufferDeallocator.java
On Java 11.0.2 there was an exception during Unsafe retrieval.
With this patch, there is still exception printed: UndertowLogger.ROOT_LOGGER.directBufferDeallocatorInitializationFailed(t);
but supported flag is set to false and everything works as intended.
`java.lang.ExceptionInInitializerError: null
at undertow.core@2.0.19.Final/io.undertow.server.DefaultByteBufferPool.queueIfUnderMax(DefaultByteBufferPool.java:209)
at undertow.core@2.0.19.Final/io.undertow.server.DefaultByteBufferPool.freeInternal(DefaultByteBufferPool.java:201)
at undertow.core@2.0.19.Final/io.undertow.server.DefaultByteBufferPool.access$200(DefaultByteBufferPool.java:40)
at undertow.core@2.0.19.Final/io.undertow.server.DefaultByteBufferPool$DefaultPooledBuffer.close(DefaultByteBufferPool.java:271)
at …
=> Included getUnsafe in try/catch to make it work with Java 11+

core/src/main/java/io/undertow/protocol/http/HttpServerConnection.java
Likely existed for debugging at some point, was checked in with
async read fixes in c6a146ac3bdcf0d4a949028c1b088a532aadbaa3
=> [3.x] Remove staic list of all HttpServerConnection instances

core/src/main/java/io/undertow/util/StatusCodes.java, core/src/test/java/io/undertow/util/NodeStatusCodesTestCase.java
The commit here fixes an issue reported in https://issues.jboss.org/browse/UNDERTOW-1529.
This also includes a testcase to reproduce the issue and verify the fix.
=> UNDERTOW-1529 - Don't let StatusCodes#getReason() throw an ArrayIndexOutOfBoundsException

core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java, core/src/main/java/io/undertow/websockets/client/WebSocketClient.java
This is basically the same code as is used in `UndertowXnioSsl.StreamConnectionChannelListener#handleEvent` to enforce SNI on the connection.
=> UNDERTOW-1533 Send SNI when connecting via HTTP Proxy

core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java, core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
When Proxy Protocol (both version v1 and v2) is enabled, client authentication doesn't work. During the TLS Handshake, the server hello doesn't include the Certificate Request, so the client never sends its certificates. With the same configuration but disabled proxy protocol, the server hello is correct (and the client sends its certs). I verified this running a local HAProxy with enabled proxy protocol. This fix sets the SSLEngine configuration to properly request the client certificates.
=> UNDERTOW-1536: fixed client auth when using proxy protocol

servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java, servlet/src/test/java/io/undertow/servlet/test/charset/DefaultCharacterEncodingTestCase.java
The commit here fixes the issue reported in https://issues.jboss.org/browse/UNDERTOW-1540 by correctly setting the passed character encoding in `ServletContext#setRequestCharacterEncoding`.
This also includes a test case which reproduces the issue and verifies the fix.
=> Fix for UNDERTOW-1540 

core/src/main/java/io/undertow/util/HttpString.java
This field was previously used in an alternative murmur-3 hash
implementation, but was not deleted with the code it supported
in 15d3d02efc3c54216d189b7df23d77fc86112cd4.
=> Remove unused HttpString.hashCodeBase

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
The patch is pretty self-explanatory. I'm a bit bugged by the fact that the `SSLEngine` itself is created by different means in two places but that's how it is and I don't think changing this right now would provide any more benefits.
=> UNDERTOW-1539 Allow checking server DNS name vs. its certificate

pom.xml
The commit here fixes the issue reported in https://issues.jboss.org/browse/UNDERTOW-1550 letting the `jboss-parent` pom dictate the version of `maven-bundle-plugin`. The `jboss-parent` pom version `35` correctly uses a version of `maven-bundle-plugin` which understands Java 9+ multi-release jars and allows builds to pass on JDK11.
P.S: With this change, the build works fine with both JDK 8 and 11.
=> UNDERTOW-1550 Make undertow build fine on JDK11

core/src/main/java/io/undertow/util/Cookies.java, core/src/main/java/io/undertow/util/LegacyCookieSupport.java, core/src/test/java/io/undertow/util/CookiesTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1548
=> [UNDERTOW-1548] Make a request cookie parser behavior tunable with ALLOW_HTTP_SEPARATORS_IN_V0 setting

core/src/test/java/io/undertow/testutils/HttpClientUtils.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java, servlet/src/test/java/io/undertow/servlet/test/charset/DefaultCharacterEncodingServlet.java, servlet/src/test/java/io/undertow/servlet/test/charset/DefaultCharacterEncodingTestCase.java
The commit here fixes the issue noted in this forum thread https://developer.jboss.org/message/989396#989396 (and tracked in JIRA https://issues.jboss.org/browse/UNDERTOW-1553). 
This commit makes sure the reader's charset encoding takes into account the encoding set on servletcontext level and then falls back to the default container level encoding. The commit does a similar thing with the response's writer.
The changes in this commit follow the rules noted in the javadoc of `javax.servlet.ServletRequest#getCharacterEncoding` and `javax.servlet.ServletResponse#getCharacterEncoding`
The existing testcase has been updated to reproduce and verify this fix.
=> UNDERTOW-1553 Use the correct character encoding for the reader/writer

core/src/main/java/io/undertow/security/handlers/SinglePortConfidentialityHandler.java, core/src/test/java/io/undertow/server/security/SimpleConfidentialRedirectTestCase.java
The commit here fixes the issue reported in https://issues.jboss.org/browse/UNDERTOW-1565
The code in `SinglePortConfidentialityHandler` which deals with forming the redirect URI was using the 7 argument constructor of `java.net.URI`, which as per its javadoc, internally encodes the passed parameters, like the `queryString`. We do not want that to happen, since the query string and other components of the URI that we are building aren't expected to be decoded/encoded, by the container, while we are building the redirect URI.
The commit here uses a `StringBuilder` to form the redirect URI and then passes it to the single argument constructor of `java.net.URI` which doesn't do the encoding of the passed parameter, unlike the 7 argument constructor.
The commit also includes an update to an …
=> UNDERTOW-1565 Don't encode query strings and URI paths while redirecting

core/src/test/java/io/undertow/server/protocol/proxy/ProxyProtocolTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1572
Test case fix for ProxyProtocolTestCase with IPv6.
Reproducer:
```mvn test -Dtest=ProxyProtocolTestCase -Dtest.ipv6```
=> UNDERTOW-1572 ProxyProtocolTestCase fails when IPv6 enabled

core/src/main/java/io/undertow/util/URLUtils.java, core/src/test/java/io/undertow/util/URLUtilsTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1567
https://issues.jboss.org/browse/JBEAP-16826
Use regex to determine URI scheme instead of `new URI(location).getScheme()`.
The presence of scheme in given `location` is used to determine whether `location` is an absolute or relative URI. The URI instantiation fails when `location` contains technically illegal characters like {}, the `location` is then always determined as relative. This was not the case in previous EAP versions.
=> UNDERTOW-1567 Redirect to absolute URL with special characters broken

core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
This fixes UNDERTOW-1564 by using the host name of the indicated destination URI rather than the address of the proxy connection.
=> Use proper peer address for proxied connections

core/src/main/java/io/undertow/server/HttpServerExchange.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1091
=> [UNDERTOW-1091] Invalid response code for empty host value in request

servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java, servlet/src/main/java/io/undertow/servlet/handlers/RedirectDirHandler.java, servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java, servlet/src/test/java/io/undertow/servlet/test/defaultservlet/SecurityRedirectTestCase.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1578
Created a `RedirectDirHandler` to handle the redirect after security check.
=> [UNDERTOW-1578] 401 Unauthorized should be returned when requesting a protected directory without trailing slash

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
When the handshake fails, the close listener is notified, connection closes and throws a ClosedChannelException hiding the underlaying cause, proposed fix just logs the error on the client side before the exception is thrown.
Issue: https://issues.jboss.org/browse/UNDERTOW-1580
=> [UNDERTOW-1580] Improve EJB over HTTPS logging

servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java, servlet/src/main/java/io/undertow/servlet/api/SecurityActions.java, servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java
The commit here fixes a NPE that's reported in https://issues.jboss.org/browse/UNDERTOW-1582. The change here uses the system level temporary directory as the base directory, if no explicit temporary directory is setup.
=> UNDERTOW-1582 Fix NPE while setting up temporary directory

core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/handlers/form/FormEncodedDataDefinition.java, core/src/main/java/io/undertow/util/UrlDecodeException.java, core/src/test/java/io/undertow/server/handlers/form/FormDataParserTestCase.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1554
Improve handling and leniency of bad POST parameters - Ignore incorrect parameters or values (ones that contain % without any hexadecimal number) in data query.
Example query with result:
$ curl -d "test1=%&test2=foo" http://127.0.0.1:8080/helloworld/HelloWorld 
test2=foo 
Example log:
13:38:04,820 ERROR [io.undertow.request] (default task-1) UT000193: Character decoding failed. Parameter [test1] with value [%] has been ignored. Note: further occurrences of Parameter errors will be logged at DEBUG level.
=> [UNDERTOW-1554] Improve handling and leniency of bad POST parameters

servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java, servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/test/java/io/undertow/servlet/test/proprietry/ExchangeCompletionTestCase.java, servlet/src/test/java/io/undertow/servlet/test/proprietry/IgnoresRequestAndSetsAttributeAsyncServlet.java, servlet/src/test/java/io/undertow/servlet/test/proprietry/IgnoresRequestAndSetsAttributeServlet.java
This reverts commit ebc30db09bb9c69f293e7059d15f6a59d3771868.
Issue: https://issues.jboss.org/browse/UNDERTOW-1573
=> [UNDERTOW-1573] Servlet request attributes are cleared before access log exchange completion listener runs

core/src/main/java/io/undertow/server/RoutingHandler.java, core/src/test/java/io/undertow/server/handlers/RoutingHandlerTestCase.java
Updates the allMethodsMatcher to lookup templates using the
match method instead of get in order to normalize the input.
Previously registration would throw an exception when routes
were added for the same path template with different parameter names
despite being equivalent.
=> UNDERTOW-1581: Fix RoutingHandler allMethodsMatcher validation

core/src/main/java/io/undertow/conduits/StoredResponseStreamSinkConduit.java
Obvious mistake. buf.position() actually indicates buffer size, so last buffer index is equal to **buf.position() -1**.
With this error, when buffer array has more than one element (so when response is bigger than 16KB by default), exception is thrown and exchange will never be finalized properly (even though HTTP response is received by client and seems fine). Listeners won't be executed, graceful shutdown will fail etc.
Below there is a simple code snippet for reproducing this error:
public static void main(String[] args) {
HttpHandler targetHandler = exchange -> {
exchange.getResponseHeaders().add(Headers.CONTENT_TYPE, "text/plain");
exchange.getResponseSender().send("A".repeat(20000));
};
StoredResponseHandler storedResponseHandler = new StoredResponseHandler(targetHandler);
Undertow …
=> Fix index out of bounds exception in StoredResponseStreamSinkConduit

core/src/test/java/io/undertow/util/ByteRangeTestCase.java
I've analysed your codebase and noticed that `io.undertow.util.ByteRange` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.
=> Add unit tests for io.undertow.util.ByteRange

servlet/src/main/java/io/undertow/servlet/compat/rewrite/RewriteHandler.java, servlet/src/test/java/io/undertow/servlet/test/compat/rewrite/RewriteTestCase.java
- Using `RewriteHandler` does not cause requests to be routed to destination servlet, requests are routed to original servlets instead
With the rule defined as `RewriteRule /foo1 /bar1` request were still send to `/foo1` servlet
- Enhancing test case to replicate rewrite scenario by removing original servlet that could handle inappropriately rewritten request
Setting `requestURI` on `HttpServerExchange` solves the problem
=> Fixing rewrite handler so that it properly routes to destination servlet

benchmarks/pom.xml
Hello, I noticed that dependencies `undertow-servlet`, `undertow-websockets-jsr`, `jboss-logging-processor`, `xnio-nio`, `jmh-generator-annprocess`, and `httpmime` are declared in the `pom` of the `undertow-benchmarks` module. However, these dependencies are not used in any of the four classes of the module. Removing these unused dependencies in the `pom` has an impact on the size of the packaged jar file for the benchmarks (reduction is more than 1MB), and also decreases the complexity of the Maven dependency tree of the module.
=> [UNDERTOW-1615] Remove unused dependencies

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/protocols/ssl/UndertowAcceptingSslChannel.java, core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Now that Undertow requires java 8, it's no longer necessary to use
reflection to access this method.
=> UNDERTOW-1616: Invoke setUseCipherSuitesOrder without reflection

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Jiras: https://issues.jboss.org/browse/UNDERTOW-1618
https://issues.jboss.org/browse/UNDERTOW-1619
https://issues.jboss.org/browse/UNDERTOW-1620
https://issues.jboss.org/browse/UNDERTOW-1621
=> [UNDERTOW-1618][UNDERTOW-1619][UNDERTOW-1620] Fix issues with abstract framed channels

servlet/src/main/java/io/undertow/servlet/compat/rewrite/RewriteHandler.java
change save the env attributes to REQUEST_ATTRIBUTES
i use rewritehandler to rewrite my front path to index.html, it work prefect when i have login in the system, but when i direct request my front resource without login, it rewrite to index.html, my authentication filter intecept the request and redirect to login page and pass current location as a 
returnUrl parameter, when i login in from login page, it redirect to index.html, that was not correct,
when i digged into undertow rewrite, i found the rewrite env, my test code is here
RewriteCond %{REQUEST_METHOD} GET [NC]
RewriteRule ^/index.html/ent$ /ent [NE,R,E=original-path:%{REQUEST_PATH}]
when i config it, RewriteHandler set the attribute correct in the request attributes, but i can't get that attributes from my filter code, so i …
=> [UNDERTOW-1630] RewriteHandler rewite url env lost

examples/src/main/java/io/undertow/examples/Runner.java
If I run examples(class Runner) on Windows (in `Intellij IDEA`), annotated classes not selected because file separator "\" not "/"
=> [UNDERTOW-1634] replace "/" to File.separator

pom.xml
Jira:https://issues.redhat.com/browse/UNDERTOW-1635
=> [UNDERTOW-1635] Mark the javadoc plugin source code compatible with 1.8

core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http/ParseState.java, core/src/main/java/io/undertow/server/session/PathParameterSessionConfig.java, core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Hi @stuartwdouglas, @fl4via,
Please review and provide feedback on my first stab at resolving the [UNDERTOW-1464](https://issues.redhat.com/browse/UNDERTOW-1464)! Some notes on the code
* The PR puts all matrix parameters in the path parameter collection and makes no difference between the two `p1` matrix parameters in the following example
```
/some;p1=v1/path;p1=v2
```
An alternative implementation could take into account the fact that these are really two separate parameters, perhaps by using the canonical path as a namespace which would give the following two variable names:
```
/some;p1
/some/path;p1
```
* The current PR does not include support for comma separated values, I will add that shortly if you think this PR is going anywhere.
```
/some;p1=v1,v2
```
* The …
=> UNDERTOW-1464 Proper handling of matrix parameters

core/src/main/java/io/undertow/protocols/ajp/AjpClientChannel.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java, core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
https://issues.redhat.com/browse/UNDERTOW-1623
In order to avoid deadlocks we cannot call alien or potentially dangerous methods
while lock is being held. We have to hold as few locks as possible.
This PR supersedes:
* https://github.com/undertow-io/undertow/pull/851
* https://github.com/undertow-io/undertow/pull/847
=> [UNDERTOW-1623] Undertow Deadlock

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Close uses double-check locking with the encapsulated lock object
instead of relying on the object level lock which risks deadlocks.
=> UNDERTOW-1643: Prevent deadlock in AbstractFramedStreamSinkChannel

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Previously when a framed channel was closed from an I/O thread while
a worked waited for blocking operations, the blocking thread could
become stuck forever.
=> UNDERTOW-1639: AbstractFramedStreamSourceChannel notifies on close

core/src/test/java/io/undertow/testutils/DefaultServer.java
Attempt to isolate tests a bit better, we don't want threads from completed tests to create noise in subsequent tests.
Possible downside: Some tests may submit work that doesn't terminate gracefully, it's possible this will cause tests to take longer to complete.
=> [UNDERTOW-1670] DefaultServer test utility waits for the worker to shut down

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
Previously STATE_CLOSED was set prior to invoking close, causing
close to return without cleaning up resources.
=> UNDERTOW-1645: AbstractFramedStreamSourceChannel.lastFrame invokes close

core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
Undertow send Content-Length header in 204 responses for HTTP/2, thus violating RFC 7230.
Note that for HTTP/1.X Undertow handles this correctly
=> [UNDERTOW-1492] Respect rfc7230 section-3.3.2

benchmarks/pom.xml
When build benchmarks module without `jmh-generator-annprocess` dependency I got
```
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:263)
at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
at org.openjdk.jmh.Main.main(Main.java:71)
```
This is fix request.
=> [UNDERTOW-1672] Unable to find the resource: /META-INF/BenchmarkList

core/src/main/java/io/undertow/server/HttpServerExchange.java
This does not solve the linked ticket, but prevents the described
scenario from causing additional problems.
While the modified blocks are commented suggesting that they
should never be called, UNDERTOW-1664 describes when they occur
with a reproducer.
=> UNDERTOW-1700: Prevent resource leaks when exchanges aren't closed cleanly

core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java, core/src/main/java/io/undertow/server/handlers/resource/SecurityActions.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1703
This is the PR to `2.0.x` branch, cherry-picked from https://github.com/undertow-io/undertow/pull/882
=> [UNDERTOW-1703] Checking isSymbolicLink should be in doPrivileged block

pom.xml
Update the Netty version to [4.1.50.Final](https://repo1.maven.org/maven2/io/netty/netty-all/4.1.50.Final/)
Jira: https://issues.redhat.com/browse/UNDERTOW-1710
=> [UNDERTOW-1710] Update the Netty version to 4.1.50.Final

core/src/main/java/io/undertow/Handlers.java, core/src/main/java/io/undertow/server/handlers/SetErrorHandler.java, core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder, servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java, servlet/src/main/java/io/undertow/servlet/handlers/SendErrorPageHandler.java
Using the predicate language in Undertow, there is no way to return the error pages configured in the servlet from the handler chain that runs first in the XNIO worker thread.  For example, if the response-code() handler is used, the exchange is simply ended and no response body is sent which is not a very useful behavior.
A solution provided by Stuart on the mailing list was to set the response code but not end the exchange.  Then configure the servlet handler to check for a status code above 399 and call the servlet sendError() routine.
=> UNDERTOW-1747 - Provide a mechanism for a predicate in return a servlet error page

servlet/src/main/java/io/undertow/servlet/core/ErrorPages.java
https://issues.redhat.com/browse/UNDERTOW-1762
2.0.x PR: #944
=> [UNDERTOW-1762] Error page for custom exception-type is not is not displayed in jsp development mode

core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java, core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1755
2.0.x PR: https://github.com/undertow-io/undertow/pull/914
=> [UNDERTOW-1755] - remove doubled definitions of some variables

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java, core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java, core/src/test/java/io/undertow/server/handlers/BlockingReadTimeoutHandlerTestCase.java, core/src/test/java/io/undertow/server/handlers/BlockingWriteTimeoutHandlerTestCase.java
Implemented a new BlockingTimeoutHandler which can be configured
with I/O timeouts for blocking read and write operations.
This approach limits the time that may be spent in awaitReadable
or awaitWritable to apply to only blocking operations without requiring
invasive code change.
=> UNDERTOW-1622: Implement blocking IO timeouts

servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
https://issues.redhat.com/browse/UNDERTOW-1732
I did consider if some of these methods should silently complete if no SecurityContext is available but up until this point these methods would have resulted in a NullPointerException so I think we are safe to convert to a ServletException for now.
=> [UNDERTOW-1732] Verify if we have a SecurityContext before making use of it.

core/src/main/java/io/undertow/util/HttpString.java
https://issues.redhat.com/browse/UNDERTOW-1770
Automatically updated
https://j2eeguys.com/updater
Signed-off-by: Steve Davidson <steve@j2eeguys.com>
=> UNDERTOW-1770 HttpString uses obsolete String Constructor

servlet/src/main/java/io/undertow/servlet/core/ApplicationListeners.java
issue: https://issues.redhat.com/browse/UNDERTOW-1773
UNDERTOW-1773 to avoid potential leak, make sure the iteration continue in case of exception.
=> UNDERTOW-1773 to avoid potential leak, make sure the iteration continue in case of exception.

servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
I successfully verified via sequence diagrams analysis that proposal fix in UNDERTOW-1742 really fixes the issue @fl4via .
Thanks @msfm for your feedback too.
Fixes:
https://issues.redhat.com/browse/UNDERTOW-1742
https://issues.redhat.com/browse/UNDERTOW-1743
https://issues.redhat.com/browse/UNDERTOW-1777
=> [UNDERTOW-1742] Don't clear attributes in closeAndDrainRequest() method

core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1807
Master PR: #989
2.1.x PR: #993
=> UNDERTOW-1807: Fix ForwardedHandlerTestCase on jdk14+

servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java, servlet/src/test/java/io/undertow/servlet/test/crosscontext/CrossContextClassLoaderTestCase.java, servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java, servlet/src/test/java/io/undertow/servlet/test/multipart/forward/MultiPartForwardTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1792
Upstream for: https://issues.redhat.com/browse/JBEAP-20289
2.0.x PR: #973 
2.1.x PR: #972
=> UNDERTOW-1792 ServletPrintWriter.println uses LF instead of CRLF

servlet/src/test/java/io/undertow/servlet/test/security/form/SaveOriginalPostRequestTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1820
I am trying to fix a flaky test detected by Nondex framework https://github.com/TestingResearchIllinois/NonDex
sometime the response String equals "param1=param1Value/param2=param2Value", and sometimes the response String equals "param2=param2Value/param1=param1Value" if we run the Nondex framework because order of the tests are changed, and the root cause might be 
https://github.com/undertow-io/undertow/blob/ff4c9cf37872cb96070ba6a2fcbbaa6df291e390/servlet/src/test/java/io/undertow/servlet/test/security/form/SaveOriginalPostRequestTestCase.java#L182
when the httpclient is trying to execute the request that is out of our control. 
I think the order of the parameter does not matter, we just need a response. So I changed line 125 to two …
=> [UNDERTOW-1820] Fix flaky test in SaveOriginalPostRequestTestCase

core/src/main/java/io/undertow/server/handlers/form/FormEncodedDataDefinition.java, core/src/main/java/io/undertow/util/URLUtils.java, core/src/test/java/io/undertow/server/handlers/form/FormDataParserTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1802
The FormEncodedDataParser has been modified to also perform a decode if a non-ascii (n < 0) character is found. The URLUtils.decode method was already prepared to handle those bytes.
The test now uses the payload instead of the headers to return the data (because now strange chars can be returned). Finally a method that sends direct UTF-8 characters is added to include a test for this specific use-case.
PR for master branch.
2.1.x PR: #979 
2.0.x PR: #978
=> [UNDERTOW-1802] Improve FormEncodedDataDefinition to handle chars in configured encoding

core/src/main/java/io/undertow/attribute/SslClientCertAttribute.java, core/src/main/java/io/undertow/server/SSLSessionInfo.java, core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java, core/src/main/java/io/undertow/util/Certificates.java, servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1791
Java 15 runtimes default jsse SSLSession implementation throws an
UnsupportedOperationException when getPeerCertificateChain is called.
https://www.oracle.com/java/technologies/javase/15-relnote-issues.html#JDK-8241039
In this PR I have replaced uses of getPeerCertificateChain with getPeerCertificates, however I have not provided an implementation of sslsessioninfo.getPeerCertificateChain which delegates to getPeerCertificates and converts to the javax variant. It's unclear if that would be desirable.
It appears unlikely that there are cases in which getPeerCertificates produces different results, but it's possible a SSLSession implementation is incorrect in a way that causes this change to introduce failures. We could flag this …
=> UNDERTOW-1791: Migrate from getPeerCertificateChain to getPeerCertificates

core/src/main/java/io/undertow/util/PathTemplateMatcher.java, core/src/test/java/io/undertow/util/PathTemplateMatcherTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1821
Replace `HashMap` to `LinkedHashMap` in `PathTemplateMatcher`. Motivation: ordered matched paths look more natural e.g. in debugging:
Also in my case I needed to write a simple custom matcher: not Map (expected) equals Map (actual), but a List of matched values (cannot use `Set`, because values can be repeated).
Reference implementation: spring-core `org.springframework.util.AntPathMatcher` keeps original order:
```java
AntPathMatcher antPathMatcher = new AntPathMatcher();
Map<String, String> pathVariables = antPathMatcher.extractUriTemplateVariables(
"/{context}/{version}/{controller}/{id}",
"/api/v3/users/1"
);
// prints "{context=api, version=v3, controller=users, id=1}"
```
Cons: in theory, updated impl will take more nanoseconds in …
=> [UNDERTOW-1821] Path template matched parameters should keep order

core/src/main/java/io/undertow/server/handlers/HttpContinueReadHandler.java, core/src/test/java/io/undertow/server/handlers/HttpContinueConduitWrappingHandlerBufferLeakTestCase.java, servlet/src/test/java/io/undertow/servlet/test/handlers/AbstractHttpContinueServletTestCase.java, servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueSslServletTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1816
=> [UNDERTOW-1816] HTTPS connection abruptly closed by HttpServerConnection

core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
https://issues.redhat.com/browse/UNDERTOW-1833
This is a trivial change of removal unused and unnecessary code in
the Http2EndExchangeTestCase.java test case.
Apart from that, I slightly changed the way how test fails in case that
HTTP2 connection is not correctly established - I unified this failure
with other failures in the test.
There is no other problem in the test as it is passing just fine.
I just got around this when I was investigating something else.
=> [UNDERTOW-1833] Unneccessary code removed from the test.

core/pom.xml, karaf/pom.xml, karaf/src/main/resources/features.xml, pom.xml, servlet/pom.xml, websockets-jsr/pom.xml
Jira: https://issues.redhat.com/browse/UNDERTOW-1852
There's also "karaf" Maven module, enabled only with `osgi` Maven
profile. This is not to provide any additional artifact, but only to
verify the Manifest headers.
I also removed io.undertow.servlet.core.ServletExtensionHolder which was
supposed to provide a static way to add ServletExtensions in OSGi
environment. It's no longer needed and even in OSGi ServletExtensions
are now added normally to DeploymentInfo.
=> [UNDERTOW-1852] Add OSGi manifest headers to 3 Undertow modules

core/src/main/java/io/undertow/Undertow.java, core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/protocols/ssl/SslConduit.java, core/src/main/java/io/undertow/protocols/ssl/UndertowAcceptingSslChannel.java, core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java, core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java, core/src/test/java/io/undertow/server/ssl/DelegatedTaskExecutorTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1846
This provides a relatively simple mechanism to control concurrency
of the delegated task portion of a handshake. The work done by
these tasks doesn't necessarily match the type of work that the
worker pool is configured for and may be controlled separately.
The connection is immediately closed when a delegated task executor
rejects a task.
=> UNDERTOW-1846 Configurable SSLEngine delegated task executor

core/src/main/java/io/undertow/conduits/StoredResponseStreamSinkConduit.java
Undertow JIRA: https://issues.redhat.com/browse/UNDERTOW-1849
JBEAP JIRA (7.3.z): https://issues.redhat.com/browse/JBEAP-21072
JBEAP JIRA (7.4.z): https://issues.redhat.com/browse/JBEAP-21269
This PR for 2.0.x branch.
PR for the master branch: https://github.com/undertow-io/undertow/pull/1057
=> UNDERTOW-1849 NPE happens at StoredResponseStreamSinkConduit.terminateWrites() when StoredResponseHandler (store-response) is enabled

core/src/main/java/io/undertow/conduits/StoredResponseStreamSinkConduit.java
Undertow JIRA: https://issues.redhat.com/browse/UNDERTOW-1849
JBEAP JIRA (7.3.z): https://issues.redhat.com/browse/JBEAP-21072
JBEAP JIRA (7.4.z): https://issues.redhat.com/browse/JBEAP-21269
This PR is for 2.1.x branch.
PR for the master branch: #1057
PR for the 2.0.x branch: #1056
=> [UNDERTOW-1849] NPE happens at StoredResponseStreamSinkConduit.terminateWrites() when StoredResponseHandler (store-response) is enabled

servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1591
=> [UNDERTOW-1591] Fix AsyncContext.dispatch() to pass decoded path

core/src/main/java/io/undertow/server/protocol/http/ALPNLimitingSSLEngine.java, core/src/main/java/io/undertow/server/protocol/http/AlpnOpenListener.java
https://issues.redhat.com/browse/UNDERTOW-1834
There is a difference in IBM JDK TLS ciphersuite names versus their
Oracle JDK counterparts, see e.g. [1].
This discrepancy causes issue in usage of HTTP2 with IBM JDK since
we check enabled ciphersuite based on the name in Oracle JDK variant
only. So if there is an incomming connection from client that offers
IBM names of the ciphersuite, we simply fail to use ALPN and HTTP2
with it consequently.
This change should fix such issue.
[1] https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.0.0/com.ibm.mq.dev.doc/q113210_.htm
=> [UNDERTOW-1834] Fix for IBM JDK and HTTP2/ALPN.

core/src/main/java/io/undertow/util/CanonicalPathUtils.java, core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java, servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1886
The `CanonicalPathUtils.canonicalize` now receives an optional boolean to return null when out of context. It's only used in the request dispatcher related methods. A system property `-Dio.undertow.REQUEST_DISPATCHER_NULL_DISALLOWED=true` restores the old behavior just in case. Tests addded.
PR for master.
PR for 2.1.x: https://github.com/undertow-io/undertow/pull/1118
PR for 2.0.x: https://github.com/undertow-io/undertow/pull/1119
=> [UNDERTOW-1886] [master] Request dispatcher is returned when the path points to outside the servlet context

core/src/main/java/io/undertow/util/CanonicalPathUtils.java, core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java, servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1886
The `CanonicalPathUtils.canonicalize` now receives an optional boolean to return null when out of context. It's only used in the request dispatcher related methods. A system property `-Dio.undertow.REQUEST_DISPATCHER_NULL_DISALLOWED=true` restores the old behavior just in case. Tests addded.
PR for 2.1.x.
PR for master: https://github.com/undertow-io/undertow/pull/1117
PR for 2.0.x: https://github.com/undertow-io/undertow/pull/1119
=> [UNDERTOW-1886] [2.1.x] Request dispatcher is returned when the path points to outside the servlet context

core/src/main/java/io/undertow/util/CanonicalPathUtils.java, core/src/test/java/io/undertow/util/CanonicalPathUtilsTestCase.java, servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1886
The `CanonicalPathUtils.canonicalize` now receives an optional boolean to return null when out of context. It's only used in the request dispatcher related methods. A system property `-Dio.undertow.REQUEST_DISPATCHER_NULL_DISALLOWED=true` restores the old behavior just in case. Tests addded.
PR for 2.0.x.
PR for master: https://github.com/undertow-io/undertow/pull/1117
PR for 2.1.x: https://github.com/undertow-io/undertow/pull/1118
=> [UNDERTOW-1886] [2.0.x] Request dispatcher is returned when the path points to outside the servlet context

pom.xml
Per details at [UNDERTOW-1903](https://issues.redhat.com/browse/UNDERTOW-1903) the current version `3.8.0.Final` is subject to CVE-2020-14340 and could do with being addressed, requiring XNIO >= `3.8.2.Final`.
Tests seem to run fine on this version - not sure what else needs to be done to further validate this or meet contributor guidelines. (Note duplicate/redundant ticket at [UNDERTOW-1861](https://issues.redhat.com/browse/UNDERTOW-1861))
=> [UNDERTOW-1903] Upgrade XNIO to 3.8.4.Final

servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1895
Just the backport of UNDERTOW-1895 to the 2.0.x branch.
PR in master: https://github.com/undertow-io/undertow/pull/1193
=> [UNDERTOW-1895] Fix test DefaultServletCachingListenerTestCase.testWelcomePages in JDK11 Ubuntu

core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1932
Decided to throw exceptions and not silently log as debug - since one of methods already failed like that. Maybe its wrong, but I cant see it.
=> [UNDERTOW-1932] - unify SSLContext manipulation flow

core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1789
=> [UNDERTOW-1789] - bumpTImeout on setMaxInactiveInterval

core/src/main/java/io/undertow/protocols/http2/Http2PushBackParser.java, core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1917
=> [UNDERTOW-1917] Logic in try/finally blocks hides exceptions

core/src/main/java/io/undertow/server/handlers/resource/PreCompressedResourceSupplier.java, core/src/test/java/io/undertow/server/handlers/file/PreCompressedResourceTestCase.java, core/src/test/java/io/undertow/server/handlers/file/data1.json, core/src/test/java/io/undertow/server/handlers/file/data2.json
This PR fixes a `NullPointerException` that can occur when using a `PreCompressedResourceSupplier` and trying to access a file where only the compressed version exists.
**For example:**
Currently, if there is a file `data.json.gz` without the uncompressed version `data.json`, then a GET request to that file `data.json` results in a NullPointerException and a `500`-response:
```
java.lang.NullPointerException: Cannot invoke "io.undertow.server.handlers.resource.Resource.getContentType(io.undertow.util.MimeMappings)" because "this.val$originalResource" is null
at io.undertow.server.handlers.resource.PreCompressedResourceSupplier$1.getContentType(PreCompressedResourceSupplier.java:121)
at io.undertow.server.handlers.resource.ResourceHandler$1.handleRequest(ResourceHandler.java:299)
at …
```
=> [UNDERTOW-1950] Fix NullPointerException in PreCompressedResourceSupplier

core/src/main/java/io/undertow/server/handlers/resource/PreCompressedResourceSupplier.java, core/src/test/java/io/undertow/server/handlers/file/PreCompressedResourceTestCase.java, core/src/test/java/io/undertow/server/handlers/file/data1.json, core/src/test/java/io/undertow/server/handlers/file/data2.json
Jira: https://issues.redhat.com/browse/UNDERTOW-1950
Master PR: #1205
=> [UNDERTOW-1950]  Fix NullPointerException in PreCompressedResourceSupplier

core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java, core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java, core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java, core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java, core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java, core/src/main/java/io/undertow/server/handlers/cache/LimitedBufferSlicePool.java, core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java, core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java, core/src/main/java/io/undertow/util/HeaderMap.java, core/src/main/java/io/undertow/util/HeaderValues.java, core/src/main/java/io/undertow/util/HexConverter.java, core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java, core/src/main/java/io/undertow/util/SubstringMap.java, core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java, core/src/main/java9/io/undertow/util/FastConcurrentDirectDeque.java, servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardRequestWrapper.java, servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardResponseWrapper.java, websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowContainerProvider.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1879
=> [UNDERTOW-1879] Utilize o.w.common.Assert class for Null-Checks

core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/test/java/io/undertow/client/http/H2CUpgradeResetTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1984
Adding the missing initialization of the `lastAssignedStreamOtherSide` when an upgrade is initiated via `createInitialUpgradeResponseStream`.
=> [UNDERTOW-1984] GOAWAY sent by HTTP2 server when a RST is sent after upgrade

core/src/main/java/io/undertow/util/NetworkUtils.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1872
2.0.x PR: https://github.com/undertow-io/undertow/pull/1128
=> [UNDERTOW-1872] fix ipv6 parsing with trailling empty block

core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
https://issues.redhat.com/browse/UNDERTOW-2002
=> [UNDERTOW-2002] Fixing StackOverflowError upon AJP read timeout

core/src/main/java/io/undertow/security/impl/DigestAuthenticationMechanism.java
https://issues.redhat.com/browse/UNDERTOW-2007
=> [UNDERTOW-2007] Digest mechanism needs sticky sessions

core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2012
=> [UNDERTOW-2012] create temp directory for uploads

core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
Previously, small buffers that required multiple events to write
would not save the correct header state, resulting in NPEs
and requests which failed to include all headers.
This PR removes the duplicated state between the method body
and HttpRequestConduit in favor of exclusively using
HttpRequestConduit fields. This way the behavior across state
changes is unlikely to be impacted at all.
Hotspot isn't able to optimize field access quite as well
as local method scoped variables, however this isn't likely
to have an impact in practice, and it's more important to
send all headers with every request.
=> UNDERTOW-2017: HttpRequestConduit state is correctly maintained

core/src/main/java/io/undertow/conduits/FixedLengthStreamSourceConduit.java
https://issues.redhat.com/browse/UNDERTOW-2018
=> UNDERTOW-2018: Fix NPE in FixedLengthStreamSourceConduit on failure

servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletTestCase.java, servlet/src/test/java/io/undertow/servlet/test/defaultservlet/meta-inf/secret
This PR tries to add a test for issue: https://issues.redhat.com/browse/UNDERTOW-1981
=> [UNDERTOW-2025][UNDERTOW-1981] Test that client cannot access files inside of meta-info sub folder

core/src/main/java/io/undertow/io/UndertowOutputStream.java, core/src/test/java/io/undertow/server/handlers/HeadBlockingExchangeTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2019
=> UNDERTOW-2019: Blocking exchanges can set HEAD response length

core/src/test/java/io/undertow/server/ssl/SimpleSSLTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1848
Changes in the test:
* Reduce the load depending the #CPU in the box. The concurrency is set to #CPU*8 up to 32 (before it was always 32 threads). The idea is reducing the number of simultaneous requests when the box has less than 4 CPUs to not stress too much.
* The SO timeout of the socket has been increased from 5s to 60s (exception `java.net.SocketTimeoutException: Read timed out`).
* The total await time was changed from fixed 70s to a while that waits for 10s and counts processed requests. The test stops if failed or if in that period no requests were processed. This way there is no hard time limit.
I have tested the class a lot of times in my VM and no failures even with only 1CPU assigned (which takes 3-5 minutes in each test). …
=> [UNDERTOW-1848] SimpleSSLTestCase fails on Windows

core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java, core/src/test/java/io/undertow/client/http/HttpClientTestCase.java, core/src/test/java/io/undertow/testutils/DefaultServer.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2027
AFAICT there is no real leak in `HttpClientTestCase.testReadTimeout`. The problem is with the TS. Two problems fixed in this PR related to that test:
1. Re-adding the read timeout when doing a `resumeReads` if not previously set. Added a new test `testReadTimeoutAtInit` which forces the timeout before writing anything back to the client.
2. Fixing how the buffer leaks are detected in the TS. Now the method waits 20s to get a `isEmpty` in the set. The same local variable is always used to avoid that random buffer allocations triggers spurious errors. This took me a lot of time. :smile: 
Thanks!
=> [UNDERTOW-2027] Spurious buffer leak error in the test-suite (HttpClientTestCase.testReadTimeout)

README.md
Jira: https://issues.redhat.com/browse/UNDERTOW-2044
=> [UNDERTOW-2044] Update README

core/src/main/java/io/undertow/io/UndertowInputStream.java, servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java, servlet/src/main/java/io/undertow/servlet/spec/UpgradeServletInputStream.java
https://issues.redhat.com/browse/UNDERTOW-2038
=> UNDERTOW-2038: InputStream.read implementations avoid unnecessary ByteBuffer.wrap

core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java, core/src/test/java/io/undertow/server/handlers/IPAddressAccessControlHandlerUnitTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2061
=> [UNDERTOW-2061] prefix not formed properly in ACL

pom.xml
JDK17 support has been added in version 4.3.0 [1]
[1] https://github.com/spotbugs/spotbugs-maven-plugin/releases/tag/spotbugs-maven-plugin-4.3.0
https://issues.redhat.com/browse/UNDERTOW-2091
=> [UNDERTOW-2091] spotbugs-maven-plugin needs to be updated to work with JDK17

servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriterDelegate.java, servlet/src/test/java/io/undertow/servlet/test/response/writer/ExceptionWriterServlet.java, servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2102
Initializing the lock object using the ServletPrintWriter passed as argument.
PR for 2.2.x branch.
PR for master: https://github.com/undertow-io/undertow/pull/1335
=> [UNDERTOW-2102] ServletPrintWriterDelegate throws exception using OpenJDK 19 EA

core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2034
https://issues.redhat.com/browse/UNDERTOW-2035
https://issues.redhat.com/browse/UNDERTOW-2079
https://issues.redhat.com/browse/UNDERTOW-2080
=> [UNDERTOW-2034][UNDERTOW-2035][UNDERTOW-2079][UNDERTOW-2080] Fixes for AbstractFramedStreamSinkChannel and Http2StreamSinkChannel await methods

core/pom.xml, servlet/pom.xml, servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServlet.java, servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServletTestCase.java, websockets-jsr/pom.xml
Issue: https://issues.redhat.com/browse/UNDERTOW-2122
There are javax imports (instead of jakarta)  that are creating issues in master. I have fixed that and also added `failIfNoTests` to `true` in the main poms because the error was undetected because of that. If you prefer to not add the last part just let me know.
@ropalka @fl4via Please review this when you have time. This is stopping my other PRs. :smile: 
Thanks!
=> [UNDERTOW-2122] Javax imports in servlet tests

servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java, servlet/src/test/java/io/undertow/servlet/test/SimpleServletTestCase.java, servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectWithContentLengthTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2116
Main modifications:
* Now the `ServletOutputStreamImpl` only resets to 0 if it's not a HEAD method.
* I duplicated the same behavior in the two methods that manage this (`close` and `closeAsync`).
* In order to fix the HEAD too, methods `sendError` and `sendRedirect` in `HttpServletResponseImpl` clean any possible `Content-Length` header added before by the app.
* Tests added.
This PR is for the master 2.2.x.
PR for 2.2.x: https://github.com/undertow-io/undertow/pull/1345
@fl4via PR for the master branch is ready.
=> [UNDERTOW-2116] ServletOutputStreamImpl incorrectly sets Content-Length to 0

servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseClientServlet.java, servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseServlet.java, servlet/src/test/java/io/undertow/servlet/test/streams/ForceDrainServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2130
Just removing the @RunWith annotation that is present in three test Servlets. They are bothering QA in the CI. I cherry-picked what @kstekovi did in his branch.
=> [UNDERTOW-2130] Classes witch annotation RunWith are triggered as TestCase

core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
https://issues.redhat.com/browse/UNDERTOW-2133
CVE-2022-2053
If the request is too big, throw an excpetion to allow the connection to
be cleaned up closed properly up the call stack.
=> [UNDERTOW-2133] CVE-2022-2053 Handle RequestTooBigException

core/src/main/java/io/undertow/server/handlers/encoding/ContentEncodingRepository.java, core/src/main/java/io/undertow/util/QValueParser.java
Fixes [UNDERTOW-2131](https://issues.redhat.com/browse/UNDERTOW-2131)
`ContentEncodingRepository.getContentEncodings(HttpServerExchange)` allocates many `ArrayList` iterators in hot paths for handling requests. It may be worthwhile to avoid using for-each loops and instead use old fashioned for loop with `List.get(int)` to avoid additional allocations during request processing.
```
java.util.ArrayList$Itr
at java.util.ArrayList.iterator()
at java.util.AbstractCollection.addAll(Collection)
at io.undertow.server.handlers.encoding.ContentEncodingRepository.getContentEncodings(HttpServerExchange)
at io.undertow.server.handlers.encoding.EncodingHandler.handleRequest(HttpServerExchange)
```
=> [UNDERTOW-2131] ContentEncodingRepository avoids iterator allocations

core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Read Timeout Test Case Fail on Windows with JDK17 due to different exception message
https://issues.redhat.com/browse/UNDERTOW-2113
=> [UNDERTOW-2113] Read Timeout Test Case Fail on Windows with JDK17 due to different exception message

core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java, core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java, core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java, core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseClientServlet.java, servlet/src/test/java/io/undertow/servlet/test/streams/EarlyCloseServlet.java, servlet/src/test/java/io/undertow/servlet/test/streams/ForceDrainServlet.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2031
https://issues.redhat.com/browse/UNDERTOW-2113
https://issues.redhat.com/browse/UNDERTOW-2130
https://issues.redhat.com/browse/UNDERTOW-2133
https://issues.redhat.com/browse/UNDERTOW-2135
=> [UNDERTOW-2031][UNDERTOW-2113][UNDERTOW-2130][UNDERTOW-2133][UNDERTOW-2135] backport bug fixes to 2.2.x branch

core/src/test/java/io/undertow/server/security/ClientCertRenegotiationTestCase.java
UNDERTOW-2112 Assume the testcase for jdk < 14. New version TLSv1.3 and new JDK versions are breaking this feature
https://issues.redhat.com/browse/UNDERTOW-2112
=> UNDERTOW-2112 Client Cert Renegotiation is not supported by JDK14 and newer. 

core/src/test/java/io/undertow/server/security/ClientCertRenegotiationTestCase.java
UNDERTOW-2112 Assume the testcase for jdk < 14. New version TLSv1.3 and new JDK versions are breaking this feature
https://issues.redhat.com/browse/UNDERTOW-2112
=> [UNDERTOW-2112] Client Cert Renegotiation is not supported by JDK14 and newer. 

core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java, core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java, core/src/main/java/io/undertow/websockets/core/WebSocketMessages.java, core/src/test/java/io/undertow/websockets/core/protocol/AbstractWebSocketServerTest.java, core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java, servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java, servlet/src/test/java/io/undertow/servlet/test/security/constraint/SecurityConstraintUrlMappingWithUnspecifiedForbiddenTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1997
https://issues.redhat.com/browse/UNDERTOW-2083
https://issues.redhat.com/browse/UNDERTOW-2112
https://issues.redhat.com/browse/UNDERTOW-2125
=> 2.2.x backport bug fixes

core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java, core/src/main/java/io/undertow/websockets/client/WebSocket13ClientHandshake.java, spotbugs-exclude.xml
Let's try to reuse instance of `SecureRandom` class when possible. This
change is attempt to fix error identified by SpotBugs plugin and
described in [1].
[1] https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#dmi-random-object-created-and-used-only-once-dmi-random-used-only-once
https://issues.redhat.com/browse/UNDERTOW-2097
=> [UNDERTOW-2097] DMI_RANDOM_USED_ONLY_ONCE error reported by spotbugs

servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java, servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java, servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
https://issues.redhat.com/browse/UNDERTOW-1902
@fl4via Please review.  I can backport to the relevant branches once you are satisfied.
When integrating into WildFly, we will want to expose this configuration via the ServletContainer management model.
=> UNDERTOW-1902 Undertow allows session creation and session ID change after response is committed.

servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
**Issue:** https://issues.redhat.com/browse/UNDERTOW-2162
**Description:** : We found this issue after upgrade to Wildfly 26.1.2, and the following code no longer work as expected
```
RequestDispatcher rd = request.getRequestDispatcher("/aaa?url=http://bb.com");
rd.forward(request, response);
``` 
The forwarded request has path `/aaa?url=http:/bb.com` which caused by canonicalize the whole path with query params in `ServletContextImpl`. 
**Fix**: Only canonicalize the servlet path in `ServletContextImpl`
**Test**:
* Unit test added in `DispatcherForwardTestCase`
* Tested locally with the updated undertow-servlet 2.2.19 jar in wildfly 26.1.2 modules, works great.
=> UNDERTOW-2162: Only canonicalize the servlet path when getting request dispatcher

core/src/main/java/io/undertow/attribute/SslClientCertAttribute.java, core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java, core/src/main/java/io/undertow/server/ConnectionSSLSessionInfo.java, core/src/main/java/io/undertow/server/DefaultByteBufferPool.java, core/src/main/java/io/undertow/server/handlers/SSLHeaderHandler.java, core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java, core/src/main/java/io/undertow/server/protocol/http2/Http2SslSessionInfo.java, core/src/main/java/io/undertow/util/Certificates.java, core/src/main/java/io/undertow/util/HttpString.java, servlet/src/main/java/io/undertow/servlet/handlers/security/SSLInformationAssociationHandler.java
https://issues.redhat.com/browse/UNDERTOW-1771
Updated from deprecated javax.security.cert Classes to current java.security.cert
Deprecated javax.security.cert APIs usage is limited to XNIO API Usage
Finalize methods not needed on (Auto)Closeables
super.finalize should always be called, and called last.
Signed-off-by: Steve Davidson <steve@j2eeguys.com>
=> [UNDERTOW-1771] APIs deprecated in JDK 9+ are in use

core/src/main/java/io/undertow/server/Connectors.java, core/src/test/java/io/undertow/testutils/DefaultServer.java, servlet/src/test/java/io/undertow/servlet/test/streams/AbstractServletInputStreamTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/AsyncInputStreamServlet.java, servlet/src/test/java/io/undertow/servlet/test/streams/AsyncOutputStreamServlet.java, servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1818
There are different changes in the PR although the former is the main one (the rest fixes minor issues in the same `AbstractServletInputStreamTestCase` test):
1. The direct solution for the issue is in the `Connectors` class. As the method is called `ungetRequestBytes` the order is directly changed. If we identify that something needs to insert real new data at the current point in the exchange (not data that was read before and is push back to be read again) another method can be created with the previous order. I think that all the callers are using the re-read / push-back idea.
2. Adding a max queue size because sometimes proxy tests fail (error 500) when concurrency tests start in input stream classes. The proxy conf now allows the …
=> [UNDERTOW-1818] AbstractServletInputStreamTestCase.runTestParallel fails with bytes out of order

servlet/src/main/java/io/undertow/servlet/core/ManagedFilter.java, servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilter.java, servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilterTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2069
=> [UNDERTOW-2069] Fix the deadlock and add a test for it

core/src/test/java/io/undertow/server/handlers/JDBCLogDatabaseTestCase.java, pom.xml
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2171 upgrade h2 database to 2.1.214
https://issues.redhat.com/browse/UNDERTOW-2172 upgrade easy mock to 4.3
https://issues.redhat.com/browse/UNDERTOW-2173 upgrade jakarta annotation api to 2.1.1
https://issues.redhat.com/browse/UNDERTOW-2174 remove batavia dependencies
https://issues.redhat.com/browse/UNDERTOW-2175 upgrade junit to 4.13.2
https://issues.redhat.com/browse/UNDERTOW-2177 upgrade netty to 4.1.82.Final
https://issues.redhat.com/browse/UNDERTOW-2178 upgrade jboss class file writer to 1.2.5.Final
https://issues.redhat.com/browse/UNDERTOW-2179 upgrade jboss logging to 3.4.3.Final
https://issues.redhat.com/browse/UNDERTOW-2180 upgrade jboss log manager to 2.1.19.Final
https://issues.redhat.com/browse/UNDERTOW-2181 upgrade XNIO to …
=> [UNDERTOW-2171..UNDERTOW-2175][UNDERTOW-2177..UNDERTOW-2183] Dependencies upgrade

core/src/main/java/io/undertow/conduits/DeflatingStreamSinkConduit.java, core/src/main/java/io/undertow/conduits/GzipStreamSinkConduit.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2143
=> UNDERTOW-2143 Deflaters operate directly on ByteBuffers

core/pom.xml, core/src/test/java/io/undertow/server/handlers/BlockingReadTimeoutHandlerTestCase.java, core/src/test/java/io/undertow/server/handlers/URLDecodingHandlerTestCase.java, core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java, core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java, core/src/test/java/io/undertow/server/security/SpnegoAuthenticationTestCase.java, core/src/test/java/io/undertow/testutils/HttpClientUtils.java, core/src/test/java/io/undertow/websockets/extensions/AutobahnExtensionCustomReceiverServer.java, core/src/test/java/io/undertow/websockets/extensions/AutobahnExtensionsServer.java, pom.xml
Issue: https://issues.redhat.com/browse/UNDERTOW-2185
Changes:
* Upgrade apacheds to 2.0.0.AM26, now the test artifact should be used in combination with the kerberos interceptor for the spnego tests.
* Tests previously used things from apacheds dependencies, all of them have been removed and substituted by two methods in the `HttpClientUtils` utility test class.
* The dependency for log4j has been removed from autobahn cos I think it's not used for anything in the tests.
Just remind the comment in the Jira. The version 2.0.0.AM26 has an issue with IBM jdk-8 and it doesn't work with it. So take care and do not backport to 2.2.x if the TS should work with that runtime. Last version that works with IBM jdk-8 is AM25.
=> [UNDERTOW-2185] Upgrade Apache DS to 2.0.0.AM26

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2054
There are errors with leaks in CI runs involving `SslConduit` (mainly `doUnwrap` method). For example this [run](https://github.com/undertow-io/undertow/actions/runs/3321170261/jobs/5488507673) or this [run](https://github.com/undertow-io/undertow/actions/runs/3235864053/jobs/5300966510). As commented in  the JIRA I think that the reason is that there is a race between the `close` and the `doUnwrap` (called by a handle read in the channel). The `doUnwrap` checks at the beginning that it is not closed but it can be closed during the execution. And if a new `dataToUnwrap` was buffered after the close it is never freed. So just adding a new condition that cleans the buffers in the finally if the conduit is closed. If you prefer to throw a …
=> [UNDERTOW-2054] Buffer leak errors involving SslConduit on CI

core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java, core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java, servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java, servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletNoDirectoryListingTestCase.java, servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2190
Only send css and js for directory listing if it's enabled. Doing the same for the `ResourceHandler` and the `DefaultServlet`. Tests added for both cases.
@fl4via @ropalka An easy fix to not display the related resources for directory listing if not enabled.
=> [UNDERTOW-2190] DefaultServlet serves CSS and JS blobs even if directory listing is disabled

core/src/main/java/io/undertow/channels/DetachableStreamSourceChannel.java, core/src/main/java/io/undertow/server/HttpServerExchange.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2189
Two main changes:
* The `DetachableStreamSourceChannel` does not throw and exception in `getOption` if finished. It delegates to the wrapped `StreamSourceChannel`. This way the exception is avoided when using a fake channel, created [here](https://github.com/rmartinc/undertow/blob/2d5f2a3eecb8b91b038d3b04a4d228dc44ea24a6/core/src/main/java/io/undertow/server/HttpServerExchange.java#L1284).
* The `DefaultBlockingHttpExchange` now only closes input/output streams if used (`!= null`) or not completed, avoiding calling close twice in normal flow when they were not used and fully read/written.
All CIs worked for me. I have even tested jakartaee 8 TCK to see if something failed.
=> [UNDERTOW-2189] IOException thrown when trying to close already closed stream

core/src/main/java/io/undertow/server/Connectors.java, core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java, servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java, servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchPathTestServlet.java, servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchServlet.java, servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardPathTestServlet.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java, servlet/src/test/java/io/undertow/servlet/test/spec/PathTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2206
The main idea is that dispatcher now decodes passed path as a normal (network) request. Code is refactored a bit to group all the dispatcher methods together in an utility class.
@ropalka Please run jakartaee 10 TCK (at least servlet) with it.
@baranowb Check your reproducer with this one. It should work as before now.
=> [UNDERTOW-1591][UNDERTOW-2123][UNDERTOW-2206] IAE trying to decode a requestPath

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java, core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2198
Adding new option `SSL_SNI_HOSTNAME` to force the SNI hostname. This is needed by the wildfly-http-client which uses IP to connect but the SNI should be set to teh correct hostname. Tests added that uses hostname/ip to connect to the server (tests are assumed if the address does not resolve to hostname).
PR to 2.2.x branch.
PR for master: https://github.com/undertow-io/undertow/pull/1402
=> [UNDERTOW-2198] Add Option to force the SNIHostName

CODEOWNERS, CONTRIBUTING.md, README.md, SECURITY.md
information to separate files. Add CODEOWNERS file
Jira: https://issues.redhat.com/browse/UNDERTOW-2023
=> [UNDERTOW-2023] Update README file, extracting contributing and security

core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/test/java/io/undertow/server/protocol/http/ParserResumeTestCase.java
Issue: https://issues.redhat.com/browse/JBEAP-24415
Upstream issue: https://issues.redhat.com/browse/UNDERTOW-2221
Upstream PR: https://github.com/undertow-io/undertow/pull/1431
=> UNDERTOW-2221 Path param parsing not resumed correctly

core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2234
The last JDK update resumes the session for the test. Just using a different `SSLContext` for each test avoids the cache and performs the full negotiation in each method.
PR for master:
PR for 2.2.x: https://github.com/undertow-io/undertow/pull/1436
=> [UNDERTOW-2234] HttpClientSNITestCase fails with last jdk 11.0.18 and 17.0.6

core/src/main/java/io/undertow/io/UndertowOutputStream.java, core/src/test/java/io/undertow/server/handlers/blocking/BlockingServerStreamClosureTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamClosureTestCase.java
Previously, setting Content-Length would auto-close the stream in such a way that a flush after the final write would throw an IOException due to internal self-closure.
=> UNDERTOW-2207: UndertowOutputStream allows flush after writes

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2252
=>  [UNDERTOW-2252] Potential fix for the SslConduit.dataToUnwrap buffer leak

servlet/src/main/java/io/undertow/servlet/core/SessionListenerBridge.java, servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
https://issues.redhat.com/browse/UNDERTOW-2192
Pending equivalent for master: (TODO)
=> [UNDERTOW-2192] session.getServletContext returns wrong context with shared-session-config

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/client/http/HttpClientProvider.java, core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java, core/src/main/java/io/undertow/io/UndertowOutputStream.java, core/src/main/java/io/undertow/protocols/ssl/SslConduit.java, core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java, core/src/test/java/io/undertow/client/http/Http2ClientTestCase.java, core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java, core/src/test/java/io/undertow/client/http/HttpClientTestCase.java, core/src/test/java/io/undertow/server/handlers/blocking/BlockingServerStreamClosureTestCase.java, servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamClosureTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2207
https://issues.redhat.com/browse/UNDERTOW-2212
https://issues.redhat.com/browse/UNDERTOW-2239
https://issues.redhat.com/browse/UNDERTOW-2252
=> [UNDERTOW-2207][UNDERTOW-2212][UNDERTOW-2239][UNDERTOW-2252] 2.2.x backport bug fixes

core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java, core/src/test/java/io/undertow/testutils/DefaultServer.java
...by waiting for a worker cycle to complete after closing the open listener's connections, making sure no connection is going to be reused in the next request.
Jira: https://issues.redhat.com/browse/UNDERTOW-1938
=> [UNDERTOW-1938] Resolve MaxRequestSizeTestCase flakiness on Windows

core/src/main/java/io/undertow/util/HeaderMap.java
The previous fix is not fully correct. This completes the UNDERTOW-2258 fix.
Jira: https://issues.redhat.com/browse/UNDERTOW-2258
=> [UNDERTOW-2258] Fix the new method HeaderMap.putAll

core/src/main/java/io/undertow/client/http2/Http2ClientConnection.java, core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java, core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java, core/src/main/java/io/undertow/protocols/http2/Http2StreamSourceChannel.java, core/src/main/java/io/undertow/server/DirectByteBufferDeallocator.java, core/src/main/java/io/undertow/util/HeaderMap.java, core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java, core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancerConnectionPoolingTestCase.java, core/src/test/java/io/undertow/testutils/DefaultServer.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1938
https://issues.redhat.com/browse/UNDERTOW-2246
https://issues.redhat.com/browse/UNDERTOW-2251
https://issues.redhat.com/browse/UNDERTOW-2258
https://issues.redhat.com/browse/UNDERTOW-2259
=> [UNDERTOW-1938][UNDERTOW-2259][UNDERTOW-2258][UNDERTOW-2246][UNDERTOW-2251] Backport bug fixes

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java, core/src/main/java/io/undertow/util/ReferenceCountedPooled.java, core/src/test/java/io/undertow/client/http/Http2WindowUpdateTimeoutTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2056
https://issues.redhat.com/browse/UNDERTOW-2075
https://issues.redhat.com/browse/UNDERTOW-2076
https://issues.redhat.com/browse/UNDERTOW-2077
https://issues.redhat.com/browse/UNDERTOW-2137
=> [UNDERTOW-2056][UNDERTOW-2075][UNDERTOW-2076][UNDERTOW-2077][UNDERTOW-2137] CVE-2022-1259 and related fixes

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/protocols/http2/Http2StreamSinkChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java, core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java, core/src/main/java/io/undertow/util/ReferenceCountedPooled.java, core/src/test/java/io/undertow/client/http/Http2WindowUpdateTimeoutTestCase.java
Backport CVE-2022-1259 from master branch to 2.2.x (#1477)
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2056
https://issues.redhat.com/browse/UNDERTOW-2075
https://issues.redhat.com/browse/UNDERTOW-2076
https://issues.redhat.com/browse/UNDERTOW-2077
https://issues.redhat.com/browse/UNDERTOW-2137
=>  [UNDERTOW-2056][UNDERTOW-2075][UNDERTOW-2076][UNDERTOW-2077][UNDERTOW-2137] CVE-2022-1259 and related fixes

core/src/main/java/io/undertow/attribute/RequestURLAttribute.java, core/src/main/java/io/undertow/predicate/PathPrefixPredicate.java, core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java, core/src/test/java/io/undertow/server/handlers/ResourcePredicateHandlerTestCase.java, servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2216
=> [UNDERTOW-2216] fix resource serving via predicates + test

core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java, core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancingProxyWithHeaderTableSizeSettingsTestCase.java
…by making sure that proxy handler does not forward http2 settings incompatible with the proxy local settings.
This was causing the proxy to send a bigger header table size to server in the HTTP2-Settings headers. As a consequence, the server would try to set the wrong table size, bigger than actually supported, and this would just result in an exception when hpack decoder is invoked with the new header table size.
Jira: https://issues.redhat.com/browse/UNDERTOW-2255
=> [UNDERTOW-2255] Solve the Hpack decoding exception

core/src/main/java/io/undertow/util/HeaderMap.java, core/src/test/java/io/undertow/util/HeaderMapTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2276
I've added a test which reproduces the defect prior to the provided `HeaderMap` change. It's a bit subtle because `HeaderMap.remove(header)` doesn't reproduce the problem as it removes the HeaderValues entirely, but removal via the HeaderValues collection does not clear the map entry.
=> UNDERTOW-2276: Fix NPE in HeaderMap.contains

core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java, core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java, core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java, core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2241
https://issues.redhat.com/browse/UNDERTOW-2247
https://issues.redhat.com/browse/UNDERTOW-2248
Also, commenting out test for failure https://issues.redhat.com/browse/UNDERTOW-2279
2.2.x backport PR: https://github.com/undertow-io/undertow/pull/1450
=>  [UNDERTOW-2241][UNDERTOW-2247][UNDERTOW-2248] Handle write timeout properly so no chunk errors occur

core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/test/java/io/undertow/server/MultipleRequestsWriteTimeoutTestCase.java
https://issues.redhat.com/browse/JBEAP-24358 
https://issues.redhat.com/browse/UNDERTOW-2228
This change resets the expireTime variable in the
WriteTimeoutStreamSinkConduit at the end of each request. This should
prevent a subsequent request on the same connection to be affected by
timeout counter started during a previous request.
=> UNDERTOW-2228 Undertow write-timeout can cause a truncate response for request coming through keep-alive connection

core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/test/java/io/undertow/server/MultipleRequestsWriteTimeoutTestCase.java
This applies to scenarios like:
* multiple HTTP requests over a single Keep-Alive connection,
* JBoss remoting where multiple invocations come over single connection.
Issue: https://issues.redhat.com/browse/JBEAP-24358
Upstream Issue: https://issues.redhat.com/browse/UNDERTOW-2228
Upstream PR: https://github.com/undertow-io/undertow/pull/1475
=> UNDERTOW-2228 Reset write timeout on suspendWrites()

core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java, core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2281
2.2.x PR: #1499
=> [UNDERTOW-2281] At Http2FrameHeaderParser, throw a protocol error for headers not followed by data 

servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java, servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludeServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2285
This is the back port of https://github.com/undertow-io/undertow/pull/1496 to `2.2.x` branch
=> [UNDERTOW-2285] Query parameters get lost in the included JSP page

core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Issue: https://issues.redhat.com/browse/JBEAP-24861
Upstream issue: https://issues.redhat.com/browse/UNDERTOW-2275
Upstream PR: https://github.com/undertow-io/undertow/pull/1480
=> UNDERTOW-2275 Suspend reads before terminating a request to cleanup read-timeout

core/src/main/java/io/undertow/client/http2/Http2ClearClientProvider.java
https://issues.redhat.com/browse/UNDERTOW-2305
https://issues.redhat.com/browse/JBEAP-25508
=> UNDERTOW-2305 Fix NPE in Http2ClearClientProvider

core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
https://issues.redhat.com/browse/UNDERTOW-2072
=> [UNDERTOW-2072] DefaultByteBufferPool.getBuffer() may return null

core/src/main/java/io/undertow/client/http2/Http2ClearClientProvider.java, core/src/main/java/io/undertow/server/DefaultByteBufferPool.java, core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java, core/src/main/java/io/undertow/server/session/InMemorySessionManager.java, core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2305 #1513 
https://issues.redhat.com/browse/UNDERTOW-2271 #1521 
https://issues.redhat.com/browse/UNDERTOW-2072 #1333 
https://issues.redhat.com/browse/UNDERTOW-2316 #1520
=> [UNDERTOW-2305][UNDERTOW-2271][UNDERTOW-2072]  CVE-2023-3223 Backport bug fixes

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/server/HttpServerExchange.java
https://issues.redhat.com/browse/UNDERTOW-2310
https://issues.redhat.com/browse/UNDERTOW-2311
=> [UNDERTOw-2310][UNDERTOW-2311] Introducing Missing Default Constants

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/test/java/io/undertow/client/http2/DoSHttp2ClientConnection.java, core/src/test/java/io/undertow/protocols/http2/RapidResetDDoSUnitTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2311
https://issues.redhat.com/browse/UNDERTOW-2327
https://issues.redhat.com/browse/UNDERTOW-2323
=> [UNDERTOW-2323] Fix for CVE-2023-44487 and related issues

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/test/java/io/undertow/client/http2/DoSHttp2ClientConnection.java, core/src/test/java/io/undertow/protocols/http2/RapidResetDDoSUnitTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2310 #1515
https://issues.redhat.com/browse/UNDERTOW-2311 #1515 #1525 
https://issues.redhat.com/browse/UNDERTOW-2327 #1525 
https://issues.redhat.com/browse/UNDERTOW-2323 #1525
=> [UNDERTOW-2323][UNDERTOW-2311][UNDERTOW-2310][UNDERTOW-2327] CVE-2023-44487 backport fixes to branch 2.2.x

core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
https://issues.redhat.com/browse/UNDERTOW-2309
This is for your consideration, the memory leak is not large in terms of memory consumed. If we have doubts we can close this.
=> UNDERTOW-2309 Prevent memory leak in DefaultByteBufferPool

core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2304
=> [UNDERTOW-2304] Prevent repeating SslConduit.doUnwrap when running hanshake task

core/src/main/java/io/undertow/server/handlers/RequestDumpingHandler.java, core/src/main/java/io/undertow/server/handlers/form/FormData.java, core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java, core/src/main/java/io/undertow/util/FileUtils.java, core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/test/java/io/undertow/servlet/test/multipart/AddMultipartServetListener.java, servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java, servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2337
=> [UNDERTOW-2337] Multipart form-data larger than 16KiB is not available through Servlet getParameter API

websockets-jsr/src/main/java/io/undertow/websockets/jsr/DefaultWebSocketClientSslProvider.java
https://issues.redhat.com/browse/UNDERTOW-2345
With websocket 2.1 in Jakara EE10,
"ClientEndpointConfig.Builder sslContext​(SSLContext sslContext)"
method has been added that allows us to hold SSLContext within ClientEndpointConfig.
The current DefaultWebSocketClientSslProvider (in Undertow WebSockets JSR356 implementations) ignores it.
=> [UNDERTOW-2345] Use SSLContext from ClientEndpointConfig when provided

core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http/ParseState.java, core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Proxies such as httpd proxy do not resolve the path segment "/..;/" to be a double dot segment, so they would pass such request path unchanged to target server. Undertow on the other hand resolves "/..;/" as double dot, which can cause essentially a path traversal problem, where client can request resources that should not be available to him per proxy configuration.
Jira: https://issues.redhat.com/browse/UNDERTOW-2339
=> [UNDERTOW-2339] CVE-2024-1459 Path segment "/..;" should not be treated as "/.."

core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java, core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http/ParseState.java, core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2280 CVE-2023-5379 master PR: #1555 
https://issues.redhat.com/browse/UNDERTOW-2336 CVE-2024-1459 master PR: #1557 
https://issues.redhat.com/browse/UNDERTOW-2339 CVE-2024-1635 master PR: #1556
=> [UNDERTOW-2280][UNDERTOW-2336][UNDERTOW-2339] CVE-2023-5379 CVE-2024-1459 CVE-2024-1635 Backport bug fixes

core/src/test/java/io/undertow/server/handlers/SenderTestCase.java
https://issues.redhat.com/browse/UNDERTOW-1926
I executed this 100 times locally and I was not able to reproduce the failure.
=> [UNDERTOW-1926] Enabling all tests of SenderTestCase

core/src/main/java/io/undertow/client/http/HttpClientProvider.java, core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
https://issues.redhat.com/browse/UNDERTOW-2347
=> [UNDERTOW-2347] Always specify at least http/1.1 in application_layer_protocol_negotiation ALPN extension when doing TLS

CONTRIBUTING.md
Couple of minor fixes.
Jira: https://issues.redhat.com/browse/UNDERTOW-2375
=> [UNDERTOW-2375] Minor fixes in contributing guide: broken links, types, style fixes.

core/src/main/java/io/undertow/client/http/HttpClientProvider.java, core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java, core/src/test/java/io/undertow/server/handlers/SenderTestCase.java, servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/BadAnnotatedEndpointTestCase.java, websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/BadOnMessageEndpoint.java
Jiras: 
https://issues.redhat.com/browse/UNDERTOW-2347 #1561 
https://issues.redhat.com/browse/UNDERTOW-1926 #1567 
https://issues.redhat.com/browse/UNDERTOW-2351 #1562
=> [UNDERTOW-2347] [UNDERTOW-1926] [UNDERTOW-2351] Backport fixes to 2.2.x branch

CONTRIBUTING.md, core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java, core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java, servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2264 #1581 
https://issues.redhat.com/browse/UNDERTOW-2374 #1580 
https://issues.redhat.com/browse/UNDERTOW-2375 #1535
=> [UNDERTOW-2264] [UNDERTOW-2374] [UNDERTOW-2375] CVE-2023-1973 Backport fixes/enhancements to 2.2.x branch

pom.xml
This tries to limit build using JDK 8 only for 2.2.x branch to avoid some errors like: `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer` if it was built using JDK 11 but running using JDK8.
upstream not needed
Jira: https://issues.redhat.com/browse/UNDERTOW-2376
=> [UNDERTOW-2376] Enforce to build using JDK8 for 2.2.x branch

core/src/main/java/io/undertow/UndertowLogger.java, core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java, core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingSender.java, core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java, core/src/main/java/io/undertow/server/handlers/resource/CachedResource.java, core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2332
Needs review. Im still wondering if there is way to update exchange on buffer write in last commit vs invalidation. Not sure if its feasible.
=> UNDERTOW-2332 CachingResource mishandling with TTL =0 and FS exhaustion

servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncResponseWriterOnPostServlet.java, servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterOnPostServlet.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2400
=> [UNDERTOW-2400] Fix ResponseWriterTestCase failures

core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2385
Duplicated Jira: https://issues.redhat.com/browse/UNDERTOW-2389
Incorporates #1589 and #1591
=> [UNDERTOW-2385] Use synchronized WeakHashMap in DefaultByteBufferPool

servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
https://issues.redhat.com/browse/UNDERTOW-2378
=> [UNDERTOW-2378] Adjust properly session timeout also for alternative AUTH mechanisms

servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
https://issues.redhat.com/browse/UNDERTOW-2383
=> [UNDERTOW-2383] do not canonicalize query string in sendRedirect location

pom.xml
Bumps xnio from 3.8.8.Final to 3.8.14.Final, which is the latest version and the first version to fix CVE-2023-5685
jira ticket is https://issues.redhat.com/browse/UNDERTOW-2391
=> [UNDERTOW-2391] CVE-2023-5685 bump xnio to bring in fix for the CVE

core/pom.xml, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java, core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java, core/src/main/java/io/undertow/server/protocol/http/HttpOpenListener.java, core/src/main/java/io/undertow/server/protocol/http2/Http2OpenListener.java, core/src/test/java/io/undertow/server/handlers/DefaultMaxHeaderTestCase.java, core/src/test/java/io/undertow/server/handlers/LongURLTestCase.java, core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java, core/src/test/java/io/undertow/server/handlers/LotsOfQueryParametersTestCase.java, core/src/test/java/io/undertow/testutils/DefaultServer.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2405
=> [UNDERTOW-2405] CVE-2024-27316 Add system property io.undertow.http2-max-header-size (default value set to 20000)

servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2409
Related Issue: https://issues.redhat.com/browse/UNDERTOW-2378
Upstream PR: https://github.com/undertow-io/undertow/pull/1608
Related PR: https://github.com/undertow-io/undertow/pull/1585
=> [UNDERTOW-2409] Adjust properly session timeout also in case when GET requests with custom auth mechanisms are used

.github/workflows/ci.yml
Jira: https://issues.redhat.com/browse/UNDERTOW-2415
=> [UNDERTOW-2415] Disable CI tests for JDK8 in MacOS

core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2397
Maintenance branch: https://github.com/undertow-io/undertow/pull/1621
=> [UNDERTOW-2397] Properly index huffman table on encoding

examples/src/main/java/io/undertow/examples/http2/Http2Server.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2357
=> [UNDERTOW-2357] remove JDK check in Http2 exapmle

core/src/main/java/io/undertow/UndertowOptions.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2193
Maintenance branch: https://github.com/undertow-io/undertow/pull/1624
=> [UNDERTOW-2193] Add uniform unity description to UndertwoOptions

core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2046
Maintenance branch: https://github.com/undertow-io/undertow/pull/1625
Local TS run did not blow up.
=> [UNDERTOW-2046] X-Forwarded-For is IP header, not hostname

examples/src/main/java/io/undertow/examples/http2/Http2Server.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2357
Upstream PR: https://github.com/undertow-io/undertow/pull/1570
=> [UNDERTOW-2357] remove JDK check in Http2 example

core/src/main/java/io/undertow/Handlers.java, core/src/main/java/io/undertow/protocols/ssl/SslConduit.java, core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java, core/src/main/java/io/undertow/server/handlers/PathHandler.java, core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java, core/src/main/java/io/undertow/server/handlers/cache/LRUCache.java, core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java, servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java, servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2413 main PR: #1638
https://issues.redhat.com/browse/UNDERTOW-2382 main PR: #1639
2.3.x PR: #1640
=> [UNDERTOW-2413][UNDERTOW-2382] CVE-2024-5971 CVE-2024-3653 Backport bug fixes

core/src/main/java/io/undertow/server/HttpServerExchange.java, servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java, servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1901
=> [UNDERTOW-1901] -  fix max entity handling for multipart

core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
https://issues.redhat.com/browse/UNDERTOW-2039
=> [UNDERTOW-2039] Convert AbstractFramedChannel.AWAIT_WRITABLE_TIMEOUT to nanoseconds

core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java, core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2256
=> [UNDERTOW-2256] Resource predicate presentation differs depending on how it is set up

core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2321
=> [UNDERTOW-2321] add "commonv" pattern to accesslog

servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
Hi,
this addresses https://issues.redhat.com/projects/UNDERTOW/issues/UNDERTOW-2295, which came up while trying to mitigate https://spring.io/security/cve-2023-34035 and https://github.com/spring-projects/spring-security/issues/13568
Tests were green locally. Feel free to discuss the implications of this either here or in the ticket. This is more of a starting point to get the ball rolling. Unfortunately, I couldn't find a ticket that references the decision behind the default servlet registration, but only the commit https://github.com/undertow-io/undertow/commit/71c5a691 which is unfortunately not providing more info. 
There is https://issues.redhat.com/browse/UNDERTOW-149 which introduced a check for the managed default servlet not being registered twice, which the PR still kept.
Since …
=> [UNDERTOW-2295] Stop registration of managed default servlet in case default servlet exists

core/src/main/java/io/undertow/predicate/ip/IPMatchBase.java, core/src/main/java/io/undertow/predicate/ip/IPMatchPredicate.java, core/src/main/java/io/undertow/server/handlers/IPAddressAccessControlHandler.java, core/src/main/resources/META-INF/services/io.undertow.predicate.PredicateBuilder, core/src/test/java/io/undertow/server/handlers/IPMatchPredicateTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2287
=> [UNDERTOW-2287] Add ACL style ip-match predicate

core/src/main/java/io/undertow/Handlers.java, core/src/main/java/io/undertow/server/handlers/AccessControlListHandler.java, core/src/test/java/io/undertow/server/handlers/UserAgentAccessControlHandlerUnitTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1737
=> [UNDERTOW-1737] add failure-reason to AccessControlListHandler

core/src/main/java/io/undertow/server/session/InMemorySessionManager.java, core/src/main/java/io/undertow/server/session/Session.java, servlet/src/main/java/io/undertow/servlet/spec/HttpSessionImpl.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1904
=> [UNDERTOW-1904] remove exception flow control

core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java, core/src/test/java/io/undertow/conduits/ChunkedStreamSinkConduitTest.java
ChunkedStreamSinkConduit releases underlying connections for reuse via a conduit listener, however flush calls may still be passed through after writes are terminated and successfully flushed. This would cause requests to be clobbered when the connection had already been reused to send another request, breaking the threading model.
This resolves the issue from https://github.com/undertow-io/undertow/pull/1495
For posterity: My first attempt at a fix was #1645 which resolves the issue, but I think this PR is cleaner and more precise. As always, I'm happy to throw the code out if you prefer a different approach, the important piece is the analysis of the root cause of the failures, which I believe I understand at this point :-)
=> UNDERTOW-2424: Prevent connection access-after-free allowed through ChunkedStreamSinkConduit

core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java, core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java, core/src/main/java/io/undertow/server/Connectors.java, core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java, core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java, core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java, core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java, core/src/test/java/io/undertow/conduits/ChunkedStreamSinkConduitTest.java, core/src/test/java/io/undertow/server/handlers/accesslog/AccessLogFileWithUnescapedCharactersTestCase.java, core/src/test/java/io/undertow/server/protocol/ajp/AjpCharacterEncodingTestCase.java, core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java, servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java, servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java, servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java, spotbugs-exclude.xml
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2312 #1516
https://issues.redhat.com/browse/UNDERTOW-2425 #1647
https://issues.redhat.com/browse/UNDERTOW-2424 #1645
Backport to 2.2.x branch: #1652
=>  [UNDERTOW-2312][UNDERTOW-2425][UNDERTOW-2424] Backport fixes

core/src/main/java/io/undertow/attribute/StoredResponse.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2412
=> [UNDERTOW-2412] Read stored json with default UTF-8 encoding

pom.xml
Issue: https://issues.redhat.com/browse/UNDERTOW-2432
=> [UNDERTOW-2432] Bump jdoc plugin to 3.3.0+

core/src/main/java/io/undertow/server/HttpServerExchange.java
https://issues.redhat.com/browse/UNDERTOW-2436
=> [UNDERTOW-2436] fix HttpServerExchange state flag race conditions

core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java, core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2422
Currently, no matter what you set the HttpServerExchange.protocol field to, the value "HTTP/1.1" will always be used. This change will use the value of the protocol field (or "HTTP/1.1" if the field is empty) in the HTTP response's status line.
There is a test included in this PR. It confirms the default behavior and the new behavior.
=> [UNDERTOW-2422] Return the protocol field of the HttpServerExchange into the status line

core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2279
=> [UNDERTOW-2279] Re-enable LotsOfHeadersResponseTestCase in Windows

core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java, core/src/test/java/io/undertow/predicate/PredicateParsingTestCase.java, core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1748
=> [UNDERTOW-1748] add comment line to predicates

core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2444
2.4.x: https://github.com/undertow-io/undertow/pull/1662
2.3.x: https://github.com/undertow-io/undertow/pull/1663
2.2.x: https://github.com/undertow-io/undertow/pull/1664
=> [UNDERTOW-2444] Fix RST scenario violation in H2

core/src/main/java/io/undertow/UndertowOptions.java
Adds `forRemoval` field for `HTTP2_SETTINGS_MAX_HEADER_LIST_SIZE`.  [Issue Link](https://issues.redhat.com/browse/UNDERTOW-2483)
=> [UNDERTOW-2483] - marked deprecated field forRemoval

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
This adds a default value for `HTTP2_SETTINGS_INITIAL_WINDOW_SIZE`. [link](https://issues.redhat.com/browse/UNDERTOW-2481)
=> [UNDERTOW-2481] Add DEFAULT_HTTP2_SETTINGS_INITIAL_WINDOW_SIZE

core/src/main/java/io/undertow/UndertowOptions.java
This adds a default value for `QUEUED_FRAMES_LOW_WATERMARK`. [Issue Link](https://issues.redhat.com/browse/UNDERTOW-2495)
=> [UNDERTOW-2495] adds DEFAULT_QUEUED_FRAMES_LOW_WATERMARK

.github/workflows/ci.yml, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/attribute/StoredResponse.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java, core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java, core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2412
https://issues.redhat.com/browse/UNDERTOW-2445
https://issues.redhat.com/browse/UNDERTOW-2449
https://issues.redhat.com/browse/UNDERTOW-2446
https://issues.redhat.com/browse/UNDERTOW-2436
https://issues.redhat.com/browse/UNDERTOW-2422
https://issues.redhat.com/browse/UNDERTOW-2444
https://issues.redhat.com/browse/UNDERTOW-2448
=> [UNDERTOW-2412 / 2445 / 2449 / 2446 / 2436 / 2422 / 2444 / 2448] Backport fixes to 2.3.x

.github/workflows/ci.yml, core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/attribute/StoredResponse.java, core/src/main/java/io/undertow/protocols/http2/Http2Channel.java, core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java, core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java, core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java, core/src/test/java/io/undertow/server/handlers/StatusLineTestCase.java, servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java, servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2412
https://issues.redhat.com/browse/UNDERTOW-2445
https://issues.redhat.com/browse/UNDERTOW-2449
https://issues.redhat.com/browse/UNDERTOW-2446
https://issues.redhat.com/browse/UNDERTOW-2436
https://issues.redhat.com/browse/UNDERTOW-2422
https://issues.redhat.com/browse/UNDERTOW-2444
https://issues.redhat.com/browse/UNDERTOW-2448
2.3.x PR: #1687
=> [UNDERTOW-2412 / 2445 / 2449 / 2446 / 2436 / 2422 / 2444 / 2448] Backport fixes to 2.2.x

core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
Jira:
https://issues.redhat.com/browse/UNDERTOW-2518
=> [UNDERTOW-2518] At WebSocketTimeoutTestCase, use a longer watch timeout

core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java, core/src/test/java/io/undertow/server/handlers/form/MultipartFormDataParserTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2509
=> [UNDERTOW-2509] Add 413 response code to overflowing multipart in default async handler

websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/security/WebsocketBasicAuthTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2504
=> [UNDERTOW-2504] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.security

websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2503
=> [UNDERTOW-2503] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.reconnect

core/src/main/java/io/undertow/websockets/core/CloseMessage.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2520
The values 1002 and 1003 were swapped compared to the RFC.
=> [UNDERTOW-2520] Fix close code constants

core/src/main/java/io/undertow/server/HttpServerExchange.java, core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java, core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
Jira:
https://issues.redhat.com/browse/UNDERTOW-2519
=> [UNDERTOW-2519] At ProxyHandler append the non-decoded query string to the request

servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
Jira:  https://issues.redhat.com/browse/UNDERTOW-2344
I am still studying if this is the best solution to the problem...
=> [UNDERTOW-2344] Take into account that close could run concurrently with a read operation

core/src/main/java/io/undertow/UndertowMessages.java, core/src/main/java/io/undertow/conduits/GzipStreamSourceConduit.java, core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java, core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2361
=> [UNDERTOW-2361] handle inflater wrapping properly in deflate encoding

servlet/src/test/java/io/undertow/servlet/test/handlers/AbstractHttpContinueServletTestCase.java, servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueSslServletTestCase.java
There are five tests in the test class `HttpContinueSslServletTestCase`. However, they reply on the same DefaultServer to send post http request. The time cost of start or stop for the DefaultServer is high. They are not modifying the contents of the DefaultServer, thus we can just initialize the DefaultServer once before or after all test methods inside test class `HttpContinueSslServletTestCase`.
The test runtime can jump from `5.43160 s` to `1.8027 s` after applying these changes when run on our machine.
=> [UNDERTOW-2371] initialize the DefaultServer once to speed up test HttpContinueSslServletTestCase

core/src/main/java/io/undertow/Undertow.java, core/src/test/java/io/undertow/server/protocol/http2/HTTP2OnListenerTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2301
=> [UNDERTOW-2301] add ability to configure http2 per listener

core/src/main/java/io/undertow/UndertowOptions.java, core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2319
RFE: https://github.com/xjusko/wildfly-proposals/commit/0ef689a8f9d4910f3486ce1fdf6dc2625eb99efa
=> [UNDERTOW-2319] Move io.undertow.multipart.minsize property to UndertowOptions

core/src/main/java/io/undertow/io/AsyncReceiverImpl.java, core/src/main/java/io/undertow/io/BlockingReceiverImpl.java, core/src/main/java/io/undertow/server/handlers/encoding/RequestEncodingHandler.java, core/src/main/java/io/undertow/util/Headers.java, core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase2.java, core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase3.java, core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase4.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2340
This needs review. Possibly change to Partial receive methods?
=> [UNDERTOW-2340] Remove Content-Length header when request is deflated.

servlet/src/main/java/io/undertow/servlet/attribute/ServletRelativePathAttribute.java
…a priority of 1 as there is a matching ExchangeAttribute in the core module.
https://issues.redhat.com/browse/UNDERTOW-2538
=> [UNDERTOW-2538] The ServletRelativePathAttribute.Builder should have a priority of 1

websockets-jsr/src/main/java/io/undertow/websockets/jsr/JsrWebSocketMessages.java, websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketSessionRemoteEndpoint.java
Hello.
I modified it in consideration of the case where NPE can occur when sending text message to websocket session.
Please check the [UNDERTOW-2532](https://issues.redhat.com/browse/UNDERTOW-2532) jira ticket for more information.
Thanks.
=> [UNDERTOW-2532] Fix NPE when transmitting text or binary message to websocket session at the same time

core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java, core/src/test/java/io/undertow/server/handlers/proxy/ProxyHandlerXForwardedForTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2576
=> [UNDERTOW-2576] ProxyHandler can throw NullPointerException if the source address SocketAddress has no ip address

core/src/main/java/io/undertow/security/impl/DigestAuthorizationToken.java, core/src/test/java/io/undertow/server/security/ParseDigestAuthorizationTokenTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2590
Adds support of 'rspauth' in Digest auth header
=> [UNDERTOW-2590] Support 'rspauth' in Digest auth header
