- core/src/main/java/io/undertow/server/handlers/proxy/LoadBalancingProxyClient.java
- core/src/main/java/io/undertow/server/handlers/proxy/ProxyConnectionPool.java
- core/src/test/java/io/undertow/server/handlers/proxy/ChannelConnectCloseHttpHandler.java
- core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancerConnectionPoolingTestCase.java
Pull request to handle https://issues.jboss.org/browse/UNDERTOW-379
> UNDERTOW-379 - closing idle connections

- core/src/main/java/io/undertow/server/handlers/proxy/HostPicker.java
- core/src/main/java/io/undertow/server/handlers/proxy/LoadBalancingProxyClient.java
- core/src/main/java/io/undertow/server/handlers/proxy/RoundRobinHostPicker.java
- core/src/test/java/io/undertow/server/handlers/proxy/LoadBalancingProxyWithCustomHostPickerTestCase.java
My use case is that I want to pick hosts from the same data center firstly, i have noticed that someone create issue for it:
https://issues.jboss.org/browse/UNDERTOW-289
> UNDERTOW-289

- core/src/main/java/io/undertow/util/MimeMappings.java
Trivial change to support serving bmp files as images.
> Added BMP as image/bmp

- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPAdvertiseTask.java
> Added debug and info log messages that I found missing.

- core/src/main/java/io/undertow/UndertowLogger.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Balancer.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPAdvertiseTask.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/MCMPHandler.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Node.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/NodeConfig.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/NodePingUtil.java
* refactored messages to use UndertowLogger methods
* added additional DEBUG messages that aid QE
> [UNDERTOW-447] Debug message on mod_cluster MCMP handler creation.

- core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
- core/src/test/java/io/undertow/server/handlers/PredicatedHandlersProxyTestCase.java
Added the argument so that requests could be made to upstream that required another Host header.
Also and made the proxy use a SimpleProxyClientProvider if theres only 1 host in the list of hosts
> Added rewrite-host-header argument

- core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/HeaderMap.java
- core/src/main/java/io/undertow/util/HeaderValues.java
- core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
- parser-generator/pom.xml
- parser-generator/src/main/java/io/undertow/annotationprocessor/HttpParserAnnotationProcessor.java
- pom.xml
- mostly changes around jboss-parent & checkstyle
DO NOT MERGE until:
https://github.com/undertow-io/undertow-checkstyle-config/pull/1 is merged and released.
> Update build to prepare it for Java 8

- pom.xml
mostly to test new github status api integration with teamcity
> Minor build change

- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
See [wildfly/pull/7920](https://github.com/wildfly/wildfly/pull/7920) for explanation. This PR depends on [WFLY-4954](https://issues.jboss.org/browse/WFLY-4954).
> UseAlias defaults to false, aligned with WFLY-4954

- core/src/main/java/io/undertow/util/HeaderTokenParser.java
Also clear the 'containsEscapes' boolean after processing the value otherwise it remains set for the remaining values.
> [UNDERTOW-567] Count the '\' characters within the value as a quote being preceeded by an even number of '\' characters is not escaped.

- core/src/main/java/io/undertow/server/ConnectorStatistics.java
- core/src/main/java/io/undertow/server/ConnectorStatisticsImpl.java
https://issues.jboss.org/browse/UNDERTOW-570
> UNDERTOW-570 correct computing of processingTime

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/server/handlers/JDBCLogHandler.java
- core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
Adding a jdbc-access-log builder with a datasource and format parameters.
Jira; https://issues.jboss.org/browse/UNDERTOW-627
> [UNDERTOW-627]: Add Builder to JDBCLogHandler for easier use

- servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
- servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
:arrow_down: This is just the 1.4.x version of the pull request for https://github.com/undertow-io/undertow/pull/354
> [UNDERTOW-549] 1.4.x Allow an alternative initial security handler to be provided that takes responsibility for the authentication of a request.

- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
Fixes https://issues.jboss.org/browse/WFLY-6413
> Fixing DefaultServlet Content-Range header counting

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Hey,
just stumbled upon this unused variable. Keep up the great work.
Cheers,
Christoph
> Removed unused variable in HttpServletRequestImpl

- core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Needs some additional verification
> UNDERTOW-709 Buffer pool holds references to thread local buffers

- core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
> [1.3] UNDERTOW-709 Buffer pool holds references to thread local buffers

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
https://issues.jboss.org/browse/UNDERTOW-767
> [master] UNDERTOW-767 Change sessionNotFound() message to sessionIsInvalid()

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
https://issues.jboss.org/browse/UNDERTOW-767
> [1.4.x] UNDERTOW-767 Change sessionNotFound() message to sessionIsInvalid()

- core/src/main/java/io/undertow/attribute/ResponseTimeAttribute.java
(cherry picked from commit f52572b322f11ea666932cb65b72e092bf8da97a)
> [UNDERTOW-787]: Fix to convert response time to seconds format

- core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
- According to the HTTP2 specification https://tools.ietf.org/html/rfc7540#section-8.1.2.3
'All HTTP/2 requests MUST include exactly one valid value for the
":method", ":scheme", and ":path" pseudo-header fields, unless it is
a CONNECT request (Section 8.3).  An HTTP request that omits
mandatory pseudo-header fields is malformed (Section 8.1.2.6).'
- therefore occurence instead of presence is checked now for :method,
:scheme and :path pseudo-header fields now
- check for :authority is removed at all as specification says nothing about it
> [UNDERTOW-816] check number of occurence of HTTP2 pseudo-headers.

- core/src/main/java/io/undertow/server/handlers/resource/ClassPathResourceManager.java
- parser-generator/src/main/java/io/undertow/annotationprocessor/AbstractParserGenerator.java
- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
Hey,
instead of checking for equality with an empty string we could check for emptyness on the string itself, which is more efficient. I replaced all occurences in the project.
Cheers,
Christoph
> Replace String.equals("") with String.isEmpty() check

- core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java
https://issues.jboss.org/browse/UNDERTOW-852
https://issues.jboss.org/browse/JBEAP-6258
https://issues.jboss.org/browse/UNDERTOW-851
https://issues.jboss.org/browse/JBEAP-6257
Upstream PR: https://github.com/undertow-io/undertow/pull/432
> [UNDERTOW-852] Web server should return 501 for unknown METHOD requests

- core/src/main/java/io/undertow/protocols/ajp/AjpClientRequestClientStreamSinkChannel.java
- core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
same change as https://github.com/undertow-io/undertow/pull/449
This is for https://issues.jboss.org/browse/WFLY-7692
> Expose default values.

- servlet/src/main/java/io/undertow/servlet/api/ListenerInfo.java
Changed method signature to correctly reflect returned class.
> UNDERTOW-941 Fixed method return type.

- core/src/main/java/io/undertow/Undertow.java
I would like to require certificates for some listeners but not others, without shedding the builder api.
> Allow custom socket options per listener

- servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
- servlet/src/test/java/io/undertow/servlet/test/security/custom/ServletCustomAuthTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/security/form/FormLoginServlet.java
- servlet/src/test/java/io/undertow/servlet/test/security/form/SaveOriginalPostRequestTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/security/form/ServletFormAuthURLRewriteTestCase.java
[JBEAP-8386] : https://issues.jboss.org/browse/JBEAP-8386
> UNDERTOW-958 ensure any jsessionid in URL is updated upon login

- core/src/main/java/io/undertow/predicate/EqualsPredicate.java
- core/src/main/java/io/undertow/predicate/ExistsPredicate.java
- core/src/main/java/io/undertow/predicate/FalsePredicate.java
- core/src/main/java/io/undertow/predicate/MaxContentSizePredicate.java
- core/src/main/java/io/undertow/predicate/MethodPredicate.java
- core/src/main/java/io/undertow/predicate/MinContentSizePredicate.java
- core/src/main/java/io/undertow/predicate/NotPredicate.java
- core/src/main/java/io/undertow/predicate/PathMatchPredicate.java
- core/src/main/java/io/undertow/predicate/PathPrefixPredicate.java
- core/src/main/java/io/undertow/predicate/PathSuffixPredicate.java
- core/src/main/java/io/undertow/predicate/TruePredicate.java
- core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
* Service providers must be public classes (or nested within a public class)
* Avoid duplicated service definition
> UNDERTOW-987 Some preparations for building/running Undertow with Jigsaw

- core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
https://issues.jboss.org/browse/JBEAP-8803
> [JBEAP-8803] ajp connection hangs if a post HTTP request header contains 'Transfer-Encoding: chunked'

- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- core/src/test/java/io/undertow/server/handlers/LotsOfQueryParametersTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1005 and https://issues.jboss.org/browse/JBEAP-8589
> [UNDERTOW-1005] fix issue in max-parameters counting.

- core/src/main/java/io/undertow/server/handlers/resource/PathResource.java
- core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
- core/src/test/java/io/undertow/server/handlers/file/PathResourceManagerTestCase.java
PathResourceManagers already provided eight constructors, this
adds a builder to avoid more going forward.
> PathResourceManager may be configured with an ETagFunction

- core/src/main/java/io/undertow/security/handlers/CachedAuthenticatedSessionHandler.java
- core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
- core/src/test/java/io/undertow/server/security/AuthenticationTestBase.java
- core/src/test/java/io/undertow/server/security/BasicAuthenticationTestCase.java
- core/src/test/java/io/undertow/server/security/ClientCertRenegotiationTestCase.java
- core/src/test/java/io/undertow/server/security/ClientCertTestCase.java
- core/src/test/java/io/undertow/server/security/DigestAuthentication2069TestCase.java
- core/src/test/java/io/undertow/server/security/DigestAuthenticationAuthTestCase.java
- core/src/test/java/io/undertow/server/security/FormAuthTestCase.java
- core/src/test/java/io/undertow/server/security/GenericHeaderAuthenticationTestCase.java
- core/src/test/java/io/undertow/server/security/SpnegoAuthenticationTestCase.java
- core/src/test/java/io/undertow/server/security/SpnegoBasicAuthenticationTestCase.java
- core/src/test/java/io/undertow/server/security/SpnegoDigestAuthenticationTestCase.java
Backport of https://issues.jboss.org/browse/UNDERTOW-884 for 1.3.x branch
JIRA: https://issues.jboss.org/browse/JBEAP-9874
> UNDERTOW-884 non servlet form auth does not compute correct location

- core/src/test/java/io/undertow/server/security/FormAuthTestCase.java
Original test was passing whether there was or wasn't included fix for
UNDERTOW-884 in io.undertow.security.impl.FormAuthenticationMechanism.
This change enhances the test to fail in case of wrong location header
@stuartwdouglas if you are OK with this change, please put it also to 1.4.x and 1.3.x branches.
> Exposing actual test failure in case of UNDERTOW-884

- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Context.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterProxyTarget.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/Node.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/VirtualHost.java
Port of #460 for 1.3 branch
EAP 7.0 JIRA: https://issues.jboss.org/browse/JBEAP-10173
Undertow JIRA: https://issues.jboss.org/browse/UNDERTOW-898
> UNDERTOW-898 Failover targets should be chosen deterministically

- core/src/main/java/io/undertow/server/handlers/accesslog/ExtendedAccessLogParser.java
Problem cause missing **return** statements.
> UNDERTOW-1064 problem with decoding x-A/R/S/P(XXX) log options

- coverage-report/pom.xml
- pom.xml
Updated jacoco version + fixed creation of merged report to single jacoco exec file.
> Jacoco update

- core/src/main/java/io/undertow/conduits/DeflatingStreamSinkConduit.java
In some error cases terminateWrites may be called after
freeBuffer, so we must check that deflater is non-null. Otherwise
we may inadvertantly clobber a deflater that has been picked
up elsewhere.
> Fix edge case where DeflatingStreamSinkConduit may leak a Deflater

- core/src/main/java/io/undertow/UndertowLogger.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
- servlet/src/test/java/io/undertow/servlet/test/streams/AsyncOutputStreamServlet.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamTestCase.java
Writes are suspended prior to execution, and resumed once
ServletOutputStream.isReady returns false.
> UNDERTOW-1103: Servlet 3.1 WriteListener impls can run asynchronously

- core/src/main/java/io/undertow/UndertowMessages.java
https://issues.jboss.org/browse/UNDERTOW-1142
> [UNDERTOW-1142] fix of two minor typos in log messages

- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
cherry-pick from commit c57112532f02094ea8b66bec7e15469a9d7175c8
upstream:- 
JIRA:- https://issues.jboss.org/browse/UNDERTOW-1077
> [JBEAP-12455] Backpot UNDERTOW-1077 to EAP 7.0.x

- core/src/main/java/io/undertow/security/api/AuthenticationMechanismFactory.java
- servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
Signed-off-by: Scott Stark <starksm64@gmail.com>
> UNDERTOW-1148 possible approach

- core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
Fixing issues detected by findbugs. Issues related to updating volatile field in threads unsafe way.
@stuartwdouglas if you are ok with this change, please cherry-pick this change also to 1.4.x branch.
> findbugs - volatile items updated via atomic field updater

- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
See title & https://issues.jboss.org/browse/UNDERTOW-1323
> UNDERTOW-1323 added possibility to specify reuseXForwarded value of the ProxyHandler that gets created by ModCluster

- servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
https://issues.jboss.org/browse/UNDERTOW-1346
> UNDERTOW-1346 Add clear methods for collection fields of DeploymentInfo

- servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
- servlet/src/test/java/io/undertow/servlet/test/listener/servletcontext/ServletContextListenerTestCase.java
Deprecated existing methods for compatibility.
> UNDERTOW-1375: Fix DeploymentInfo ServletContainerInitializer spelling

- core/src/main/java/io/undertow/protocols/alpn/JettyAlpnProvider.java
- core/src/test/java/io/undertow/server/handlers/encoding/DeflateContentEncodingTestCase.java
- core/src/test/java/io/undertow/server/handlers/encoding/GzipContentEncodingSimpleObjectPoolTestCase.java
- core/src/test/java/io/undertow/server/handlers/encoding/GzipContentEncodingTestCase.java
- core/src/test/java/io/undertow/server/handlers/encoding/RequestContentEncodingTestCase.java
- core/src/test/java/io/undertow/server/handlers/file/ContentEncodedResourceTestCase.java
- core/src/test/java/io/undertow/server/handlers/file/PreCompressedResourceTestCase.java
- pom.xml
- servlet/pom.xml
- remove non used propertites 
- jboss-parent 28
- fix compression tests to use new http client api
> update dependancies to latest, fix tests to use new api

- core/src/main/java/io/undertow/protocols/alpn/ALPNManager.java
Use an array for more efficient looping.
> ALPNManager.getProvider no longer allocates an iterator

- core/src/main/java/io/undertow/Undertow.java
> remove the needless 'if' code

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketDeploymentInfo.java
https://issues.jboss.org/browse/UNDERTOW-1414
@stuartwdouglas could you please review?
> [UNDERTOW-1414] Allow creating custom clones of WebSocketDeploymentInfo

- core/src/main/java/io/undertow/conduits/BytesReceivedStreamSourceConduit.java
- core/src/main/java/io/undertow/conduits/BytesSentStreamSinkConduit.java
I'm not sure what the preferred way to test this is. Happy to write a few if you can point me in the right direction.
> UNDERTOW-1421: ByteActivityCallback is called with positive values

- pom.xml
- remove leftovers from commit 1faa06fe4d4c4eabe78d6888413c790a43ddcb79
https://issues.jboss.org/browse/UNDERTOW-1433
> [UNDERTOW-1433] Remove unnecessary version properties.

- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingTestCase.java
Caching resource manager does not handle range requests if file is too large to fit in cache
> Regression test for Undertow 1444

- core/src/main/java/io/undertow/server/protocol/http/AlpnOpenListener.java
Updated visibility from public to private.
> UNDERTOW-1450: AlpnOpenListener.REQUIRED_PROTOCOLS is not mutable

- core/src/main/java/io/undertow/server/Connectors.java
No need to recreate the listener for every request.
> Singleton Connectors.ungetRequestBytes ExchangeCompletionListener

- servlet/src/test/java/io/undertow/servlet/test/security/MultipartAcceptingServlet.java
- servlet/src/test/java/io/undertow/servlet/test/security/basic/ServletCertAndDigestAuthTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1417
> UNDERTOW-1417 Test case

- core/src/main/java/io/undertow/server/handlers/resource/PathResource.java
- core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
- core/src/test/java/io/undertow/server/handlers/file/PathResourceManagerTestCase.java
https://issues.jboss.org/browse/UNDERTOW-1440
> UNDERTOW-1440 Support non-default file systems in PathResourceManager

- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java
https://issues.jboss.org/browse/UNDERTOW-1435
> [UNDERTOW-1435] Fixing flaky test AnnotatedEndpointTest.testCloseReason.

- examples/src/main/java/io/undertow/examples/Runner.java
fix io.undertow.examples.Runner in the dev mode
> fix the main method in the dev mode

- servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
- servlet/src/test/java/io/undertow/servlet/test/security/custom/CustomEncodingAuthenticationMechanism.java
- servlet/src/test/java/io/undertow/servlet/test/security/custom/ServletCustomAuthFormEncodingTestCase.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1496
> [UNDERTOW-1496] Set form default encoding

- core/src/main/java/io/undertow/server/handlers/URLDecodingHandler.java
- core/src/test/java/io/undertow/server/handlers/URLDecodingHandlerTestCase.java
Added test cases to prevent future regressions. Break URLDecodingHandler
into smaller jit-friendly methods.
> URLDecodingHandler fixes and improvements

- README.md
- servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
... and two minor updates in the project
Jira: https://issues.jboss.org/browse/UNDERTOW-1159
> [UNDERTOW-1159] At RequestDispatcher.forwardImpl reset path/URL/URI after forward

- core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
- core/src/main/java/io/undertow/server/handlers/resource/PathResource.java
- core/src/test/java/io/undertow/server/handlers/file/FileHandlerIndexTestCase.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1506
> [UNDERTOW-1506] Internal Server Error (500) when using directory-listing in FileHandler

- core/src/main/java/io/undertow/server/handlers/proxy/LoadBalancingProxyClient.java
- core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
- core/src/main/java/io/undertow/server/handlers/proxy/RouteIteratorFactory.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterContainer.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModClusterProxyTarget.java
- core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/RouteParserTestCase.java
Jira
https://issues.jboss.org/browse/UNDERTOW-1432
> UNDERTOW-1432 Add support for multiple routes in JSESSIONID to reverse proxy

- core/src/main/java/io/undertow/server/handlers/RequestLimit.java
This two lines can throw exceptions in RequestLimit:
```java
task.exchange.addExchangeCompleteListener(COMPLETION_LISTENER);
task.exchange.dispatch(task.next);
```
There is a `finally` for calling the next listener, however `decrementRequests()` isn't in it. In case of an error the currently polled exchange will be skipped while `decrementRequests()` is also not called: oops, we lost a thread! At a larger workload we lose all the threads, sooner or later. We solved the problem with the change contained by this pull request.
The most common exception we experienced is this (this stack is from 1.4.18, but the problem still exists with 2.x):
```
java.lang.IllegalStateException: UT000139: Exchange already complete
at io.undertow.server.HttpServerExchange.addExchangeCompleteListener(HttpServerE …
```
> Make RequestLimit safer (2)

- pom.xml
Jira: https://issues.jboss.org/browse/UNDERTOW-1522
> [UNDERTOW-1522] Remove repository from pom

- core/src/main/java/io/undertow/Undertow.java
- core/src/main/java/io/undertow/util/UndertowOptions.java
BACKLOG, KEEP_ALIVE, TCP_NODELAY, and REUSE_ADDRESSES
> [3.x] Implement support for several UndertowOptions

- core/src/main/java/io/undertow/server/UndertowOutputStream.java
- core/src/test/java/io/undertow/server/handlers/BlockingServerStreamResetTestCase.java
Includes the fix for UNDERTOW-1526
> [3.x] Implement UndertowOutputStream.resetBuffer 

- servlet/src/main/java/io/undertow/servlet/handlers/ServletRequestContext.java
Added javadoc to current and requireCurrent
Previously requireCurrent duplicated the implementation of current.
> ServletRequestContext.requireCurrent delegates to current

- core/src/main/java/io/undertow/util/HeaderMap.java
https://issues.jboss.org/browse/UNDERTOW-1524
> [UNDERTOW-1524] Break infinite recursion within HeaderMap.

- core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
- core/src/main/java/io/undertow/server/handlers/accesslog/ExtendedAccessLogParser.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1530
> [UNDERTOW-1530] Access log adds newline by CRLF on Windows

- core/src/main/java/io/undertow/server/handlers/RequestLimit.java
- core/src/test/java/io/undertow/server/handlers/RequestLimitingHandlerTestCase.java
Changing from custom response code 513 to RFC7231 https://tools.ietf.org/html/rfc7231#section-6.6.4 response code 503 "Service Unavailable"
> Changing queue overflow response code to 503

- core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
- core/src/main/java/io/undertow/util/ReferenceCountedPooled.java
- core/src/test/java/io/undertow/server/handlers/ReceiverTestCase.java
Also re-enables the sender test case to see if this is the root cause
>  UNDERTOW-1534 HTTP/2 can enter an infinite loop

- core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
Reduces potential contention between threads using a shared
Random instance.
> UNDERTOW-1543: SimpleNonceManager uses ThreadLocalRandom

- pom.xml
Jira: https://issues.jboss.org/browse/UNDERTOW-1545
> [UNDERTOW-1545] Upgrade websocket-api_1.1_spec to 1.1.4.Final

- core/src/main/java/io/undertow/util/URLUtils.java
- core/src/test/java/io/undertow/util/URLUtilsTestCase.java
The commit here fixes the issue reported in https://issues.jboss.org/browse/UNDERTOW-1552.
This includes a testcase which reproduces the issue and verifies the fix.
> Fix for UNDERTOW-1552 

- core/src/main/java/io/undertow/server/Connectors.java
- servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
- servlet/src/test/java/io/undertow/servlet/test/response/cookies/AddCookiesServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/cookies/DuplicateCookiesServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/cookies/JSessionIDCookiesServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/cookies/OverwriteCookiesServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/cookies/ResponseCookiesTestCase.java
Jira: https://issues.jboss.org/browse/UNDERTOW-1489
> [UNDERTOW-1489] Add support for duplicate cookies

- core/src/main/java/io/undertow/client/http/HttpClientConnection.java
Issue: https://issues.jboss.org/browse/UNDERTOW-1507
> [UNDERTOW-1507] Add null checks on HttpClientConnection.ClientReadListener#handleEvent()

- core/src/main/java/io/undertow/security/impl/BasicAuthenticationMechanism.java
jira: https://issues.jboss.org/browse/UNDERTOW-1576
> UNDERTOW-1576: BASIC auth password is output as plain text at DEBUG level logging in BasicAuthenticationMechanism

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/ServerWebSocketContainer.java
I had previously created pull request #788 but made a mistake. Sorry!
> [UNDERTOW-1570] Websocket messages lost when ClientEndpointConfig provided

- pom.xml
Jira: https://issues.jboss.org/browse/UNDERTOW-1546
> [UNDERTOW-1546] Upgrade jboss-parent pom version to 35

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
- servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
- servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
JIRA: https://issues.redhat.com/browse/UNDERTOW-1646
> [UNDERTOW-1646] Inconsistent parameter count on file upload

- core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
https://issues.redhat.com/browse/UNDERTOW-1638
> UNDERTOW-1638: Fix AbstractFramedStreamSinkChannel resource release race

- core/src/main/java/io/undertow/server/handlers/proxy/ProxyConnectionPool.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1611
> [UNDERTOW-1611] Update counts and notify callback when getting RuntimeException at ProxyPoolConnection.openConnection

- core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
> Fix typo in Http2ReceiveListener.handleInitialRequest javadoc

- core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1663
> [UNDERTOW-1663] Make the expanded buffer pool volatile

- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
- core/src/main/java/io/undertow/util/URLUtils.java
- core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/session/ServletSessionTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1464
https://issues.redhat.com/browse/UNDERTOW-1671
> [UNDERTOW-1464][UNDERTOW-1671] Fix path param parsing

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/handlers/Cookie.java
- core/src/main/java/io/undertow/server/handlers/CookieImpl.java
- core/src/main/java/io/undertow/server/handlers/CookieSameSiteMode.java
- core/src/main/java/io/undertow/server/handlers/SameSiteCookieHandler.java
- core/src/main/java/io/undertow/util/Cookies.java
- core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
- core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
- core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
- core/src/test/java/io/undertow/util/CookiesTestCase.java
- core/src/test/java/io/undertow/util/SameSiteNoneIncompatibleClientCheckerTestCase.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletCookieAdaptor.java
https://issues.jboss.org/browse/UNDERTOW-1600
> UNDERTOW-1600 Enhance SameSite cookie support

- core/src/test/java/io/undertow/util/CookiesTestCase.java
- core/src/test/java/io/undertow/util/SameSiteNoneIncompatibleClientCheckerTestCase.java
- add one case to test case for cookies
- cover with tests also shouldSendSameSiteNone() and isSameSiteNoneIncompatible() methods
https://issues.redhat.com/browse/UNDERTOW-1685
> [UNDERTOW-1685] Slight test extension for SameSite cookie support

- core/src/main/java/io/undertow/server/handlers/GracefulShutdownHandler.java
1. Thread T1 calls decrementRequests. Shutdown is false, so this thread will follow the 'else' path in preparation for decrementAndGet
2. Thread T2 calls shutdown. Increments from 1 to 2, sets shutdown=true, and calls decrementRequests where decrementAndGet results in 1
3. Thread T1 completes the decrementRequests invocation reducing the active request count to zero in the else path without calling shutdownComplete.
> UNDERTOW-1701: Fix race condition in GracefulShutdownHandler

- core/pom.xml
- core/src/test/java/io/undertow/server/security/SimpleConfidentialRedirectTestCase.java
- examples/pom.xml
- pom.xml
- servlet/pom.xml
Jira: https://issues.redhat.com/browse/UNDERTOW-1675
> [UNDERTOW-1675] Upgrade dependencies for 2.1.0.Final release

- core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
- core/src/main/java/io/undertow/server/handlers/resource/SecurityActions.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1703
This is the PR to master branch
> [UNDERTOW-1703] Checking isSymbolicLink should be in doPrivileged block

- core/src/main/java/io/undertow/server/handlers/SameSiteCookieHandler.java
- core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
- core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
- core/src/test/java/io/undertow/util/SameSiteNoneIncompatibleClientCheckerTestCase.java
https://issues.redhat.com/browse/UNDERTOW-1702
> [Undertow 1702] SameSiteCookieHandler can throw NPE if request doesn't contain user-agent header

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/conduits/ChunkReader.java
JIRA: https://issues.redhat.com/browse/UNDERTOW-1708
> [UNDERTOW-1708] Invalid HTTP Request with large chunk file

- core/src/main/java/io/undertow/UndertowLogger.java
- core/src/main/java/io/undertow/server/HttpServerExchange.java
- core/src/main/java/io/undertow/server/handlers/HttpContinueReadHandler.java
- core/src/main/java/io/undertow/server/protocol/ajp/AjpServerConnection.java
- core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
- core/src/main/java/io/undertow/server/protocol/http/HttpReadListener.java
- core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
- core/src/main/java/io/undertow/server/protocol/http/HttpServerConnection.java
- core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
- core/src/test/java/io/undertow/server/handlers/HttpContinueConduitWrappingHandlerBufferLeakTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueServletTestCase.java
JIRA: https://issues.redhat.com/browse/UNDERTOW-1657
Plus: https://issues.redhat.com/browse/UNDERTOW-1709
> [UNDERTOW-1657] Memory exhaustion issue in HttpReadListener and related fixes

- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1719
A new `parsePathComplete` method has been created to not repeat the code at the end of the three situations that completes a path parsing  (common path, path with parameters and start of query string). This fixes the two issues and a little corner case.
Some more tests added and now the `isHostIncludedInRequestURI` is also checked in the majority of them.
PR for master branch.
> [UNDERTOW-1719] Handling of path parameters can set incorrect requestURI/requestPath

- core/src/test/java/io/undertow/server/handlers/session/InMemorySessionTestCase.java
This is to implement a regression test for https://issues.redhat.com/browse/UNDERTOW-1419.
Partially based on a reproducer by @aogburn.
FYI @fl4via, CC @mackaypeter
> Adding test to InMemorySessionTestCase for UNDERTOW-1419

- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- core/src/main/java/io/undertow/util/URLUtils.java
- core/src/test/java/io/undertow/server/protocol/ajp/AjpParsingUnitTestCase.java
- core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/session/ServletSessionTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1671
https://issues.redhat.com/browse/UNDERTOW-1464
Upstream PRs: #832 #868 #871
> [UNDERTOW-1464][UNDERTOW-1671] Proper parsing of matrix parameters

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
- servlet/src/test/java/io/undertow/servlet/test/session/CrossContextServletSharedSessionTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1677
Upstream PR: #872
> UNDERTOW-1677 cross context request issue with shared session managers

- core/src/main/java/io/undertow/io/AsyncSenderImpl.java
- core/src/main/java/io/undertow/io/BlockingSenderImpl.java
- servlet/src/main/java/io/undertow/servlet/core/BlockingWriterSenderImpl.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1720
Master PR: #897
> UNDERTOW-1720 fix potential race in senders

- servlet/src/main/java/io/undertow/servlet/spec/ServletInputStreamImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1713
Master PR: #892
> UNDERTOW-1713 Don't start async IO too early

- servlet/src/main/java/io/undertow/servlet/core/ErrorPages.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1762
PR: #917
> [UNDERTOW-1762] Error page for custom exception-type is not is not displayed in jsp development mode

- core/src/main/java/io/undertow/server/HttpServerExchange.java
This can be reproduced using
https://github.com/carterkozak/http2-reproducer-undertow
specifically the second test case:
https://github.com/carterkozak/http2-reproducer-undertow/tree/master/src/main/java/net/ckozak/repro/two
This PR provides two changes:
1. Http/2 channels may be closed prior to the http2 server connection
object. In this case an error is no longer logged, and the exchange
is completed as though the connection is closed. This fixes all instances
of the bug that I'm aware of. I can no longer reproduce the bug with this fix.
2. Exchange completion listeners are invoked in the unexpected case
to avoid resource leaks, and allow request logging to execute
as expected. This is defensive programming in case another issue of this
type is introduced, this way we log an error, but …
> UNDERTOW-1664: Prevent errors when http/2 channels are terminated

- core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
No impact, this simply marks an immutable field final for
readability.
> [UNDERTOW-1779] Mark several fields of Http2Channel as final

- core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
This could cause websocket tests for fail with a race
> UNDERTOW-1764 Websocket client was calling .handshake twice

- servlet/src/test/java/io/undertow/servlet/test/util/TestResourceLoader.java
- servlet/src/test/resources/logging.properties
It causesd intermittent failured when testing if-modified-since
> UNDERTOW-1767 Remove hack from TestResourceLoader

- core/src/main/java/io/undertow/Handlers.java
- core/src/main/java/io/undertow/server/handlers/SetErrorHandler.java
- core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
- servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
- servlet/src/main/java/io/undertow/servlet/handlers/SendErrorPageHandler.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1747
2.0.x PR (original PR, reverted to prevent new feature from being added to maintenance branch): #908
> UNDERTOW-1747 - Provide a mechanism for a predicate in return a servlet error page

- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1780
> [UNDERTOW-1780][JBEAP-18537] Validating request headers in HTTP2 frames

- servlet/src/main/java/io/undertow/servlet/attribute/ServletRequestURLAttribute.java
https://issues.redhat.com/browse/UNDERTOW-1788
> [UNDERTOW-1788] prefer FORWARD_REQUEST_URI over ERROR_REQUEST_URI

- core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
https://issues.redhat.com/browse/UNDERTOW-1872
> [UNDERTOW-1782][WFLY-13748]: fix for Contains non-LDH ASCII during ejb remote call in ipv6 network

- core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
https://issues.redhat.com/browse/UNDERTOW-1763
> UNDERTOW-1763 DefaultAccessLogReceiver has a concurrency issue that throws "IOException: Stream closed" or NullPointerException

- core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java
https://issues.redhat.com/browse/UNDERTOW-1766
> UNDERTOW-1766 Fix SSL Renegotiation on JDK14

- core/src/test/java/io/undertow/server/security/KerberosKDCUtil.java
https://issues.redhat.com/browse/UNDERTOW-1765
> UNDERTOW-1765 Fix SPNEGO tests on Windows JDK11

- core/src/test/java/io/undertow/server/handlers/SameSiteCookieHandlerTestCase.java
https://issues.redhat.com/browse/UNDERTOW-1724
> [UNDERTOW-1724] Remove the @RunWith from SameSiteCookieHandlerTestCase

- core/src/main/java/io/undertow/server/HttpServerExchange.java
- core/src/main/java/io/undertow/server/OverridableTreeSet.java
- core/src/main/java/io/undertow/server/handlers/Cookie.java
- core/src/main/java/io/undertow/server/handlers/CookieImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletCookieAdaptor.java
https://issues.redhat.com/browse/UNDERTOW-1795
> [UNDERTOW-1795] Always sort cookies

- core/src/main/java/io/undertow/protocols/alpn/JDK8HackAlpnProvider.java
- core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
JIRA's:
- https://issues.redhat.com/browse/UNDERTOW-1796
- https://issues.redhat.com/browse/UNDERTOW-1800
> [UNDERTOW-1796][UNDERTOW-1800] Default the io.undertow.protocols.alpn.jdk8 to true and change the order of preferred providers

- core/src/test/java/io/undertow/server/handlers/ForwardedHandlerTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1807
Master PR: #989 
2.0.x PR: #992
> UNDERTOW-1807: Fix ForwardedHandlerTestCase on jdk14+

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1743
Master PR: #986 
2.1.x PR: #995
> [UNDERTOW-1742] Don't clear attributes in closeAndDrainRequest() method

- servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
- servlet/src/test/java/io/undertow/servlet/test/errorpage/ErrorPageTestCase.java
https://issues.redhat.com/browse/UNDERTOW-1817
> [UNDERTOW-1817] Enhance error page handling to be spec compliant

- core/src/main/java/io/undertow/server/ConnectionSSLSessionInfo.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1812
> UNDERTOW-1812: Fail fast when renegotiation is requested using TLSv1.3

- core/src/main/java/io/undertow/protocols/alpn/JDK8HackAlpnProvider.java
- core/src/main/java/io/undertow/protocols/alpn/JDK9AlpnProvider.java
JIRA's:
- https://issues.redhat.com/browse/UNDERTOW-1796
- https://issues.redhat.com/browse/UNDERTOW-1800
master: #977 
2.0.x PR: #982
> [UNDERTOW-1796] [UNDERTOW-1800] Default the io.undertow.protocols.alpn.jdk8 to true and change the order of preferred providers

- core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
- core/src/test/java/io/undertow/server/protocol/http2/Http2EndExchangeTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1806
Master PR: #981 
2.0.x PR: #985
> UNDERTOW-1806 better HTTP/2 close behaviour

- core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
https://issues.redhat.com/browse/UNDERTOW-1745
2.1.x PR: #1011 
2.0.x PR: #1012
> [UNDERTOW-1745] AccessLog must contain HTTP2 Upgrade requests too

- core/src/main/java/io/undertow/server/handlers/HttpContinueReadHandler.java
- core/src/test/java/io/undertow/server/handlers/HttpContinueConduitWrappingHandlerBufferLeakTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/handlers/AbstractHttpContinueServletTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/handlers/HttpContinueSslServletTestCase.java
Jira: 
https://issues.redhat.com/browse/UNDERTOW-1816
Master PR: #1000 
2.0.x PR: #1001
> [UNDERTOW-1816] HTTPS connection abruptly closed by HttpServerConnection

- jakartaee9/pom.xml
- jakartaee9/src/main/java/io/undertow/jakartaee9/ArtifactNameTransformer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Deployer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Installer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Transformer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/PomTransformer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/TransformConstants.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/UndertowJakartaEE9Logger.java
- jakartaee9/src/main/resources/META-INF/services/org.wildfly.transformer.TransformerFactory
- jakartaee9/src/main/resources/Version.properties
- pom.xml
Jira: https://issues.redhat.com/browse/UNDERTOW-1785
> [UNDERTOW-1785][UNDERTOW-1757][UNDERTOW-1744] Merge Jakarta EE 9 work

- core/src/main/java/io/undertow/server/handlers/PathHandler.java
- core/src/main/java/io/undertow/util/PathMatcher.java
Fix some minor javadoc mistakes
> Fix minor javadoc mistakes

- jakartaee9/deploy-jakartaee9-artifacts.sh
Jira: https://issues.redhat.com/browse/UNDERTOW-1847
> [UNDERTOW-1847] Add deploy-jakartaee9-artifacts.sh script

- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatchesData.java
- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
- servlet/src/test/java/io/undertow/servlet/test/path/GetMappingServlet.java
- servlet/src/test/java/io/undertow/servlet/test/path/MappingTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/path/MultipleMatchingMappingTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/path/ServletSpecExampleTestCase.java
https://issues.redhat.com/browse/UNDERTOW-1844
> UNDERTOW-1844: Fix getHttpServletMapping when both prefix and extension match

- servlet/src/main/java/io/undertow/servlet/api/ServletSessionConfig.java
ISSUE: https://issues.redhat.com/browse/UNDERTOW-1819
> [UNDERTOW-1819] Update default values of cookies to match TCK requied

- servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1591
Master PR: #1063 
2.0.x PR: #1076
> [UNDERTOW-1591] Fix AsyncContext.dispatch() to pass decoded path

- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1864
Summary of changes:
1. There are two caches now, one that contains matches that depends on welcome files and can change and one that is fixed. Trying to maximize performance.
2. The cache that can change uses listeners and TTL (if enabled) to detect changes.
3. The TTL was added to the deployment config. So we need a minor change in wildfly to set the new field in the deployment (no schema change, the value is already there) to really activate this with the component upgrade.
4. Tests added to check welcome files modifications with and without file listeners.
@fl4via check this and tell me how you see it. We can do different things but I like this idea more. We need to backport the fix to 2.0 and 2.1 branches. I'll do when we think …
> [UNDERTOW-1864] EAP returns 403 even after adding the welcome file to unmanaged exploded deploy

- core/src/main/java/io/undertow/server/handlers/form/FormData.java
- core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
- servlet/src/main/java/io/undertow/servlet/spec/PartImpl.java
- servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartServlet.java
- servlet/src/test/java/io/undertow/servlet/test/multipart/MultiPartTestCase.java
Reverts undertow-io/undertow#1105
> Revert "[UNDERTOW-1783] Add support for part specific charsets. Charset is ca…"

- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1864
Backport of UNDERTOW-1864 for 2.1.x branch.
PR for master: https://github.com/undertow-io/undertow/pull/1113
PR for 2.0.x:  https://github.com/undertow-io/undertow/pull/1144
> [UNDERTOW-1864] (2.1.x) EAP returns 403 even after adding the welcome file to unmanaged exploded deploy

- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletCachingListenerTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1864
Backport of UNDERTOW-1864 for 2.0.x branch.
PR for master: https://github.com/undertow-io/undertow/pull/1113
PR for 2.1.x: https://github.com/undertow-io/undertow/pull/1145
> [UNDERTOW-1864] (2.0.x) EAP returns 403 even after adding the welcome file to unmanaged exploded deploy

- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1898
> [UNDERTOW-1898] DefaultServlet will not serve content from any directories starting with WEB-INF or META-INF

- core/src/main/java/io/undertow/server/HttpServerExchange.java
- servlet/src/main/java/io/undertow/servlet/core/ManagedServlet.java
- servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1601
Upstream PR: #1177
> [UNDERTOW-1601] -  fix max entity handling for multipart

- .github/workflows/ci.yml
- core/src/test/java/io/undertow/server/ParseTimeoutTestCase.java
- core/src/test/java/io/undertow/server/WriteTimeoutTestCase.java
- core/src/test/java/io/undertow/server/ssl/ComplexSSLTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1919
https://issues.redhat.com/browse/UNDERTOW-1523
https://issues.redhat.com/browse/UNDERTOW-1918
https://issues.redhat.com/browse/UNDERTOW-1923
https://issues.redhat.com/browse/UNDERTOW-1925
https://issues.redhat.com/browse/UNDERTOW-1859
> Improve the CI

- core/src/test/java/io/undertow/server/ParseTimeoutTestCase.java
- core/src/test/java/io/undertow/server/WriteTimeoutTestCase.java
- core/src/test/java/io/undertow/server/ssl/ComplexSSLTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1919
https://issues.redhat.com/browse/UNDERTOW-1523
https://issues.redhat.com/browse/UNDERTOW-1918
https://issues.redhat.com/browse/UNDERTOW-1859
> Test fixes for maintenance branch

- jakartaee9/pom.xml
- jakartaee9/src/main/java/io/undertow/jakartaee9/JakartaEE9Transformer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/PomTransformer.java
- jakartaee9/src/main/java/io/undertow/jakartaee9/UndertowJakartaEE9Logger.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1920
https://issues.redhat.com/browse/UNDERTOW-1921
https://issues.redhat.com/browse/UNDERTOW-1922
> [UNDERTOW-1920] [UNDERTOW-1921][UNDERTOW-1922] Fixes for Jakarta EE9 transformation module

- core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSinkChannel.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1842
2.0.x PR: #1191
> [UNDERTOW-1842] At AbstractFramedStreamSinkChannel.flushComplete(), requeue the final frame if we still have a body to be written

- core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
- core/src/main/java/io/undertow/server/handlers/resource/ClassPathResourceManager.java
- core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1906
Upstream PR: https://github.com/undertow-io/undertow/pull/1181
> [UNDERTOW-1906] Guard against null resource path

- core/src/test/java/io/undertow/server/handlers/proxy/mod_cluster/AbstractModClusterTestBase.java
- core/src/test/java/io/undertow/testutils/DefaultServer.java
- core/src/test/java/io/undertow/testutils/RunDefaultServer.java
- servlet/src/test/java/io/undertow/servlet/test/security/custom/ServletCustomAuthFormEncodingTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/BinaryEndpointTest.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/JsrWebSocketServer07Test.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/ProgramaticLazyEndpointTest.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/TestMessagesReceivedInOrder.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/AnnotatedEndpointTest.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/autobahn/AnnotatedAutobahnServer.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/autobahn/ProgramaticAutobahnServer.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DynamicEndpointTest.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/security/WebsocketBasicAuthTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/stress/WebsocketStressTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/suspendresume/SuspendResumeTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1857
Master PRs: #1049 #1051
> [UNDERTOW-1857] Provide a way of performing actions before starts and after server stops in tests

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java
- core/src/test/java/io/undertow/server/ReadTimeoutTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1858
Master PR: #1050
> [UNDERTOW-1858] Fix ReadTimeoutTestCase

- core/src/main/java/io/undertow/server/HttpServerExchange.java
- core/src/test/java/io/undertow/server/handlers/SetAttributeTestCase.java
Pull for this ticket: https://issues.redhat.com/browse/UNDERTOW-1894
2.0.x PR: #1168
> UNDERTOW-1894 - Better handling for leading ? on query string

- core/src/main/java/io/undertow/server/HttpServerExchange.java
- core/src/test/java/io/undertow/server/handlers/SetAttributeTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1894
Upstream PR: #1167
> UNDERTOW-1984_2.0.x

- core/src/main/java/io/undertow/websockets/client/WebSocketClient.java
- core/src/test/java/io/undertow/websockets/client/version13/WebSocketClient13TestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1471
2.0.x PR: #1094
2.1.x PR: #1093
> [UNDERTOW-1471] unify secure uri processing for wss and https

- .github/workflows/ci.yml
Jira: https://issues.redhat.com/browse/UNDERTOW-1939
> [UNDERTOW-1939] Upload dump files in github actions script

- core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java
- core/src/test/java/io/undertow/server/handlers/ReceiverTestCase.java
- core/src/test/java/io/undertow/server/handlers/SenderTestCase.java
- core/src/test/java/io/undertow/server/ssl/SimpleSSLTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamSSLTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1523
> [UNDERTOW-1523] Temporarily disable failing tests

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/FrameHandler.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1935
2.0.x PR: #1234
> [UNDERTOW-1935] - buffer leak on incoming websocket PONG message

- core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1933
2.0.x PR: #1224
> [UNDERTOW-1933] Short-circuit logic for boolean (2.2.x)

- core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1933
Master PR: #1222
> [UNDERTOW-1933] Short-circuit logic for boolean (2.0.x)

- core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
- core/src/main/java/io/undertow/conduits/InflatingStreamSourceConduit.java
- core/src/main/java/io/undertow/util/Cookies.java
- core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1931
2.0.x PR: #1235
> [UNDERTOW-1931] Avoid Nullpointer

- core/src/main/java/io/undertow/server/handlers/resource/PathResourceManager.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1916
2.0.x PR: #1220
> [UNDERTOW-1916] - fix method signature in PathResourceManager

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1789
Upstream PR: https://github.com/undertow-io/undertow/pull/1237
> [UNDERTOW-1789] - bumpTImeout on setMaxInactiveInterval

- core/src/main/java/io/undertow/Undertow.java
- core/src/main/java/io/undertow/attribute/RemoteHostAttribute.java
- core/src/main/java/io/undertow/client/http2/Http2ClientProvider.java
- core/src/main/java/io/undertow/protocols/ajp/AjpResponseParser.java
- core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
- core/src/main/java/io/undertow/protocols/http2/Http2DataStreamSinkChannel.java
- core/src/main/java/io/undertow/protocols/ssl/SNISSLExplorer.java
- core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
- core/src/main/java/io/undertow/server/handlers/RequestDumpingHandler.java
- core/src/main/java/io/undertow/server/handlers/accesslog/DefaultAccessLogReceiver.java
- core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
- core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
- core/src/main/java/io/undertow/server/protocol/http/ALPNOfferedClientHelloExplorer.java
- core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
- core/src/main/java/io/undertow/util/ETagUtils.java
- core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/PathMatcher.java
- core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
- servlet/pom.xml
- servlet/src/main/java/io/undertow/servlet/compat/rewrite/Substitution.java
- servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
- websockets-jsr/src/main/java/io/undertow/websockets/jsr/SendHandlerAdapter.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1915
Reviewers: Please cherry pick if you want to keep something.
> [UNDERTOW-1915] Remove unneccesary code

- core/src/main/java/io/undertow/protocols/http2/Http2PushBackParser.java
- core/src/main/java/io/undertow/security/impl/FormAuthenticationMechanism.java
- core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1917
Master PR: #1203
> [UNDERTOW-1917] Logic in try/finally blocks hides exceptions

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1869
Alternative to: https://github.com/undertow-io/undertow/pull/1173 (closed)
Followed up by #1196
> [UNDERTOW-1869] fix concurrency on session creation

- core/src/main/java/io/undertow/server/BasicSSLSessionInfo.java
https://issues.redhat.com/browse/UNDERTOW-1969
> [UNDERTOW-1969] Ignore deprecated certificate retrieval method failure for deprecated parts of Undertow

- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
- servlet/src/main/java/io/undertow/servlet/handlers/Paths.java
- servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
https://issues.redhat.com/browse/UNDERTOW-1981
> [UNDERTOW-1981] Unify DefaultServlet & ServletInitialHandler in handling forbidden subpaths

- core/src/main/java/io/undertow/util/NetworkUtils.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1872
Upstream PR: https://github.com/undertow-io/undertow/pull/1127
> [UNDERTOW-1872] fix ipv6 parsing with trailling empty block

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
- servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectEncodedServlet.java
- servlet/src/test/java/io/undertow/servlet/test/redirect/RedirectEncodedToSubPathTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1409
2.0.x PR: https://github.com/undertow-io/undertow/pull/1101
> [UNDERTOW-1409] fix percent encoded path redirect

- core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1740
2.0.x PR: https://github.com/undertow-io/undertow/pull/1159
> [UNDERTOW-1740] fix single predicate termination ";" parsing

- core/src/main/java/io/undertow/UndertowLogger.java
- core/src/main/java/io/undertow/security/impl/DigestAuthenticationMechanism.java
- core/src/main/java/io/undertow/security/impl/GSSAPIAuthenticationMechanism.java
Issue: https://issues.redhat.com/browse/UNDERTOW-318
2.0.xPR: https://github.com/undertow-io/undertow/pull/1138
> [UNDERTOW-318] fix GSSAPI logs

- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
- servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/async/SimpleDateThreadLocalAsyncServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1989
Re-adding the setup actions when calling the `invokeRunnable` method.
> [UNDERTOW-1989] Setup actions are not executed when using the async Start method

- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
- servlet/src/test/java/io/undertow/servlet/test/listener/request/async/onError/AsyncListenerOnErrorTest.java
- servlet/src/test/java/io/undertow/servlet/test/listener/request/async/onError/AsyncServlet5.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1786
2.0.x PR: https://github.com/undertow-io/undertow/pull/1088
> [UNDERTOW-1786] handle IO properly for async context write

- core/src/main/java/io/undertow/util/PooledAdaptor.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1992
> [UNDERTOW-1992] Add PooledAdaptor.toString()

- core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
- core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java
- core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java
- core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java
- core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java
- core/src/main/java/io/undertow/server/handlers/cache/LimitedBufferSlicePool.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
- core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/HeaderMap.java
- core/src/main/java/io/undertow/util/HeaderValues.java
- core/src/main/java/io/undertow/util/HexConverter.java
- core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/SubstringMap.java
- core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
- core/src/main/java9/io/undertow/util/FastConcurrentDirectDeque.java
- servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardRequestWrapper.java
- servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardResponseWrapper.java
- websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowContainerProvider.java
Reverts undertow-io/undertow#1089
More information on UNDERTOW-1879 comments:
https://issues.redhat.com/browse/UNDERTOW-1879
> Revert "[UNDERTOW-1879] Utilize o.w.common.Assert class for Null-Checks"

- core/src/main/java/io/undertow/client/http/HttpClientConnection.java
- core/src/test/java/io/undertow/client/http/HttpClientTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1913
Master PR: #1198
> [UNDERTOW-1913]apply ReadTimeoutStreamSourceConduit/WriteTimeoutStrea… 

- core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
- core/src/test/java/io/undertow/util/HeaderMapTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2006
> [UNDERTOW-2006] Add test that headers of different case work

- core/src/main/java/io/undertow/protocols/http2/HpackEncoder.java
- core/src/main/java/io/undertow/protocols/http2/Http2Channel.java
- core/src/test/java/io/undertow/client/http/H2CUpgradeContinuationTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1979
> [UNDERTOW-1979] CVE-2021-3859 continuation frames are not read correctly

- core/src/main/java/io/undertow/conduits/ChunkedStreamSourceConduit.java
- core/src/main/java/io/undertow/protocols/ssl/UndertowSslConnection.java
- pom.xml
Jira: https://issues.redhat.com/browse/UNDERTOW-1986
> [UNDERTOW-1986] Buffer leak errors involving buffer allocated by ChunkedStreamSourceConduit

- servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
- servlet/src/test/java/io/undertow/servlet/test/listener/servletcontext/CheckRolesServlet.java
- servlet/src/test/java/io/undertow/servlet/test/listener/servletcontext/DeclareRolesServletContextListener.java
- servlet/src/test/java/io/undertow/servlet/test/listener/servletcontext/ServletContextRolesTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1994
> [UNDERTOW-1994] impl declareRoles in ServletContext + testcase

- core/src/main/java/io/undertow/server/handlers/resource/PathResource.java
ticket: https://issues.redhat.com/browse/UNDERTOW-2011
> BugFix: UNDERTOW-2011 update getName method in PathResource class

- jakarta/servlet/pom.xml
- pom.xml
https://issues.redhat.com/browse/UNDERTOW-2000
> [UNDERTOW-2000] Properly Jakartize Undertow components - remaining fixes

- core/src/main/java/io/undertow/server/protocol/ajp/AjpServerResponseConduit.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2028
Changing `AjpServerResponseConduit` to manage responses bigger than the buffer size. Now if the conduit cannot write more to the network it stores several buffers to accommodate the remaining data. If any weird error happens the buffers are closed properly.
> [UNDERTOW-2028] Buffer leak error involving AjpServerResponseConduit

- core/src/main/java/io/undertow/conduits/FixedLengthStreamSourceConduit.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2022
> [UNDERTOW-2022] Add resumeReads to FixedLengthStreamSourceConduit

- core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
- core/src/main/java/io/undertow/server/handlers/BlockingReadTimeoutHandler.java
- core/src/main/java/io/undertow/server/handlers/BlockingWriteTimeoutHandler.java
- core/src/main/java/io/undertow/server/handlers/ChannelUpgradeHandler.java
- core/src/main/java/io/undertow/server/handlers/RequestLimitingHandler.java
- core/src/main/java/io/undertow/server/handlers/cache/LimitedBufferSlicePool.java
- core/src/main/java/io/undertow/server/handlers/proxy/mod_cluster/ModCluster.java
- core/src/main/java/io/undertow/util/FastConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/HeaderMap.java
- core/src/main/java/io/undertow/util/HeaderValues.java
- core/src/main/java/io/undertow/util/HexConverter.java
- core/src/main/java/io/undertow/util/PortableConcurrentDirectDeque.java
- core/src/main/java/io/undertow/util/SubstringMap.java
- core/src/main/java/io/undertow/websockets/core/protocol/version07/Base64.java
- core/src/main/java9/io/undertow/util/FastConcurrentDirectDeque.java
- servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardRequestWrapper.java
- servlet/src/test/java/io/undertow/servlet/test/wrapper/NonStandardResponseWrapper.java
- websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowContainerProvider.java
Fixes https://issues.redhat.com/browse/UNDERTOW-1879
> [UNDERTOW-1879] Utilize o.w.common.Assert class for Null-Checks

- pom.xml
Jiras: https://issues.redhat.com/browse/UNDERTOW-2073
https://issues.redhat.com/browse/UNDERTOW-2074
> [UNDERTOW-2074] Upgrade XNIO to 3.8.7.Final (fixes UNDERTOW-2073)

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/UndertowSession.java
https://issues.redhat.com/browse/UNDERTOW-2081
> [UNDERTOW-2081] Proceed if RejectedExecutionException is thrown

- core/src/main/java/io/undertow/UndertowOptions.java
- core/src/main/java/io/undertow/server/RequestStatistics.java
- core/src/main/java/io/undertow/server/handlers/ActiveRequestTrackerHandler.java
- core/src/main/resources/META-INF/services/io.undertow.server.handlers.builder.HandlerBuilder
- core/src/test/java/io/undertow/server/handlers/ActiveRequestTrackerTest.java
https://issues.redhat.com/browse/UNDERTOW-1593
Port active request tracking from 2.2.x
> [UNDERTOW-1593-2.3.x] [master] Port request tracking from 2.2.x

- .github/workflows/ci.yml
https://issues.redhat.com/browse/UNDERTOW-2092
> [UNDERTOW-2092] Update GitHub CI configuration to JDK11+

- .github/workflows/ci.yml
- core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
- pom.xml
- spotbugs-exclude.xml
Exclude bugs from static analyses of code and add the JBoss Nexus repo, is needed for the Jakarta RC artifacts
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2093
https://issues.redhat.com/browse/UNDERTOW-2096
> [UNDERTOW-2093][UNDERTOW-2096] Fix CI, with spotbugs fully passing

- pom.xml
https://issues.redhat.com/browse/UNDERTOW-2052
> [UNDERTOW-2052] Move Undertow to Servlet API 6.0.0

- core/src/main/java/io/undertow/server/protocol/ajp/AjpReadListener.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2060
> [UNDERTOW-2060] fix double AJP response

- core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
- core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedStreamSourceChannel.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletOutputStreamTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1945
https://issues.redhat.com/browse/UNDERTOW-2066
https://issues.redhat.com/browse/UNDERTOW-2067
https://issues.redhat.com/browse/UNDERTOW-2068
> [UNDERTOW-1945] ServletOutputStreamTestCase fails with Premature end of chunk coded message body 

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
- servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServlet.java
- servlet/src/test/java/io/undertow/servlet/test/redirect/RelativeRedirectServletTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2094
> [UNDERTOW-2094] fix relative redirect with trailing slash context

- pom.xml
https://issues.redhat.com/browse/UNDERTOW-2095
> [UNDERTOW-2095] undertow-examples dependency duplicated in root pom.xml file

- core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2031
> [UNDERTOW-2031] protocol error with HTTP/2 and Expect: 100-continue

- core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
https://issues.redhat.com/browse/UNDERTOW-2135
> [UNDERTOW-2135] Partial revert of hack from commit id: 55445de

- core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2124
PR for master branch.
PR for 2.2.x: https://github.com/undertow-io/undertow/pull/1358
> [UNDERTOW-2124] ProgramaticLazyEndpointTest and BinaryEndpointTest failures with JDK-17

- core/src/main/java/io/undertow/conduits/ReadTimeoutStreamSourceConduit.java
… connection is not open.
Also:
- prevent unneeded duplicate scheduling by checking if handle is null before rescheduling
- calculate the elapsed time in the expiration properly when throwing the timeout exception
Jira: https://issues.redhat.com/browse/UNDERTOW-2125
incorporates https://issues.redhat.com/browse/UNDERTOW-2083
> [UNDERTOW-2125] [UNDERTOW-2083] Fixes for ReadTimeoutStreamSourceConduit

- core/src/main/java/io/undertow/websockets/core/WebSocketChannel.java
- core/src/main/java/io/undertow/websockets/core/WebSocketMessages.java
- core/src/test/java/io/undertow/websockets/core/protocol/AbstractWebSocketServerTest.java
- core/src/test/java/io/undertow/websockets/utils/WebSocketTestClient.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1934
Ref: https://github.com/undertow-io/undertow/pull/1293
> [UNDERTOW-1934] invoke onClose in case of network failure

- servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
- servlet/src/test/java/io/undertow/servlet/test/security/constraint/SecurityConstraintUrlMappingWithUnspecifiedForbiddenTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-1997
> [UNDERTOW-1997] Corrected handling of security constraints with URL pattern '/'

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2159
> [UNDERTOW-2159] add null check to SessionManager

- core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
UNDERTOW-2109 create large file in expected location
> [UNDERTOW-2109] The large file is in unexpected location on JDK17

- core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2160
This improves the test case by writing bytes directly,
and syncing writes in an attempt to fix flakes. On failure,
additional diagnostic information is provided.
Note that failure to delete the file is ignored due to potential
races on Windows, where the file may be locked.
> [UNDERTOW-2160] FileHandlerTestCase.testFileTransferLargeFile improvement

- core/src/main/java/io/undertow/io/UndertowOutputStream.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
https://issues.redhat.com/browse/UNDERTOW-2145
> UNDERTOW-2145 OutputStreams only awaitWritable after a write returns zero

- core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
- core/src/test/java/io/undertow/server/handlers/ChunkedResponseTransferCodingTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2142
> UNDERTOW-2142 ChunkedStreamSinkConduit.write writes all requested buffers

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
https://issues.redhat.com/browse/UNDERTOW-2147
master PR: #1375
> [UNDERTOW-2147] fix race condition between session changeSessionId and invalidate"

- core/src/main/java/io/undertow/server/SSLSessionInfo.java
https://issues.redhat.com/browse/UNDERTOW-2140
> [UNDERTOW-2140] improve cipher suite len match

- core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
- core/src/main/java/io/undertow/io/UndertowOutputStream.java
- core/src/main/java/io/undertow/server/SSLSessionInfo.java
- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
- core/src/test/java/io/undertow/server/handlers/ChunkedResponseTransferCodingTestCase.java
- core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Backport recent bug fixes to 2.2.x branch.
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2159 #1373 
https://issues.redhat.com/browse/UNDERTOW-2145 #1369 
https://issues.redhat.com/browse/UNDERTOW-2140 #1368
https://issues.redhat.com/browse/UNDERTOW-2142 #1363 
https://issues.redhat.com/browse/UNDERTOW-2109  #1338
> [UNDERTOW-2159][UNDERTOW-2145][UNDERTOW-2140][UNDERTOW-2142][UNDERTOW-2109] Port fixes

- core/src/main/java/io/undertow/UndertowOptions.java
- core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- core/src/main/java/io/undertow/util/Cookies.java
- core/src/main/java/io/undertow/util/SecurityActions.java
- servlet/src/test/java/io/undertow/servlet/test/protocol/cookie/CookieAssemblyTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2082
This is just temp(for now) for review and discussion.
> [UNDERTOW-2082] reassemble cookie crumbs

- core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
- core/src/test/java/io/undertow/server/handlers/builder/PredicatedHandlersParserTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2163
Two changes mainly:
* Now if a required attribute is not passed to the handler or the predicate an error is thrown at parse time. I have checked and missing a required attribute almost always means a NPE when constructing the handler/predicate.
* Fix for the quoted string when escaping a quote. Previously a `StringIndexOutOfBoundsException` was thrown if passing the empty string `''` or `""` and the backslash was not removed when escaping the quote.
* Tests added for the new cases.
@fl4via @ropalka If you think that adding the required check is not safe just let me know. I have tested several handlers and predicates and it's almost always a NPE, so I think that it's OK.
> [UNDERTOW-2163] Predicate Language cannot set attribute to empty string

- benchmarks/pom.xml
- core/pom.xml
- coverage-report/pom.xml
- dist/assembly.xml
- dist/pom.xml
- examples/pom.xml
- karaf/pom.xml
- karaf/src/main/resources/features.xml
- parser-generator/pom.xml
- pom.xml
- servlet/pom.xml
- websockets-jsr/pom.xml
Jira: https://issues.redhat.com/browse/UNDERTOW-2168
> Final Undertow Master Cleanup

- core/src/test/java/io/undertow/server/handlers/ActiveRequestTrackerTest.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2176
@fl4via @ropalka Just a minor change in a test that is failing intermittently. I'm changing to use a latch to ensure the statistics are retrieved and avoid weird races. There is a max wait of 5s just in case.
> [UNDERTOW-2176] ActiveRequestTrackerTest.testRequestTracking fails intermittently

- servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
https://issues.redhat.com/browse/UNDERTOW-2123
> [UNDERTOW-2123] always URL decode pathInfo and servletPath as required by Servlet specification

- core/src/main/java/io/undertow/security/impl/SimpleNonceManager.java
- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
- core/src/main/java/io/undertow/server/handlers/builder/RewriteHandlerBuilder.java
- core/src/main/java/io/undertow/websockets/client/WebSocket13ClientHandshake.java
- core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
- core/src/test/java/io/undertow/server/handlers/builder/PredicatedHandlersParserTestCase.java
- core/src/test/java/io/undertow/testutils/DefaultServer.java
- servlet/src/main/java/io/undertow/servlet/core/ManagedFilter.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilter.java
- servlet/src/test/java/io/undertow/servlet/test/dispatchingfilter/DispatchingFilterTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/session/CrossContextServletBrokenSessionFactoryTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/AbstractServletInputStreamTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/AsyncInputStreamServlet.java
- servlet/src/test/java/io/undertow/servlet/test/streams/AsyncOutputStreamServlet.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamRequestBufferingTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/streams/ServletInputStreamTestCase.java
- spotbugs-exclude.xml
https://issues.redhat.com/browse/UNDERTOW-1818
https://issues.redhat.com/browse/UNDERTOW-1971
https://issues.redhat.com/browse/UNDERTOW-2069
https://issues.redhat.com/browse/UNDERTOW-2097
https://issues.redhat.com/browse/UNDERTOW-2111
https://issues.redhat.com/browse/UNDERTOW-2141
https://issues.redhat.com/browse/UNDERTOW-2162
https://issues.redhat.com/browse/UNDERTOW-2163
> Upstream backports to 2.2.x branch

- CODE_OF_CONDUCT.md
Jira: https://issues.redhat.com/browse/UNDERTOW-2204
> [UNDERTOW-2204] Add a CODE_OF_CONDUCT.md file

- core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
- servlet/src/main/java/io/undertow/servlet/handlers/ServletInitialHandler.java
Hi,
this PR resolves  https://issues.redhat.com/browse/UNDERTOW-2196. 
I took the freedom to also apply some polishing in `ServletInitialHandler.isMultiPartExchange`. Hope that's okay.
Let me know if you need anything from me to get this merged.
Cheers,
Christoph
> [UNDERTOW-2196] Reduce allocations caused by HttpString

- servlet/src/main/java/io/undertow/servlet/handlers/Paths.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/foo/meta-inf/notsecret
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/foo/web-inf/notsecret
https://issues.redhat.com/browse/UNDERTOW-2186
> [UNDERTOW-2186] allow WEB-INF or META-INF subdirectory access

- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
- servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
- servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchPathTestServlet.java
- servlet/src/test/java/io/undertow/servlet/test/async/AsyncDispatchServlet.java
- servlet/src/test/java/io/undertow/servlet/test/async/SimpleAsyncTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherForwardTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/ForwardPathTestServlet.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java
- servlet/src/test/java/io/undertow/servlet/test/spec/PathTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2206
Backport to 2.2.x of PR: https://github.com/undertow-io/undertow/pull/1411
Only changes jakarta -> javax needed.
> [UNDERTOW-1591][UNDERTOW-2123][UNDERTOW-2206] IAE trying to decode a requestPath (2.2.x)

- servlet/src/main/java/io/undertow/servlet/core/SessionListenerBridge.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2184
Upstream PR: https://github.com/undertow-io/undertow/pull/1405
> [UNDERTOW-2184] - properly propagate sessionChanged callback

- CODE_OF_CONDUCT.md
- core/src/main/java/io/undertow/UndertowOptions.java
- core/src/main/java/io/undertow/channels/DetachableStreamSourceChannel.java
- core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
- core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
- core/src/main/java/io/undertow/server/HttpServerExchange.java
- core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
- core/src/main/java/io/undertow/server/handlers/resource/ResourceHandler.java
- core/src/test/java/io/undertow/client/http/HttpClientSNITestCase.java
- core/src/test/java/io/undertow/server/handlers/file/FileHandlerTestCase.java
- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
- servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletNoDirectoryListingTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/defaultservlet/DefaultServletTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2054
https://issues.redhat.com/browse/UNDERTOW-2190
https://issues.redhat.com/browse/UNDERTOW-2188
https://issues.redhat.com/browse/UNDERTOW-2189
https://issues.redhat.com/browse/UNDERTOW-2202
https://issues.redhat.com/browse/UNDERTOW-2204
> [UNDERTOW-2054][UNDERTOW-2190][UNDERTOW-2188][UNDERTOW-2189][UNDERTOW-2202][UNDERTOW-2204] Backport fixes to 2.2.x

- servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2209
> [UNDERTOW-2209] Ignore defaultPath security when it is not configured at all

- servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2213
Reverts fixes for UNDERTOW-2188 and UNDERTOW-2209 for investigation of related TCK failures
> [UNDERTOW-2213] Revert deny-uncovered-methods fix for corner case

- core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
- core/src/test/java/io/undertow/predicate/PredicateParsingTestCase.java
- core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1748
> [UNDERTOW-1748] add comment line to predicates

- .github/workflows/ci.yml
> Update CI: run weekly for 2.2.x branch

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Fixes https://issues.redhat.com/browse/UNDERTOW-2208
> [UNDERTOW-2208] Enhance SNI hostname creation exception text

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/protocols/ssl/UndertowXnioSsl.java
Fixes https://issues.redhat.com/browse/UNDERTOW-2208
Upstream https://github.com/undertow-io/undertow/pull/1420
> [UNDERTOW-2208][2.2.x] Enhance SNI hostname creation exception text

- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/util/NetworkUtils.java
- core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1890
> [UNDERTOW-1890] - fix NetworkUtils exceptions

- core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
- core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1885
> [UNDERTOW-1885] remove escape char from delimitered strings

- core/src/main/java/io/undertow/attribute/ExchangeStartTimeAttribute.java
- core/src/main/resources/META-INF/services/io.undertow.attribute.ExchangeAttributeBuilder
Issue: https://issues.redhat.com/browse/UNDERTOW-1442
> [UNDERTOW-1442] Add exchange attribute to display start of processing

- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1875
> [UNDERTOW-1875] - add system property to allow ID less matrix parameters

- servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
- servlet/src/main/java/io/undertow/servlet/handlers/security/ServletSecurityConstraintHandler.java
- servlet/src/test/java/io/undertow/servlet/test/security/constraint/AuthenticationMessageServlet.java
- servlet/src/test/java/io/undertow/servlet/test/security/constraint/DenyUncoveredHttpMethodsTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2188
https://issues.redhat.com/browse/UNDERTOW-2209
https://issues.redhat.com/browse/UNDERTOW-2211
> [UNDERTOW-2211] Fix deny uncovered methods handling

- core/src/main/java/io/undertow/util/MimeMappings.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2218
> [UNDERTOW-2218] add default mime for webp

- CODEOWNERS
- CONTRIBUTING.md
- README.md
- SECURITY.md
- benchmarks/src/main/java/io/undertow/benchmarks/AsciiEncoders.java
- benchmarks/src/main/java/io/undertow/benchmarks/AsciiEncodingBenchmark.java
- core/src/main/java/io/undertow/server/handlers/builder/PredicatedHandlersParser.java
- core/src/test/java/io/undertow/server/handlers/PredicatedHandlersTestCase.java
- servlet/src/main/java/io/undertow/servlet/handlers/security/SecurityPathMatches.java
- servlet/src/main/java/io/undertow/servlet/handlers/security/ServletSecurityConstraintHandler.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
- servlet/src/test/java/io/undertow/servlet/test/security/constraint/AuthenticationMessageServlet.java
- servlet/src/test/java/io/undertow/servlet/test/security/constraint/DenyUncoveredHttpMethodsTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-1885
https://issues.redhat.com/browse/UNDERTOW-2203
https://issues.redhat.com/browse/UNDERTOW-2210
https://issues.redhat.com/browse/UNDERTOW-2211
> [UNDERTOW-1885][UNDERTOW-2203][UNDERTOW-2210][UNDERTOW-2211] Backport fixes to 2.2.x branch

- .github/workflows/ci.yml
Jira: https://issues.redhat.com/browse/UNDERTOW-2253
> [UNDERTOW-2253] Fix the CI script so it can run again

- core/src/main/java/io/undertow/UndertowLogger.java
- core/src/main/java/io/undertow/UndertowMessages.java
- core/src/main/java/io/undertow/io/BlockingReceiverImpl.java
- core/src/main/java/io/undertow/io/BlockingSenderImpl.java
- core/src/main/java/io/undertow/security/impl/SingleSignOnAuthenticationMechanism.java
- core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
- core/src/main/java/io/undertow/server/handlers/resource/PathResource.java
- core/src/main/java/io/undertow/server/handlers/resource/URLResource.java
- core/src/main/java/io/undertow/server/protocol/proxy/ProxyProtocolReadListener.java
- spotbugs-exclude.xml
Replace https://github.com/undertow-io/undertow/pull/1356
Jira: https://issues.redhat.com/browse/UNDERTOW-2093
> [UNDERTOW-2263] UNDERTOW-2093 detailed followup

- core/src/main/java/io/undertow/util/NetworkUtils.java
- core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1896
> [UNDEDRTOW-1896] - fix parsing of trailing :: in IPv6

- .github/workflows/ci.yml
- core/src/main/java/io/undertow/attribute/RequestURLAttribute.java
- core/src/main/java/io/undertow/predicate/PathPrefixPredicate.java
- core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
- core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
- core/src/main/java/io/undertow/util/NetworkUtils.java
- core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
- core/src/test/java/io/undertow/server/handlers/ResourcePredicateHandlerTestCase.java
- core/src/test/java/io/undertow/util/NetworkUtilsAddressParsingTestCase.java
- servlet/src/main/java/io/undertow/servlet/handlers/DefaultServlet.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
Jiras and PRs:
https://issues.redhat.com/browse/UNDERTOW-2250 #1451
https://issues.redhat.com/browse/UNDERTOW-2277 #1482 
https://issues.redhat.com/browse/UNDERTOW-1896 #1188 
https://issues.redhat.com/browse/UNDERTOW-2216 #1465 
https://issues.redhat.com/browse/UNDERTOW-2243 #1443 
https://issues.redhat.com/browse/UNDERTOW-2255 #1472
> [UNDERTOW-2250][UNDERTOW-2277][UNDERTOW-1896][UNDERTOW-2216][UNDERTOW-2243][UNDERTOW-2255] Backport fixes to 2.2.x branch

- servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
- servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
https://issues.redhat.com/browse/UNDERTOW-2267
> [UNDERTOW-2267] Align Servlet.init() method behaviour with previous JBoss Web implementation

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2270
Master PR: #1485
> [UNDERTOW-2270] io.undertow.servlet.spec.HttpServletRequestImpl NPE thrown

- core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
- core/src/main/java/io/undertow/conduits/WriteTimeoutStreamSinkConduit.java
- core/src/main/java/io/undertow/server/protocol/http/HttpResponseConduit.java
- core/src/test/java/io/undertow/server/handlers/LotsOfHeadersResponseTestCase.java
Duplicate of #1450 
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2241
https://issues.redhat.com/browse/UNDERTOW-2247
https://issues.redhat.com/browse/UNDERTOW-2248
Also, commenting out test for failure https://issues.redhat.com/browse/UNDERTOW-2279
Master PR: #1490
> [UNDERTOW-2241][UNDERTOW-2247][UNDERTOW-2248] Handle write timeout properly so no chunk errors occur 

- core/src/main/java/io/undertow/util/HeaderMap.java
- core/src/test/java/io/undertow/util/HeaderMapTestCase.java
- servlet/src/main/java/io/undertow/servlet/UndertowServletLogger.java
- servlet/src/main/java/io/undertow/servlet/core/DeploymentManagerImpl.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2276 #1481 
https://issues.redhat.com/browse/UNDERTOW-2267 #1473
> [UNDERTOW-2276] [UNDERTOW-2267] Backport fixes to 2.2.x branch

- core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
- core/src/main/java/io/undertow/util/FlexBase64.java
- pom.xml
https://issues.redhat.com/browse/UNDERTOW-2282
> [UNDERTOW-2282] Upgrade spotbugs to 4.7.3.4

- core/src/main/java/io/undertow/protocols/http2/Http2FrameHeaderParser.java
- core/src/main/java/io/undertow/protocols/http2/Http2HeaderBlockParser.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2281
Master PR: #1498
>  [UNDERTOW-2281] At Http2FrameHeaderParser, throw a protocol error for headers not followed by data

- servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncExceptionWriterServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncLargeResponseWriterServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncResponseWriterOnPostServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncResponseWriterServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterOnPostServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterTestCase.java
Jiras: https://issues.redhat.com/browse/UNDERTOW-2293 (see also https://issues.redhat.com/browse/UNDERTOW-2243)
> [UNDERTOW-2293] Rewrite the fix for UNDERTOW-2243 in a way to prevent extra chunked messages

- servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/DispatcherIncludeTestCase.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludePathTestServlet.java
- servlet/src/test/java/io/undertow/servlet/test/dispatcher/IncludeServlet.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2285
> [UNDERTOW-2285] Query parameters get lost in the included JSP page

- servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2296
2.x PR : https://github.com/undertow-io/undertow/pull/1507
> [UNDERTOW-2296] Wrong type in INCLUDE_MAPPING request attribute

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
https://issues.redhat.com/browse/UNDERTOW-2313
master PR: #1522
> [UNDERTOW-2313] NPE occurs in session invalidation if a session creation attempt hits UNDERTOW-1971

- core/src/main/java/io/undertow/server/session/InMemorySessionManager.java
https://issues.redhat.com/browse/UNDERTOW-2316
> [UNDERTOW-2316] Unify InMemorySessionManager with DistributableSessionManager - allow null exchanges

- core/src/main/java/io/undertow/util/Cookies.java
- core/src/test/java/io/undertow/util/CookiesTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2342
> [UNDERTOW-2342] CVE-2023-4639 ignore cookie with improper quotes

- .github/workflows/ci.yml
- core/src/main/java/io/undertow/util/HeaderValues.java
- pom.xml
https://issues.redhat.com/browse/UNDERTOW-2353
> [UNDERTOW-2353] A few adjustments to make Undertow build and test on JDK21

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/Bootstrap.java
https://issues.redhat.com/browse/UNDERTOW-2354
2.2.x PR: #1572
> [UNDERTOW-2354] Prevent NPE in Bootstrap$WebSocketListener.contextDestroyed

- pom.xml
https://issues.redhat.com/browse/UNDERTOW-2291
Replace https://github.com/undertow-io/undertow/pull/1504
> [UNDERTOW-2291] Shush jdoc and compile warning obfuscating console

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/Bootstrap.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2354
This is a back port of #1565 to `2.2.x` branch
> [UNDERTOW-2354] Prevent NPE in Bootstrap.contextDestroyed

- core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2407
https://issues.redhat.com/browse/UNDERTOW-2408
> [UNDERTOW-2407][UNDERTOW-2408] Prevent the NPE at DefaultByteBufferPool.close() and minor code enhancements

- servlet/src/main/java/io/undertow/servlet/handlers/security/ServletFormAuthenticationMechanism.java
https://issues.redhat.com/browse/UNDERTOW-2409
> [UNDERTOW-2409] Adjust properly session timeout also in case when GET requests with custom auth mechanisms are used

- core/src/main/java/io/undertow/UndertowLogger.java
- core/src/main/java/io/undertow/server/DefaultByteBufferPool.java
- core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
- core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingSender.java
- core/src/main/java/io/undertow/server/handlers/cache/ResponseCachingStreamSinkConduit.java
- core/src/main/java/io/undertow/server/handlers/resource/CachedResource.java
- core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
- pom.xml
- servlet/src/test/java/io/undertow/servlet/test/response/writer/AsyncResponseWriterOnPostServlet.java
- servlet/src/test/java/io/undertow/servlet/test/response/writer/ResponseWriterOnPostServlet.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2291
https://issues.redhat.com/browse/UNDERTOW-2332
https://issues.redhat.com/browse/UNDERTOW-2400
https://issues.redhat.com/browse/UNDERTOW-2385
> [UNDERTOW-2291][UNDERTOW-2332][UNDERTOW-2400][UNDERTOW-2385] Backport bug fixes to 2.2.x branch

- .github/workflows/ci.yml
Issue: https://issues.redhat.com/browse/UNDERTOW-2398
> [UNDERTOW-2398] Tweak workflow to allow manual re-runs

- pom.xml
Jira: https://issues.redhat.com/browse/UNDERTOW-2417
> [UNDERTOW-2417] Fix typo in pom config for show warnings

- .github/workflows/ci.yml
Issue: https://issues.redhat.com/browse/UNDERTOW-2386
Maintenance branch: https://github.com/undertow-io/undertow/pull/1623
> [UNDERTOW-2386] Update ci.yml git doc link

- core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2397
Upstream PR: https://github.com/undertow-io/undertow/pull/1629
> [UNDERTOW-2397] Properly index huffman table on encoding

- core/src/main/java/io/undertow/UndertowOptions.java
Issue: https://issues.redhat.com/browse/UNDERTOW-2193
Upstream PR: https://github.com/undertow-io/undertow/pull/1568
2.2.x: https://github.com/undertow-io/undertow/pull/1624
> [UNDERTOW-2193] Add uniform unity description to UndertowOptions

- core/src/main/java/io/undertow/Handlers.java
- core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
- core/src/main/java/io/undertow/server/handlers/PathHandler.java
- core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
- core/src/main/java/io/undertow/server/handlers/cache/LRUCache.java
- core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2382
> [UNDERTOW-2382] CVE-2024-3653 Switch to LRUCache to store entries in cache in LearningPushHandler

- core/src/main/java/io/undertow/Handlers.java
- core/src/main/java/io/undertow/protocols/ssl/SslConduit.java
- core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java
- core/src/main/java/io/undertow/server/handlers/PathHandler.java
- core/src/main/java/io/undertow/server/handlers/cache/DirectBufferCache.java
- core/src/main/java/io/undertow/server/handlers/cache/LRUCache.java
- core/src/main/java/io/undertow/server/handlers/resource/CachingResourceManager.java
- servlet/src/main/java/io/undertow/servlet/handlers/ServletPathMatches.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletContextImpl.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2413 main PR: #1638 
https://issues.redhat.com/browse/UNDERTOW-2382 main PR: #1639 
2.2.x PR: #1641
> [UNDERTOW-2413][UNDERTOW-2382] CVE-2024-5971 CVE-2024-3653  Backport bug fixes

- core/src/main/java/io/undertow/UndertowMessages.java
- servlet/src/main/java/io/undertow/servlet/UndertowServletMessages.java
- servlet/src/main/java/io/undertow/servlet/spec/HttpServletRequestImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/HttpServletResponseImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
Issues: https://issues.redhat.com/browse/UNDERTOW-1485
> [UNDERTOW-1485] fix some wrong letter

- examples/src/main/java/io/undertow/examples/predicates/PredicateParser.java
https://issues.redhat.com/browse/UNDERTOW-2335
> [UNDERTOW-2335] Add an example of the PredicatesHandler and specifically the predicate handler parser

- servlet/src/main/java/io/undertow/servlet/api/DeploymentInfo.java
- servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
Issue: https://issues.redhat.com/browse/UNDERTOW-1870
> [UNDERTOW-1870] - make AsyncContext.timeout configurable per deployment

- core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
- core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
- core/src/test/java/io/undertow/protocols/http2/HpackHuffmanDecodingStringLiteralRepresentation.java
- core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2256
https://issues.redhat.com/browse/UNDERTOW-2381
> [UNDERTOW-2256][UNDERTOW-2381] Backport fixes to 2.2.x

- core/src/main/java/io/undertow/protocols/http2/HPackHuffman.java
- core/src/main/java/io/undertow/server/handlers/resource/DirectoryUtils.java
- core/src/test/java/io/undertow/protocols/http2/HpackHuffmanDecodingStringLiteralRepresentation.java
- core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
- pom.xml
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2417
https://issues.redhat.com/browse/UNDERTOW-2256
https://issues.redhat.com/browse/UNDERTOW-2381
> [UNDERTOW-2417][UNDERTOW-2256][UNDERTOW-2381] Backport fixes to 2.3.x

- core/src/test/java/io/undertow/server/handlers/file/FileHandlerWithPredicateTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2256
> [UNDERTOW-2256] Add missing header

- core/src/main/java/io/undertow/conduits/ChunkedStreamSinkConduit.java
- core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
- core/src/main/java/io/undertow/server/Connectors.java
- core/src/main/java/io/undertow/server/protocol/ajp/AjpRequestParser.java
- core/src/main/java/io/undertow/server/protocol/http/HttpRequestParser.java
- core/src/main/java/io/undertow/server/protocol/http2/Http2ReceiveListener.java
- core/src/main/java/io/undertow/server/protocol/http2/Http2ServerConnection.java
- core/src/main/java/io/undertow/server/protocol/http2/Http2UpgradeHandler.java
- core/src/test/java/io/undertow/conduits/ChunkedStreamSinkConduitTest.java
- core/src/test/java/io/undertow/server/handlers/accesslog/AccessLogFileWithUnescapedCharactersTestCase.java
- core/src/test/java/io/undertow/server/protocol/ajp/AjpCharacterEncodingTestCase.java
- core/src/test/java/io/undertow/server/protocol/http/SimpleParserTestCase.java
- servlet/src/main/java/io/undertow/servlet/spec/AsyncContextImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/RequestDispatcherImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletOutputStreamImpl.java
- servlet/src/main/java/io/undertow/servlet/spec/ServletPrintWriter.java
- servlet/src/main/java/io/undertow/servlet/util/DispatchUtils.java
- spotbugs-exclude.xml
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2312 #1516 
https://issues.redhat.com/browse/UNDERTOW-2425 #1647 
https://issues.redhat.com/browse/UNDERTOW-2424 #1645 
Backport to 2.3.x branch: #1653
> [UNDERTOW-2312][UNDERTOW-2425][UNDERTOW-2424] Backport fixes

- .github/workflows/ci.yml
- core/src/test/java/io/undertow/protocols/http2/PushResourceRSTTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2449
> [UNDERTOW-2449] Fix PushResourceRSTTestCase

- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/suspendresume/SuspendResumeTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2505
> [UNDERTOW-2505] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.suspendresume

- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
https://issues.redhat.com/browse/UNDERTOW-2502
> [UNDERTOW-2502] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.extension

- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/ThreadSafetyEndpoint.java
https://issues.redhat.com/browse/UNDERTOW-2499
> [UNDERTOW-2499] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.annotated

- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DoUpgradeServlet.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/EchoProgramaticEndpoint.java
https://issues.redhat.com/browse/UNDERTOW-2501
> [UNDERTOW-2501] Review anonymous classes in Undertow io.undertow.websockets.jsr.test.dynamicupgrade

- core/src/main/java/io/undertow/server/handlers/accesslog/AccessLogHandler.java
https://issues.redhat.com/browse/UNDERTOW-2321
> [UNDERTOW-2321] Document new commonv pattern in accesslog handler

- .github/workflows/ci.yml
https://issues.redhat.com/browse/UNDERTOW-2548
Update various action versions
> UNDERTOW-2548 - Update action versions in workflow

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/JsrWebSocketMessages.java
- websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketSessionRemoteEndpoint.java
https://issues.redhat.com/browse/UNDERTOW-2532
Upstream PR: https://github.com/undertow-io/undertow/pull/1708
> [UNDERTOW-2532] Fix NPE when transmitting text or binary message to websocket session at the same time

- core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
https://issues.redhat.com/browse/UNDERTOW-2547
Modify conduit to perform a gather write to decrease latency
> UNDERTOW-2547 - Perform gathering write

- websockets-jsr/src/main/java/io/undertow/websockets/jsr/JsrWebSocketMessages.java
- websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketSessionRemoteEndpoint.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2532
> [UNDERTOW-2532] At WebSocketSessionRemoteEndpoint, prevent the NPE by setting a local sender field before checking for null

- core/src/test/java/io/undertow/websockets/core/protocol/WebSocketTimeoutTestCase.java
Jira: https://issues.redhat.com/browse/UNDERTOW-2518
2.2.x PR: #1746 
2.3.x PR: #1745
> [UNDERTOW-2518] Tidy up the WebSocketTimeoutTestCase a bit more

- core/src/main/java/io/undertow/websockets/core/CloseMessage.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/annotated/ThreadSafetyEndpoint.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/DoUpgradeServlet.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/dynamicupgrade/EchoProgramaticEndpoint.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/extension/JsrWebsocketExtensionTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/reconnect/ClientEndpointReconnectTestCase.java
- websockets-jsr/src/test/java/io/undertow/websockets/jsr/test/stress/WebsocketStressTestCase.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2506 Main PR: #1701 
https://issues.redhat.com/browse/UNDERTOW-2503 Main PR: #1700 
https://issues.redhat.com/browse/UNDERTOW-2502 Main PR: #1697 
https://issues.redhat.com/browse/UNDERTOW-2499 Main PR: #1696 
https://issues.redhat.com/browse/UNDERTOW-2501 Main PR: #1695 
https://issues.redhat.com/browse/UNDERTOW-2520 Main PR: #1699 
2.3.x PR: #1750
> [UNDERTOW-2506 / 2503 / 2502 / 2499 / 2501 / 2520] Backport fixes to 2.2.x

- core/src/main/java/io/undertow/client/http/HttpRequestConduit.java
- core/src/main/java/io/undertow/protocols/http2/HpackDecoder.java
- servlet/src/main/java/io/undertow/servlet/attribute/ServletRelativePathAttribute.java
- websockets-jsr/src/main/java/io/undertow/websockets/jsr/WebSocketSessionRemoteEndpoint.java
Jiras:
https://issues.redhat.com/browse/UNDERTOW-2511 Main PR: #1715 
https://issues.redhat.com/browse/UNDERTOW-2538 Main PR: #1714 
https://issues.redhat.com/browse/UNDERTOW-2532 Main PR: #1736 
https://issues.redhat.com/browse/UNDERTOW-2547 Main PR: #1721 
2.3.x PR: #1754
> [UNDERTOW-2511 / 2538 / 2532 / 2547 ] CVE-2024-4109 Backport fixes to 2.2.x

- pom.xml
Jira:
https://issues.redhat.com/browse/UNDERTOW-2586
Related Jiras:
https://issues.redhat.com/browse/UNDERTOW-2583 PR: #1765 
https://issues.redhat.com/browse/UNDERTOW-2584 PR: #1767
> [UNDERTOW-2586] Upgrade JBoss Threads to 3.7.0.Final

- core/src/main/java/io/undertow/server/handlers/form/MultiPartParserDefinition.java
- core/src/main/java/io/undertow/server/handlers/proxy/ProxyHandler.java
- core/src/main/java/io/undertow/server/protocol/framed/AbstractFramedChannel.java
- core/src/main/java/io/undertow/server/protocol/http/HttpContinue.java
- core/src/main/java/io/undertow/server/protocol/http/HttpTransferEncoding.java
- core/src/test/java/io/undertow/server/MaxRequestSizeTestCase.java
- core/src/test/java/io/undertow/server/handlers/proxy/ProxyHandlerXForwardedForTestCase.java
- core/src/test/java/io/undertow/testutils/DefaultServer.java
Jiras: 
https://issues.redhat.com/browse/UNDERTOW-2573 Main PR: #1740 
https://issues.redhat.com/browse/UNDERTOW-2564 Main PR: #1730 
https://issues.redhat.com/browse/UNDERTOW-2556 Main PR: #1727 
https://issues.redhat.com/browse/UNDERTOW-2574 Main PR: #1744 
https://issues.redhat.com/browse/UNDERTOW-2576 Main PR: #1757 
2.3.x PR: #1769
> [UNDERTOW-2573 / 2564 / 2556 / 2574 / 2576 ] Backport fixes and enhancements to 2.2.x
